BattleFrontier_Lounge4_MapScripts:: @ 826358C
	.byte 0

BattleFrontier_Lounge4_EventScript_26358D:: @ 826358D
	msgbox BattleFrontier_Lounge4_Text_2635A8, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_263596:: @ 8263596
	msgbox BattleFrontier_Lounge4_Text_2635EC, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_26359F:: @ 826359F
	msgbox BattleFrontier_Lounge4_Text_263625, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_2635A8: @ 82635A8
	.string "Je me demande s'il y aura des interviews\n"
	.string "de bons DRESSEURS aujourd'hui.$"

BattleFrontier_Lounge4_Text_2635EC: @ 82635EC
	.string "Si j'ouvrais un restaurant ici, je\n"
	.string "ferais fortune!$"

BattleFrontier_Lounge4_Text_263625: @ 8263625
	.string "Pfiou…\p"
	.string "J'aurais besoin de faire le vide dans\n"
	.string "ma tête entre deux combats…\p"
	.string "Mais je n'arrête jamais de penser à\n"
	.string "ma stratégie.$"

