SlateportCity_SternsShipyard_2F_MapScripts:: @ 820863D
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_20863E:: @ 820863E
	msgbox SlateportCity_SternsShipyard_2F_Text_208650, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_208647:: @ 8208647
	msgbox SlateportCity_SternsShipyard_2F_Text_2086BA, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_208650: @ 8208650
	.string "Concevoir un grand bateau relève plus\n"
	.string "de la construction d'un vaste bâtiment\l"
	.string "que de l'assemblage d'un véhicule.$"

SlateportCity_SternsShipyard_2F_Text_2086BA: @ 82086BA
	.string "C'est étrange qu'un bateau fait d'acier\n"
	.string "puisse flotter, non?\p"
	.string "S'il flotte, c'est dû à ce que l'on\n"
	.string "appelle le principe de flottabilité.$"

