MagmaHideout_2F_1R_MapScripts:: @ 8239B50
	.byte 0

MagmaHideout_2F_1R_EventScript_239B51:: @ 8239B51
	trainerbattle_single TRAINER_GRUNT_51, MagmaHideout_2F_1R_Text_239BAD, MagmaHideout_2F_1R_Text_239C4B
	msgbox MagmaHideout_2F_1R_Text_239C74, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_239B68:: @ 8239B68
	trainerbattle_single TRAINER_GRUNT_40, MagmaHideout_2F_1R_Text_239CAB, MagmaHideout_2F_1R_Text_239D09
	msgbox MagmaHideout_2F_1R_Text_239D1D, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_239B7F:: @ 8239B7F
	trainerbattle_single TRAINER_GRUNT_41, MagmaHideout_2F_1R_Text_239D62, MagmaHideout_2F_1R_Text_239D75
	msgbox MagmaHideout_2F_1R_Text_239D7D, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_239B96:: @ 8239B96
	trainerbattle_single TRAINER_GRUNT_42, MagmaHideout_2F_1R_Text_239DC5, MagmaHideout_2F_1R_Text_239DDA
	msgbox MagmaHideout_2F_1R_Text_239DE2, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_Text_239BAD: @ 8239BAD
	.string "Pas si vite!\p"
	.string "Seuls les membres de la TEAM MAGMA\n"
	.string "sont autorisés à être ici!\p"
	.string "Mais tu ne portes pas notre uniforme…\p"
	.string "Il vaut mieux que je sois sûre!\n"
	.string "Allez, viens te battre!$"

MagmaHideout_2F_1R_Text_239C4B: @ 8239C4B
	.string "Aïe…\n"
	.string "Mon honneur vient d'en prendre un coup.$"

MagmaHideout_2F_1R_Text_239C74: @ 8239C74
	.string "Si tu n'aimes pas avoir froid,\n"
	.string "rejoins la TEAM MAGMA!$"

MagmaHideout_2F_1R_Text_239CAB: @ 8239CAB
	.string "Attends un peu toi!\p"
	.string "Tu pensais vraiment pouvoir passer\n"
	.string "devant moi comme ça?$"

MagmaHideout_2F_1R_Text_239D09: @ 8239D09
	.string "Bon d'accord, j'ai rien dit.$"

MagmaHideout_2F_1R_Text_239D1D: @ 8239D1D
	.string "J'aurais sûrement mieux fait de\n"
	.string "te laisser passer directement…$"

MagmaHideout_2F_1R_Text_239D62: @ 8239D62
	.string "Ah ah!\n"
	.string "Un intrus!$"

MagmaHideout_2F_1R_Text_239D75: @ 8239D75
	.string "Graaah!$"

MagmaHideout_2F_1R_Text_239D7D: @ 8239D7D
	.string "J'ai perdu…\p"
	.string "Est-ce que je dois continuer à\n"
	.string "tourner en rond bêtement?$"

MagmaHideout_2F_1R_Text_239DC5: @ 8239DC5
	.string "Oh oh!\n"
	.string "Un intrus!$"

MagmaHideout_2F_1R_Text_239DDA: @ 8239DDA
	.string "Humpff…$"

MagmaHideout_2F_1R_Text_239DE2: @ 8239DE2
	.string "En fait, les combats n'ont jamais été\n"
	.string "ma spécialité…$"

