VerdanturfTown_House_MapScripts:: @ 820335E
	.byte 0

VerdanturfTown_House_EventScript_20335F:: @ 820335F
	msgbox VerdanturfTown_House_Text_203371, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_203368:: @ 8203368
	msgbox VerdanturfTown_House_Text_2033EE, MSGBOX_NPC
	end

VerdanturfTown_House_Text_203371: @ 8203371
	.string "Au loin, au fin fond d'ETERNARA,\n"
	.string "se trouve la LIGUE POKéMON.\p"
	.string "Les DRESSEURS qui s'y retrouvent sont\n"
	.string "terriblement doués.$"

VerdanturfTown_House_Text_2033EE: @ 82033EE
	.string "Dans la LIGUE POKéMON, la règle stipule\n"
	.string "que tu dois battre tous les membres\l"
	.string "du CONSEIL 4 consécutivement.\p"
	.string "Si tu perds contre l'un d'entre eux, tu\n"
	.string "dois reprendre le défi depuis le début.$"

