SootopolisCity_House5_MapScripts:: @ 8226E93
	.byte 0

SootopolisCity_House5_EventScript_226E94:: @ 8226E94
	msgbox SootopolisCity_House5_Text_226EA6, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_226E9D:: @ 8226E9D
	msgbox SootopolisCity_House5_Text_226F35, MSGBOX_NPC
	end

SootopolisCity_House5_Text_226EA6: @ 8226EA6
	.string "Il semblerait qu'il existe un rapport\n"
	.string "entre ATALANOPOLIS et le MONT MEMORIA.\p"
	.string "Avec mes amis, on a fait des recherches\n"
	.string "à ce sujet au labo où je travaillais.$"

SootopolisCity_House5_Text_226F35: @ 8226F35
	.string "Mon grand frère étudie la mer.$"

