VictoryRoad_B2F_MapScripts:: @ 82368D4
	.byte 0

VictoryRoad_B2F_EventScript_2368D5:: @ 82368D5
	trainerbattle_single TRAINER_VITO, VictoryRoad_B2F_Text_23695F, VictoryRoad_B2F_Text_2369B3
	msgbox VictoryRoad_B2F_Text_2369DE, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_2368EC:: @ 82368EC
	trainerbattle_single TRAINER_OWEN, VictoryRoad_B2F_Text_236A4C, VictoryRoad_B2F_Text_236A92
	msgbox VictoryRoad_B2F_Text_236AAE, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_236903:: @ 8236903
	trainerbattle_single TRAINER_CAROLINE, VictoryRoad_B2F_Text_236AF0, VictoryRoad_B2F_Text_236B14
	msgbox VictoryRoad_B2F_Text_236B2F, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_23691A:: @ 823691A
	trainerbattle_single TRAINER_JULIE, VictoryRoad_B2F_Text_236B88, VictoryRoad_B2F_Text_236C0A
	msgbox VictoryRoad_B2F_Text_236C21, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_236931:: @ 8236931
	trainerbattle_single TRAINER_FELIX, VictoryRoad_B2F_Text_236C67, VictoryRoad_B2F_Text_236CAB
	msgbox VictoryRoad_B2F_Text_236CBA, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_236948:: @ 8236948
	trainerbattle_single TRAINER_DIANNE, VictoryRoad_B2F_Text_236D27, VictoryRoad_B2F_Text_236D6E
	msgbox VictoryRoad_B2F_Text_236D8C, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_Text_23695F: @ 823695F
	.string "On s'entraîne tous ensemble, avec\n"
	.string "les membres de ma famille!\l"
	.string "Je ne perds contre personne!$"

VictoryRoad_B2F_Text_2369B3: @ 82369B3
	.string "Tu as un meilleur niveau que ma famille?!\n"
	.string "Est-ce possible?!$"

VictoryRoad_B2F_Text_2369DE: @ 82369DE
	.string "J'ai toujours été le meilleur de la\n"
	.string "famille. Je n'avais encore jamais perdu…\p"
	.string "J'ai perdu confiance en moi…\n"
	.string "Je vais peut-être rentrer chez moi…$"

VictoryRoad_B2F_Text_236A4C: @ 8236A4C
	.string "On m'avait dit qu'il y avait un môme\n"
	.string "très fort. C'est de toi qu'ils parlaient?$"

VictoryRoad_B2F_Text_236A92: @ 8236A92
	.string "La demi-portion est forte!$"

VictoryRoad_B2F_Text_236AAE: @ 8236AAE
	.string "D'après les rumeurs, le p'tit môme\n"
	.string "très fort viendrait de CLEMENTI-VILLE.$"

VictoryRoad_B2F_Text_236AF0: @ 8236AF0
	.string "Tu dois commencer à fatiguer.$"

VictoryRoad_B2F_Text_236B14: @ 8236B14
	.string "Aucun signe de fatigue du tout!$"

VictoryRoad_B2F_Text_236B2F: @ 8236B2F
	.string "La ROUTE VICTOIRE et la LIGUE POKéMON\n"
	.string "sont des défis épuisants et de longue\l"
	.string "haleine. Gare à la fatigue!$"

VictoryRoad_B2F_Text_236B88: @ 8236B88
	.string "Avoir beaucoup de BADGES ne suffit pas.\p"
	.string "Il y aura toujours quelqu'un de plus\n"
	.string "fort que toi!$"

VictoryRoad_B2F_Text_236C0A: @ 8236C0A
	.string "Tu as un meilleur niveau que moi!$"

VictoryRoad_B2F_Text_236C21: @ 8236C21
	.string "Regarde bien tes BADGES et rappelle-\n"
	.string "toi quels DRESSEURS tu as affrontés.$"

VictoryRoad_B2F_Text_236C67: @ 8236C67
	.string "Je suis arrivé jusqu'ici, mais le stress\n"
	.string "me donne des maux d'estomac…$"

VictoryRoad_B2F_Text_236CAB: @ 8236CAB
	.string "Oooh…\n"
	.string "Ça fait mal…$"

VictoryRoad_B2F_Text_236CBA: @ 8236CBA
	.string "Je ne peux pas m'empêcher de stresser\n"
	.string "en sachant que la LIGUE POKéMON\l"
	.string "est si proche.\p"
	.string "J'arrive à peine à me détendre.$"

VictoryRoad_B2F_Text_236D27: @ 8236D27
	.string "L'élite de l'élite se réunit dans\n"
	.string "cette grotte.\p"
	.string "T'en penses quoi?$"

VictoryRoad_B2F_Text_236D6E: @ 8236D6E
	.string "Pas une seule fausse note!$"

VictoryRoad_B2F_Text_236D8C: @ 8236D8C
	.string "T'as du cran, continue comme ça!$"

