BattleFrontier_Lounge8_MapScripts:: @ 82676C9
	.byte 0

BattleFrontier_Lounge8_EventScript_2676CA:: @ 82676CA
	msgbox BattleFrontier_Lounge8_Text_2676E5, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_2676D3:: @ 82676D3
	msgbox BattleFrontier_Lounge8_Text_26779C, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_2676DC:: @ 82676DC
	msgbox BattleFrontier_Lounge8_Text_26782C, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_2676E5: @ 82676E5
	.string "Ce dont un DRESSEUR a besoin…\p"
	.string "Savoir…\n"
	.string "Tactique…\l"
	.string "Chance…\l"
	.string "Cran…\l"
	.string "Esprit…\l"
	.string "Bravoure…\l"
	.string "Capacité…\p"
	.string "Parfait, je suis prêt!\n"
	.string "Je vais relever tous les défis!\p"
	.string "Quoi? Des POKéMON?\n"
	.string "C'est quoi ça?$"

BattleFrontier_Lounge8_Text_26779C: @ 826779C
	.string "Tu as entendu parler des MENEURS DE\n"
	.string "ZONE?\p"
	.string "C'est ainsi que SCOTT appelle les sept\n"
	.string "DRESSEURS responsables de chaque\l"
	.string "bâtiment de la ZONE DE COMBAT.$"

BattleFrontier_Lounge8_Text_26782C: @ 826782C
	.string "A la TOUR DE COMBAT, une fille m'a dit\n"
	.string "que j'avais beaucoup de talent!\p"
	.string "Moi, je préfère les CONCOURS POKéMON!\n"
	.string "Mais je ne suis pas fort!\p"
	.string "On n'est pas forcément doué pour les\n"
	.string "choses qu'on aime…$"
