MagmaHideout_2F_2R_MapScripts:: @ 8239E07
	.byte 0

MagmaHideout_2F_2R_EventScript_239E08:: @ 8239E08
	trainerbattle_single TRAINER_GRUNT_52, MagmaHideout_2F_2R_Text_239E64, MagmaHideout_2F_2R_Text_239EA5
	msgbox MagmaHideout_2F_2R_Text_239EBB, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_239E1F:: @ 8239E1F
	trainerbattle_single TRAINER_GRUNT_43, MagmaHideout_2F_2R_Text_239F31, MagmaHideout_2F_2R_Text_239F71
	msgbox MagmaHideout_2F_2R_Text_239FA1, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_239E36:: @ 8239E36
	trainerbattle_single TRAINER_GRUNT_44, MagmaHideout_2F_2R_Text_239FDE, MagmaHideout_2F_2R_Text_23A050
	msgbox MagmaHideout_2F_2R_Text_23A07D, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_239E4D:: @ 8239E4D
	trainerbattle_single TRAINER_GRUNT_45, MagmaHideout_2F_2R_Text_23A0E4, MagmaHideout_2F_2R_Text_23A14C
	msgbox MagmaHideout_2F_2R_Text_23A16F, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_Text_239E64: @ 8239E64
	.string "Je n'ai rien contre toi…\n"
	.string "Mais je dois suivre les ordres!$"

MagmaHideout_2F_2R_Text_239EA5: @ 8239EA5
	.string "C'est une défaite, mais…$"

MagmaHideout_2F_2R_Text_239EBB: @ 8239EBB
	.string "On a déterré quelque chose\n"
	.string "d'incroyable! Et on a l'ORBE BLEU!\p"
	.string "Notre leader n'a plus qu'à…\n"
	.string "Wahahah…$"

MagmaHideout_2F_2R_Text_239F31: @ 8239F31
	.string "Je ne supporte pas la chaleur…\n"
	.string "Je ferais peut-être mieux de rejoindre\l"
	.string "la TEAM AQUA…$"

MagmaHideout_2F_2R_Text_239F71: @ 8239F71
	.string "Oui, je ne suis vraiment pas fait pour\n"
	.string "être dans la TEAM MAGMA!$"

MagmaHideout_2F_2R_Text_239FA1: @ 8239FA1
	.string "La mer ne te manque pas dans un\n"
	.string "endroit comme ça?$"

MagmaHideout_2F_2R_Text_239FDE: @ 8239FDE
	.string "On entend quelquefois des grondements\n"
	.string "sourds par ici…\p"
	.string "Serait-ce le volcan? Ou bien serait-ce\n"
	.string "GROU…\p"
	.string "Oups!\n"
	.string "Oublie ce que je viens de dire!$"

MagmaHideout_2F_2R_Text_23A050: @ 823A050
	.string "Ça a été chaud!\n"
	.string "Presque aussi chaud qu'un volcan!$"

MagmaHideout_2F_2R_Text_23A07D: @ 823A07D
	.string "Tu as gagné contre moi, mais\n"
	.string "ça n'a pas vraiment d'importance.\p"
	.string "La TEAM MAGMA est sur le point de\n"
	.string "toucher son but!$"

MagmaHideout_2F_2R_Text_23A0E4: @ 823A0E4
	.string "Un de nos sbires est très inquiet\n"
	.string "d'avoir perdu le SCEAU MAGMA…\p"
	.string "Attends un peu!\n"
	.string "Ça ne serait pas toi qui… ?$"

MagmaHideout_2F_2R_Text_23A14C: @ 823A14C
	.string "J'peux pas le croire…$"

MagmaHideout_2F_2R_Text_23A16F: @ 823A16F
	.string "J'ai cette étrange impression que\n"
	.string "notre plan va échouer…$"

