LilycoveCity_ContestHall_MapScripts:: @ 821B484
	.byte 0

LilycoveCity_ContestHall_EventScript_21B485:: @ 821B485
	msgbox LilycoveCity_ContestHall_Text_21B74E, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B48E:: @ 821B48E
	msgbox LilycoveCity_ContestHall_Text_21B7D7, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B497:: @ 821B497
	msgbox LilycoveCity_ContestHall_Text_21B899, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B4A0:: @ 821B4A0
	msgbox LilycoveCity_ContestHall_Text_21B911, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B4A9:: @ 821B4A9
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21B977, MSGBOX_DEFAULT
	closemessage
	applymovement 4, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B4C0:: @ 821B4C0
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21B9DC, MSGBOX_DEFAULT
	closemessage
	applymovement 5, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B4D7:: @ 821B4D7
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BA44, MSGBOX_DEFAULT
	closemessage
	applymovement 6, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B4EE:: @ 821B4EE
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BAD5, MSGBOX_DEFAULT
	closemessage
	applymovement 7, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B505:: @ 821B505
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BB84, MSGBOX_DEFAULT
	closemessage
	applymovement 8, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B51C:: @ 821B51C
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BBDD, MSGBOX_DEFAULT
	closemessage
	applymovement 9, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B533:: @ 821B533
	msgbox LilycoveCity_ContestHall_Text_21BC65, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_EventScript_21B53C:: @ 821B53C
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BC89, MSGBOX_DEFAULT
	closemessage
	applymovement 12, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B553:: @ 821B553
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BD30, MSGBOX_DEFAULT
	closemessage
	applymovement 22, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B56A:: @ 821B56A
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BD70, MSGBOX_DEFAULT
	closemessage
	applymovement 11, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B581:: @ 821B581
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BDDD, MSGBOX_DEFAULT
	closemessage
	applymovement 13, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B598:: @ 821B598
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BE16, MSGBOX_DEFAULT
	closemessage
	applymovement 14, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5AF:: @ 821B5AF
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BE77, MSGBOX_DEFAULT
	closemessage
	applymovement 15, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5C6:: @ 821B5C6
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BEDE, MSGBOX_DEFAULT
	closemessage
	applymovement 16, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5DD:: @ 821B5DD
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BF6E, MSGBOX_DEFAULT
	closemessage
	applymovement 17, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5F4:: @ 821B5F4
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BFE3, MSGBOX_DEFAULT
	closemessage
	applymovement 18, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B60B:: @ 821B60B
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C07F, MSGBOX_DEFAULT
	closemessage
	applymovement 19, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B622:: @ 821B622
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C0D8, MSGBOX_DEFAULT
	closemessage
	applymovement 21, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B639:: @ 821B639
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C137, MSGBOX_DEFAULT
	closemessage
	applymovement 20, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B650:: @ 821B650
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C1A4, MSGBOX_DEFAULT
	closemessage
	applymovement 23, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B667:: @ 821B667
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C215, MSGBOX_DEFAULT
	closemessage
	applymovement 24, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B67E:: @ 821B67E
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C27F, MSGBOX_DEFAULT
	closemessage
	applymovement 25, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B695:: @ 821B695
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C2BB, MSGBOX_DEFAULT
	closemessage
	applymovement 26, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B6AC:: @ 821B6AC
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C307, MSGBOX_DEFAULT
	closemessage
	applymovement 27, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B6C3:: @ 821B6C3
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C365, MSGBOX_DEFAULT
	closemessage
	applymovement 28, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B6DA:: @ 821B6DA
	lockall
	applymovement 29, Common_Movement_FacePlayer
	waitmovement 0
	msgbox LilycoveCity_ContestHall_Text_21C3F4, MSGBOX_DEFAULT
	closemessage
	applymovement 29, Common_Movement_FaceOriginalDirection
	waitmovement 0
	delay 25
	msgbox LilycoveCity_ContestHall_Text_21C411, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestHall_EventScript_21B705:: @ 821B705
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C4B1, MSGBOX_DEFAULT
	closemessage
	applymovement 31, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B71C:: @ 821B71C
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C445, MSGBOX_DEFAULT
	closemessage
	applymovement 30, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B733:: @ 821B733
	msgbox LilycoveCity_ContestHall_Text_21C512, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_EventScript_21B73C:: @ 821B73C
	msgbox LilycoveCity_ContestHall_Text_21C548, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_EventScript_21B745:: @ 821B745
	msgbox LilycoveCity_ContestHall_Text_21C57B, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_Text_21B74E: @ 821B74E
	.string "Ce POKéMON a déjà gagné le CONCOURS\n"
	.string "DE BEAUTE ici.\p"
	.string "Et tu sais quoi? Je lui ai fait gagner le\n"
	.string "CONCOURS D'INTELLIGENCE, aujourd'hui!\p"
	.string "Je m'effraie moi-même…$"

LilycoveCity_ContestHall_Text_21B7D7: @ 821B7D7
	.string "J'ai fait pas mal de CONCOURS,\n"
	.string "donc je sais comment ça se passe.\p"
	.string "Dans un CONCOURS DE SANG-FROID, les\n"
	.string "capacités SANG-FROID ont du succès.\p"
	.string "Mais les capacités INTELLIGENCE et\n"
	.string "GRACE, par exemple, n'ont pas trop\l"
	.string "d'effet.$"

LilycoveCity_ContestHall_Text_21B899: @ 821B899
	.string "Le jeune garçon qui vient de gagner\n"
	.string "avait plein de {POKEBLOCK}S différents.\p"
	.string "Tu gagnerais, toi, si t'en avais autant?$"

LilycoveCity_ContestHall_Text_21B911: @ 821B911
	.string "Waouh, cet endroit est super!\p"
	.string "On peut sentir la tension dans l'air…\n"
	.string "Ça, c'est un vrai lieu de CONCOURS.$"

LilycoveCity_ContestHall_Text_21B977: @ 821B977
	.string "ANIMATRICE: POKéMON INTELLIGENTS\n"
	.string "et leurs DRESSEURS, vous êtes prêts?!\p"
	.string "Montrez-vous sous votre meilleur jour!\n"
	.string "C'est parti!$"

LilycoveCity_ContestHall_Text_21B9DC: @ 821B9DC
	.string "JUGE: Vous aimez ce genre de CONCOURS?\p"
	.string "Revenez avec trois amis et vous\n"
	.string "pourrez tous participer à un CONCOURS!$"

LilycoveCity_ContestHall_Text_21BA44: @ 821BA44
	.string "Aïe, aïe, aïe…\n"
	.string "Je me suis trompé de CONCOURS.\p"
	.string "J'ai inscrit ce POKéMON ROBUSTE à un\n"
	.string "CONCOURS D'INTELLIGENCE…\p"
	.string "Allez, montre-leur ton ECLATE-ROC.$"

LilycoveCity_ContestHall_Text_21BAD5: @ 821BAD5
	.string "Cela m'a pris des années et beaucoup\n"
	.string "de sagesse, pour que ce POKéMON\l"
	.string "devienne aussi intelligent.\p"
	.string "Il ne se laisse pas battre par n'importe\n"
	.string "quel POKéMON inexpérimenté.$"

LilycoveCity_ContestHall_Text_21BB84: @ 821BB84
	.string "Voilà!\p"
	.string "Une capacité INTELLIGENCE maintenant,\n"
	.string "et l'enthousiasme du public augmentera!$"

LilycoveCity_ContestHall_Text_21BBDD: @ 821BBDD
	.string "Oh, non!\p"
	.string "J'utilise tout le temps le VAMPIRISME\n"
	.string "de mon NOSFERAPTI, il est si gracieux!\p"
	.string "Mais ces gens sont méchants et\n"
	.string "n'apprécient pas du tout!$"

LilycoveCity_ContestHall_Text_21BC65: @ 821BC65
	.string "Ouais! T'es super, pépé!$"

LilycoveCity_ContestHall_Text_21BC89: @ 821BC89
	.string "Même quand les DRESSEURS inscrivent\n"
	.string "le même genre de POKéMON, ils semblent\l"
	.string "utiliser des capacités différentes.\p"
	.string "C'est comme pour les combats, chacun\n"
	.string "a son propre style.$"

LilycoveCity_ContestHall_Text_21BD30: @ 821BD30
	.string "Je trouve que les POKéMON ont l'air bien\n"
	.string "plus intelligents que leurs DRESSEURS.$"

LilycoveCity_ContestHall_Text_21BD70: @ 821BD70
	.string "Par-dessus tout, j'adore les\n"
	.string "CONCOURS D'INTELLIGENCE.\p"
	.string "Cette couleur verte si intellectuelle…\n"
	.string "C'est… super cool.$"

LilycoveCity_ContestHall_Text_21BDDD: @ 821BDDD
	.string "ANIMATRICE: Tu vas aussi participer au\n"
	.string "CONCOURS DE BEAUTE? Bonne chance!$"

LilycoveCity_ContestHall_Text_21BE16: @ 821BE16
	.string "JUGE: Ah, les POKéMON ici présents\n"
	.string "sont des spécimens d'une rare beauté!\p"
	.string "Oh, j'en ai presque oublié de les noter!$"

LilycoveCity_ContestHall_Text_21BE77: @ 821BE77
	.string "Un POKéMON de cette magnificence…\n"
	.string "Il n'y en a pas deux comme ça.\p"
	.string "Tout le monde sera subjugué par tant\n"
	.string "de beauté.$"

LilycoveCity_ContestHall_Text_21BEDE: @ 821BEDE
	.string "Ahhhhh!\p"
	.string "J'ai brossé et coiffé mon POKéMON\n"
	.string "avec soin pour ce CONCOURS…\p"
	.string "Mais j'ai exagéré…\n"
	.string "Maintenant, il a le poil tout ébouriffé…\p"
	.string "Qu'est-ce que je peux faire?$"

LilycoveCity_ContestHall_Text_21BF6E: @ 821BF6E
	.string "Cette ONDE BOREALE est si éblouissante\n"
	.string "que le JUGE ne pourra pas la voir.\p"
	.string "Euh, attends…\n"
	.string "Mais ça sert à rien, alors!$"

LilycoveCity_ContestHall_Text_21BFE3: @ 821BFE3
	.string "Ce joli POKéMON, c'est exactement moi\n"
	.string "quand j'étais plus jeune.\p"
	.string "Juste au moment où je l'ai dit, mon mari\n"
	.string "s'est étouffé avec son café.\p"
	.string "J'ai dit quelque chose d'amusant?$"

LilycoveCity_ContestHall_Text_21C07F: @ 821C07F
	.string "Tu sais, en tant que femme, je serais\n"
	.string "plus qu'heureuse de gagner un CONCOURS\l"
	.string "DE BEAUTE.$"

LilycoveCity_ContestHall_Text_21C0D8: @ 821C0D8
	.string "Waouhhhh!\p"
	.string "Tu devrais jeter un coup d'œil\n"
	.string "à ces jolis POKéMON.\l"
	.string "Quelle splendeur! J'adore!$"

LilycoveCity_ContestHall_Text_21C137: @ 821C137
	.string "Tu ne peux pas toujours compter\n"
	.string "sur la beauté uniquement.\p"
	.string "Tu dois aussi coiffer ton POKéMON, pour\n"
	.string "qu'il soit aussi brillant que le mien.$"

LilycoveCity_ContestHall_Text_21C1A4: @ 821C1A4
	.string "ANIMATRICE: Hum! Ohé!\n"
	.string "On est en plein CONCOURS!\p"
	.string "Veuillez vous inscrire au guichet et\n"
	.string "revenez ensuite, vous voulez bien?$"

LilycoveCity_ContestHall_Text_21C215: @ 821C215
	.string "JUGE: Oh, quelles démonstrations\n"
	.string "ravissantes et gracieuses!\p"
	.string "Juste ciel! Quelle parfaite et adorable\n"
	.string "démonstration de TOURNIQUET!$"

LilycoveCity_ContestHall_Text_21C27F: @ 821C27F
	.string "Oh, non… Mon doux AZURILL s'est\n"
	.string "laissé distraire par un autre POKéMON.$"

LilycoveCity_ContestHall_Text_21C2BB: @ 821C2BB
	.string "Mon POKéMON ne gagne jamais de combat,\n"
	.string "mais en CONCOURS, c'est le meilleur!$"

LilycoveCity_ContestHall_Text_21C307: @ 821C307
	.string "La DANSE-FLEUR de mon POKéMON est une\n"
	.string "merveille d'élégance.\p"
	.string "Je ne laisserai personne perturber sa\n"
	.string "prestation.$"

LilycoveCity_ContestHall_Text_21C365: @ 821C365
	.string "Tous les POKéMON sont gracieux.\p"
	.string "Mais si mon POKéMON faisait une\n"
	.string "démonstration de grâce…\p"
	.string "Je suis sûre qu'il serait beaucoup plus\n"
	.string "gracieux que les autres.$"

LilycoveCity_ContestHall_Text_21C3F4: @ 821C3F4
	.string "Mon enfant participe au CONCOURS.$"

LilycoveCity_ContestHall_Text_21C411: @ 821C411
	.string "Vas-y, courage!\n"
	.string "Ton POKéMON est le meilleur!$"

LilycoveCity_ContestHall_Text_21C445: @ 821C445
	.string "Je trouve que cette fille est vraiment\n"
	.string "la plus gracieuse.\p"
	.string "Comment? Ils jugent les POKéMON\n"
	.string "sur leur apparence?$"

LilycoveCity_ContestHall_Text_21C4B1: @ 821C4B1
	.string "Oh, regarder tous ces gracieux POKéMON\n"
	.string "me donne envie d'en avoir un!\p"
	.string "Je vais aller en attraper quelques-uns!$"

LilycoveCity_ContestHall_Text_21C512: @ 821C512
	.string "EPREUVE DE BEAUTE\n"
	.string "POKéMON D'UNE BEAUTE EPOUSTOUFLANTE!$"

LilycoveCity_ContestHall_Text_21C548: @ 821C548
	.string "EPREUVE DE GRACE\n"
	.string "POKéMON D'UNE GRACE EXTREME!$"

LilycoveCity_ContestHall_Text_21C57B: @ 821C57B
	.string "EPREUVE D'INTELLIGENCE\n"
	.string "POKéMON D'UNE INTELLIGENCE INOUIE!$"

