RustboroCity_House2_MapScripts:: @ 8215EB3
	.byte 0

RustboroCity_House2_EventScript_215EB4:: @ 8215EB4
	msgbox RustboroCity_House2_Text_215EC6, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_215EBD:: @ 8215EBD
	msgbox RustboroCity_House2_Text_215F21, MSGBOX_NPC
	end

RustboroCity_House2_Text_215EC6: @ 8215EC6
	.string "L'ECOLE DE DRESSEURS est excellente.\p"
	.string "En y étudiant, tu pourrais même devenir\n"
	.string "CHAMPION D'ARENE.$"

RustboroCity_House2_Text_215F21: @ 8215F21
	.string "ROXANNE, notre CHAMPION, en sait\n"
	.string "vraiment beaucoup sur les POKéMON.\p"
	.string "Elle est également très forte!$"

