RustboroCity_Flat2_3F_MapScripts:: @ 8216116
	.byte 0

RustboroCity_Flat2_3F_EventScript_216117:: @ 8216117
	msgbox RustboroCity_Flat2_3F_Text_216129, MSGBOX_NPC
	end

RustboroCity_Flat2_3F_EventScript_216120:: @ 8216120
	msgbox RustboroCity_Flat2_3F_Text_216159, MSGBOX_NPC
	end

RustboroCity_Flat2_3F_Text_216129: @ 8216129
	.string "Le DIRECTEUR de DEVON collectionne\n"
	.string "les pierres rares.$"

RustboroCity_Flat2_3F_Text_216159: @ 8216159
	.string "Je crois que le fils du DIRECTEUR\n"
	.string "collectionne aussi les pierres rares.$"

