OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
	.string "Quand un combat de POKéMON commence,\n"
	.string "celui qui est à gauche de la liste part\l"
	.string "au combat le premier.\p"
	.string "Donc, quand tu auras plus de POKéMON\n"
	.string "dans ton équipe, tu pourras modifier\l"
	.string "l'ordre des POKéMON.\p"
	.string "Ça pourrait te donner l'avantage.$"

