LilycoveCity_House4_MapScripts:: @ 821F5B4
	.byte 0

LilycoveCity_House4_EventScript_21F5B5:: @ 821F5B5
	msgbox LilycoveCity_House4_Text_21F5C7, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_21F5BE:: @ 821F5BE
	msgbox LilycoveCity_House4_Text_21F62B, MSGBOX_NPC
	end

LilycoveCity_House4_Text_21F5C7: @ 821F5C7
	.string "Les plus grands mystères de cette\n"
	.string "planète se trouvent au fond de l'océan.\p"
	.string "Quelqu'un a dit ça, mais j'sais plus qui…$"

LilycoveCity_House4_Text_21F62B: @ 821F62B
	.string "Il y a un abîme tout au fond de l'eau,\n"
	.string "entre ALGATIA et ATALANOPOLIS.\p"
	.string "En tout cas, c'est ce qu'on m'a dit.$"