@ The scripts there concern pokeblock events in LilyCove City's Contest Lobby 

@ 'PblockX' number of offline opponents
@ 'Ask' talking with a blender machine
@ 'Yes' agreeing to blend
@ 'No' refusing to blend
@ 'KnowHow' asking if the player knows the blending process
@ 'Explain' explaining the blender process
@ 'Start' start blending
@ 'TalkX' talking with a person next to a blender machine
@ 'NoBerries' can't blend cause they have no berries
@ 'FullPokeblock' can't blend cause full pokeblock case
@ 'NoPokeblock' can't blend cause they have no pokeblock case

Text_Pblock1_Ask: @ 8292DEE
	.string "Oh? Tu veux créer des {POKEBLOCK}S\n"
	.string "avec un ancêtre comme moi?$"

Text_Pblock1_Yes: @ 8292E28
	.string "Excellent!$"

Text_Pblock1_No: @ 8292E33
	.string "Oh… Je suis l'ancêtre le plus\n"
	.string "triste du monde…$"

Text_Pblock1_KnowHow: @ 8292E57
	.string "Tu sais comment créer un {POKEBLOCK}?$"

Text_Pblock1_Start: @ 8292E78
	.string "Dans ce cas, allons-y!\p"
	.string "C'est parti pour le MIXEUR!$"

Text_Pblock1_Explain: @ 8292EA6
	.string "Dans ce cas, je vais t'expliquer.\p"
	.string "Ne t'inquiète pas, c'est simple comme\n"
	.string "bonjour.\p"
	.string "Lorsque la flèche du MIXEUR passe\n"
	.string "devant ton marqueur, appuie simplement\l"
	.string "sur le bouton A.\p"
	.string "Voilà, c'est tout.\n"
	.string "Essaie, tu verras, c'est enfantin.$"

Text_Pblock1_NoBerries: @ 8292F77
	.string "Oh?\n"
	.string "Tu n'as pas de BAIE?\p"
	.string "Sans BAIE, il est impossible de créer\n"
	.string "des {POKEBLOCK}S.$"

LilycoveCity_ContestLobby_Text_292FD1: @ 8292FD1
	.string "Bon, ça ne va pas du tout, n'est-ce pas?\p"
	.string "Si ça ne te gêne pas de prendre mes\n"
	.string "restes, je peux te donner une BAIE.\p"
	.string "Comme ça, on peut créer des {POKEBLOCK}S\n"
	.string "avec le MIXEUR.$"

LilycoveCity_ContestLobby_Text_29307D: @ 829307D
	.string "S'il me restait des BAIES, je t'en\n"
	.string "donnerais volontiers une…\p"
	.string "Mais, aujourd'hui, je n'ai plus de BAIE\n"
	.string "à partager. Ce sera pour une autre fois.$"

Text_Pblock1_FullPokeblock: @ 8293101
	.string "Mais ta BOITE {POKEBLOCK}S est pleine.\p"
	.string "Tu devrais utiliser des {POKEBLOCK}S et\n"
	.string "revenir me voir.$"

Text_Pblock1_NoPokeblock: @ 8293157
	.string "Mais tu n'as pas de BOITE {POKEBLOCK}S.\p"
	.string "Trouve une BOITE {POKEBLOCK}S et\n"
	.string "reviens me voir.$"

LilycoveCity_ContestLobby_Text_2931AA: @ 82931AA
	.string "C'est parti pour le mélange!$"

LilycoveCity_ContestLobby_Text_2931C6: @ 82931C6
	.string "Je me demande quel type de {POKEBLOCK} je\n"
	.string "vais créer! C'est palpitant!$"

LilycoveCity_ContestLobby_Text_293201: @ 8293201
	.string "Salut toi!\n"
	.string "Tu veux créer des {POKEBLOCK}S?$"

LilycoveCity_ContestLobby_Text_293237: @ 8293237
	.string "Excellent!$"

LilycoveCity_ContestLobby_Text_29323D: @ 829323D
	.string "Quel dommage…\p"
	.string "Dès que tu as une petite envie de mixer,\n"
	.string "viens par ici!$"

LilycoveCity_ContestLobby_Text_29328C: @ 829328C
	.string "Tu sais comment créer un {POKEBLOCK}, non?$"

LilycoveCity_ContestLobby_Text_2932C3: @ 82932C3
	.string "Dans ce cas, allons-y!\p"
	.string "C'est parti pour le MIXEUR!$"

LilycoveCity_ContestLobby_Text_2932F1: @ 82932F1
	.string "Dans ce cas, je vais t'expliquer.\p"
	.string "Lorsque la flèche du MIXEUR passe\n"
	.string "devant ton marqueur, appuie simplement\l"
	.string "sur le bouton A.\p"
	.string "Voilà, c'est tout.\n"
	.string "C'est trop facile, tu verras!$"

LilycoveCity_ContestLobby_Text_293394: @ 8293394
	.string "Oh?\n"
	.string "Tu n'as pas de BAIE?\p"
	.string "Sans BAIE, il est impossible de créer\n"
	.string "des {POKEBLOCK}S.\p"
	.string "Repasse quand tu auras quelques BAIES\n"
	.string "à mixer.$"

LilycoveCity_ContestLobby_Text_29343E: @ 829343E
	.string "Mais ta BOITE {POKEBLOCK}S est pleine.\p"
	.string "Tu devrais utiliser des {POKEBLOCK}S et\n"
	.string "repasser.$"

LilycoveCity_ContestLobby_Text_2934A2: @ 82934A2
	.string "Mais tu n'as pas de BOITE {POKEBLOCK}S.\p"
	.string "Trouve une BOITE {POKEBLOCK}S et\n"
	.string "repasse nous voir.$"

LilycoveCity_ContestLobby_Text_29350B: @ 829350B
	.string "Oh, hello! Did you want to make some\n"
	.string "{POKEBLOCK}S with our little group?$"

LilycoveCity_ContestLobby_Text_29354E: @ 829354E
	.string "Oh!$"

LilycoveCity_ContestLobby_Text_293558: @ 8293558
	.string "Oh…\p"
	.string "Nous sommes en état de choc.$"

LilycoveCity_ContestLobby_Text_29357E: @ 829357E
	.string "Bien sûr, tu dois savoir comment créer\n"
	.string "un {POKEBLOCK}. N'est-ce pas que tu sais?$"

LilycoveCity_ContestLobby_Text_2935B1: @ 82935B1
	.string "Dans ce cas, allons-y!\p"
	.string "C'est parti pour le MIXEUR!$"

LilycoveCity_ContestLobby_Text_2935E5: @ 82935E5
	.string "Pas possible!\p"
	.string "Dans ce cas, je vais t'expliquer.\p"
	.string "Lorsque la flèche du MIXEUR passe\n"
	.string "devant ton marqueur, appuie simplement\l"
	.string "sur le bouton A.\p"
	.string "Voilà, c'est tout.\n"
	.string "C'est trop facile, tu verras!$"

LilycoveCity_ContestLobby_Text_29367D: @ 829367D
	.string "Oh?\n"
	.string "Tu n'as pas de BAIE?\p"
	.string "Sans BAIE, il est impossible de créer\n"
	.string "des {POKEBLOCK}S.\p"
	.string "Je reste ici pour faire des {POKEBLOCK}S.\n"
	.string "Reviens dès que tu auras quelques\l"
	.string "BAIES!$"

LilycoveCity_ContestLobby_Text_293738: @ 8293738
	.string "Mais ta BOITE {POKEBLOCK}S est pleine.\p"
	.string "Tu devrais utiliser des {POKEBLOCK}S et\n"
	.string "repasser.$"

LilycoveCity_ContestLobby_Text_293792: @ 8293792
	.string "Mais tu n'as pas de BOITE {POKEBLOCK}S.\p"
	.string "Trouve une BOITE {POKEBLOCK}S et\n"
	.string "repasse.$"

LilycoveCity_ContestLobby_Text_2937F9: @ 82937F9
	.string "Aujourd'hui, je vais battre le record\n"
	.string "de vitesse du MIXEUR!$"

LilycoveCity_ContestLobby_Text_293842: @ 8293842
	.string "Dis, toi!\n"
	.string "Je suis sûre que tu sais bien mixer!\l"
	.string "Tu veux te joindre à nous?$"

LilycoveCity_ContestLobby_Text_29388F: @ 829388F
	.string "Je vais faire de délicieux {POKEBLOCK}S\n"
	.string "pour rendre mes POKéMON plus gracieux.$"

Text_PblockLink_Ask: @ 82938CD
	.string "Il va être possible de créer des\n"
	.string "{POKEBLOCK}S entre amis en utilisant\l"
	.string "des BAIES avec le MIXEUR.\p"
	.string "Voulez-vous sauvegarder la partie\n"
	.string "avant de vous connecter avec vos amis?$"

Text_PblockLink_Searching: @ 8293955
	.string "Recherche d'amis…\n"
	.string "… … Bouton B: Annuler$"

Text_PblockLink_1Arrived: @ 8293986
	.string "{STR_VAR_1} arrive.$"

Text_PblockLink_2Arrived: @ 8293992
	.string "{STR_VAR_1} et {STR_VAR_2} arrivent.$"

Text_PblockLink_3Arrived: @ 82939A5
	.string "{STR_VAR_1}, {STR_VAR_2} et\n"
	.string "{STR_VAR_3} arrivent.$"

Text_PblockLink_NoBerries: @ 82939BD
	.string "Vous n'avez pas de BAIES.\n"
	.string "Impossible d'utiliser le MIXEUR.$"

Text_PblockLink_FullPokeblock: @ 82939F3
	.string "Votre BOITE {POKEBLOCK}S est pleine.\n"
	.string "Impossible d'utiliser le MIXEUR.$"

Text_PblockLink_NoPokeblock: @ 8293A2D
	.string "Vous n'avez pas de BOITE {POKEBLOCK}S.\n"
	.string "Impossible d'utiliser le MIXEUR.$"

Text_Pblock1_Talk_0: @ 8293A6B
	.string "J'aime bien faire des {POKEBLOCK}S.\p"
	.string "J'ai toujours quelques BAIES sur moi.$"

Text_Pblock1_Talk_1: @ 8293AA5
	.string "Si ça te dit, on peut faire quelques\n"
	.string "{POKEBLOCK}S ensemble à l'aide du MIXEUR.$"

LilycoveCity_ContestLobby_Text_293AF0: @ 8293AF0
	.string "Oh?\n"
	.string "Tu n'as pas de BAIES?\p"
	.string "Bon, ça n'fait rien pour l'instant, hein?\p"
	.string "Si tu t'en fiches d'avoir les restes,\n"
	.string "tu peux prendre une de mes BAIES.$"

LilycoveCity_ContestLobby_Text_293B76: @ 8293B76
	.string "On va s'en servir pour faire des {POKEBLOCK}S\n"
	.string "ensemble avec le MIXEUR.$"

LilycoveCity_ContestLobby_Text_293BB4: @ 8293BB4
	.string "Oh?\n"
	.string "Tu n'as pas de BAIES?\p"
	.string "S'il m'en restait, je t'en donnerais\n"
	.string "une avec grand plaisir…\p"
	.string "Mais je n'en ai aucune en réserve\n"
	.string "aujourd'hui. Désolé.$"

EventScript_Pblock1_Ask:: @ 8293C3E
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER_ONLOOKERS, LilycoveCity_ContestLobby_EventScript_293EFB
	setvar VAR_0x8009, 1
	applymovement 16, LilycoveCity_ContestLobby_Movement_294053
	waitmovement 0
	msgbox Text_Pblock1_Ask, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq EventScript_Pblock1_Yes
	goto EventScript_Pblock1_No
	end

EventScript_Pblock1_No: @ 8293C70
	msgbox Text_Pblock1_No, MSGBOX_DEFAULT
	releaseall
	end

EventScript_Pblock1_NoBerries: @ 8293C7A
	msgbox Text_Pblock1_NoBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, LilycoveCity_ContestLobby_EventScript_293C92
	goto LilycoveCity_ContestLobby_EventScript_293C9C
	end

LilycoveCity_ContestLobby_EventScript_293C92: @ 8293C92
	msgbox LilycoveCity_ContestLobby_Text_29307D, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293C9C: @ 8293C9C
	msgbox LilycoveCity_ContestLobby_Text_292FD1, MSGBOX_DEFAULT
	giveitem_std ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto EventScript_Pblock1_KnowHow
	end

EventScript_Pblock1_KnowHow: @ 8293CB9
	msgbox Text_Pblock1_KnowHow, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq EventScript_Pblock1_Start
	goto EventScript_Pblock1_Explain
	end

EventScript_Pblock1_Start: @ 8293CD2
	msgbox Text_Pblock1_Start, MSGBOX_DEFAULT
	goto EventScript_StartBlending
	end

EventScript_Pblock1_Explain: @ 8293CE0
	msgbox Text_Pblock1_Explain, MSGBOX_DEFAULT
	goto EventScript_Pblock1_Start
	end

EventScript_Pblock1_Yes: @ 8293CEE
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_if_eq EventScript_Pblock1_NoPokeblock
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_eq EventScript_Pblock1_FullPokeblock
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_if_eq EventScript_Pblock1_NoBerries
	msgbox Text_Pblock1_Yes, MSGBOX_DEFAULT
	goto EventScript_Pblock1_KnowHow
	end

EventScript_StartBlending: @ 8293D2C
	copyvar VAR_0x8004, VAR_0x8009
	fadescreen 1
	special DoBerryBlending
	waitstate
	releaseall
	end

EventScript_Pblock1_FullPokeblock: @ 8293D39
	msgbox Text_Pblock1_FullPokeblock, MSGBOX_DEFAULT
	releaseall
	end

EventScript_Pblock1_NoPokeblock: @ 8293D43
	msgbox Text_Pblock1_NoPokeblock, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293D4D:: @ 8293D4D
	lockall
	setvar VAR_0x8009, 2
	applymovement 10, Common_Movement_FaceOriginalDirection
	applymovement 3, LilycoveCity_ContestLobby_Movement_294053
	waitmovement 0
	msgbox LilycoveCity_ContestLobby_Text_293201, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293DC6
	goto LilycoveCity_ContestLobby_EventScript_293D7D
	end

LilycoveCity_ContestLobby_EventScript_293D7D: @ 8293D7D
	msgbox LilycoveCity_ContestLobby_Text_29323D, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293D87: @ 8293D87
	msgbox LilycoveCity_ContestLobby_Text_293394, MSGBOX_DEFAULT
	release
	end

LilycoveCity_ContestLobby_EventScript_293D91: @ 8293D91
	msgbox LilycoveCity_ContestLobby_Text_29328C, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293DAA
	goto LilycoveCity_ContestLobby_EventScript_293DB8
	end

LilycoveCity_ContestLobby_EventScript_293DAA: @ 8293DAA
	msgbox LilycoveCity_ContestLobby_Text_2932C3, MSGBOX_DEFAULT
	goto EventScript_StartBlending
	end

LilycoveCity_ContestLobby_EventScript_293DB8: @ 8293DB8
	msgbox LilycoveCity_ContestLobby_Text_2932F1, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_293DAA
	end

LilycoveCity_ContestLobby_EventScript_293DC6: @ 8293DC6
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293D87
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293E14
	msgbox LilycoveCity_ContestLobby_Text_293237, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne LilycoveCity_ContestLobby_EventScript_293D91
	compare VAR_RESULT, 65535
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293E0A
	end

LilycoveCity_ContestLobby_EventScript_293E0A: @ 8293E0A
	msgbox LilycoveCity_ContestLobby_Text_29343E, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293E14: @ 8293E14
	msgbox LilycoveCity_ContestLobby_Text_2934A2, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293E1E:: @ 8293E1E
	lockall
	setvar VAR_0x8008, 15
	setvar VAR_0x8009, 3
	applymovement 9, Common_Movement_FaceOriginalDirection
	applymovement 17, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, LilycoveCity_ContestLobby_Movement_294053
	waitmovement 0
	msgbox LilycoveCity_ContestLobby_Text_293842, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293EA3
	goto LilycoveCity_ContestLobby_EventScript_293E5A
	end

LilycoveCity_ContestLobby_EventScript_293E5A: @ 8293E5A
	msgbox LilycoveCity_ContestLobby_Text_293558, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293E64: @ 8293E64
	msgbox LilycoveCity_ContestLobby_Text_29367D, MSGBOX_DEFAULT
	release
	end

LilycoveCity_ContestLobby_EventScript_293E6E: @ 8293E6E
	msgbox LilycoveCity_ContestLobby_Text_29357E, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293E87
	goto LilycoveCity_ContestLobby_EventScript_293E95
	end

LilycoveCity_ContestLobby_EventScript_293E87: @ 8293E87
	msgbox LilycoveCity_ContestLobby_Text_2935B1, MSGBOX_DEFAULT
	goto EventScript_StartBlending
	end

LilycoveCity_ContestLobby_EventScript_293E95: @ 8293E95
	msgbox LilycoveCity_ContestLobby_Text_2935E5, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_293E87
	end

LilycoveCity_ContestLobby_EventScript_293EA3: @ 8293EA3
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293E64
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293EF1
	msgbox LilycoveCity_ContestLobby_Text_29354E, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne LilycoveCity_ContestLobby_EventScript_293E6E
	compare VAR_RESULT, 65535
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293EE7
	end

LilycoveCity_ContestLobby_EventScript_293EE7: @ 8293EE7
	msgbox LilycoveCity_ContestLobby_Text_293738, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293EF1: @ 8293EF1
	msgbox LilycoveCity_ContestLobby_Text_293792, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293EFB: @ 8293EFB
	lockall
	setvar VAR_0x8009, 1
	msgbox LilycoveCity_ContestLobby_Text_2C42F4, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293F28
	msgbox LilycoveCity_ContestLobby_Text_2C4332, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293F1E: @ 8293F1E
	msgbox LilycoveCity_ContestLobby_Text_2C439D, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293F28: @ 8293F28
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293F8E
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293F1E
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne LilycoveCity_ContestLobby_EventScript_293F64
	compare VAR_RESULT, 65535
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293F98
	end

LilycoveCity_ContestLobby_EventScript_293F64: @ 8293F64
	msgbox LilycoveCity_ContestLobby_Text_2C43FA, MSGBOX_YESNO
	compare VAR_RESULT, 0
	call_if_eq LilycoveCity_ContestLobby_EventScript_293F85
	msgbox LilycoveCity_ContestLobby_Text_2C451B, MSGBOX_DEFAULT
	goto EventScript_StartBlending
	end

LilycoveCity_ContestLobby_EventScript_293F85: @ 8293F85
	msgbox LilycoveCity_ContestLobby_Text_2C444C, MSGBOX_DEFAULT
	return

LilycoveCity_ContestLobby_EventScript_293F8E: @ 8293F8E
	msgbox LilycoveCity_ContestLobby_Text_2C4573, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293F98: @ 8293F98
	msgbox LilycoveCity_ContestLobby_Text_2C45E8, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293FA2:: @ 8293FA2
	msgbox LilycoveCity_ContestLobby_Text_2937F9, MSGBOX_NPC
	end

LilycoveCity_ContestLobby_EventScript_293FAB:: @ 8293FAB
	msgbox LilycoveCity_ContestLobby_Text_293842, MSGBOX_NPC
	end

LilycoveCity_ContestLobby_EventScript_293FB4:: @ 8293FB4
	msgbox LilycoveCity_ContestLobby_Text_29388F, MSGBOX_NPC
	end

LilycoveCity_ContestLobby_EventScript_293FBD:: @ 8293FBD
	setvar VAR_0x8008, 15
	goto LilycoveCity_ContestLobby_EventScript_293FC8
	end

LilycoveCity_ContestLobby_EventScript_293FC8: @ 8293FC8
	lock
	faceplayer
	msgbox Text_Pblock1_Talk_0, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293FEE
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_293FF8
	end

LilycoveCity_ContestLobby_EventScript_293FEE: @ 8293FEE
	msgbox Text_Pblock1_Talk_1, MSGBOX_DEFAULT
	release
	end

LilycoveCity_ContestLobby_EventScript_293FF8: @ 8293FF8
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_if_eq LilycoveCity_ContestLobby_EventScript_294028
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_eq LilycoveCity_ContestLobby_EventScript_294028
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, LilycoveCity_ContestLobby_EventScript_294028
	goto LilycoveCity_ContestLobby_EventScript_294032
	end

LilycoveCity_ContestLobby_EventScript_294028: @ 8294028
	msgbox LilycoveCity_ContestLobby_Text_293BB4, MSGBOX_DEFAULT
	release
	end

LilycoveCity_ContestLobby_EventScript_294032: @ 8294032
	msgbox LilycoveCity_ContestLobby_Text_293AF0, MSGBOX_DEFAULT
	giveitem_std ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox LilycoveCity_ContestLobby_Text_293B76, MSGBOX_DEFAULT
	release
	end

LilycoveCity_ContestLobby_Movement_294053: @ 8294053
	walk_in_place_fastest_right
	step_end

EventScript_PblockLink:: @ 8294055
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_if_eq EventScript_PblocLink_NoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_if_eq EventScript_PblocLink_NoPokeblock
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne EventScript_PblocLink_Ask
	compare VAR_RESULT, 65535
	goto_if_eq EventScript_PblocLink_FullPokeblock
	end

EventScript_PblocLink_Ask: @ 8294092
	msgbox Text_PblockLink_Ask, MSGBOX_YESNO
	compare VAR_RESULT, 1
	goto_if_eq EventScript_PblocLink_TryConnect
	compare VAR_RESULT, 0
	goto_if_eq EventScript_PblocLink_End
	end

EventScript_PblocLink_NoBerries: @ 82940B1
	msgbox Text_PblockLink_NoBerries, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_TryConnect: @ 82940BB
	call Common_EventScript_SaveGame
	compare VAR_RESULT, 0
	goto_if_eq EventScript_PblocLink_End
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	compare VAR_RESULT, 1
	goto_if_eq LilycoveCity_ContestLobby_EventScript_2941ED
	message Text_PblockLink_Searching
	waitmessage
	special sub_80B2FD8
	waitstate
	compare VAR_RESULT, 1
	goto_if_eq EventScript_PblocLink_SpawnPartners
	compare VAR_RESULT, 2
	goto_if_eq EventScript_PblocLink_SomeoneNotReady
	compare VAR_RESULT, 3
	goto_if_eq EventScript_PblocLink_DifferentSelections
	compare VAR_RESULT, 5
	goto_if_eq EventScript_PblocLink_CloseLink
	compare VAR_RESULT, 6
	goto_if_eq EventScript_PblocLink_LinkError
	end

EventScript_PblocLink_1Arrived: @ 829411D
	msgbox Text_PblockLink_1Arrived, MSGBOX_DEFAULT
	goto EventScript_PblocLink_StartLinkBlending
	end

EventScript_PblocLink_2Arrived: @ 829412B
	msgbox Text_PblockLink_2Arrived, MSGBOX_DEFAULT
	goto EventScript_PblocLink_StartLinkBlending
	end

EventScript_PblocLink_3Arrived: @ 8294139
	msgbox Text_PblockLink_3Arrived, MSGBOX_DEFAULT
	goto EventScript_PblocLink_StartLinkBlending
	end

EventScript_PblocLink_StartLinkBlending: @ 8294147
	setvar VAR_0x8004, 0
	fadescreen 1
	removeobject 240
	removeobject 239
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

EventScript_PblocLink_End: @ 8294160
	releaseall
	end

EventScript_PblocLink_FullPokeblock: @ 8294162
	msgbox Text_PblockLink_FullPokeblock, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_NoPokeblock: @ 829416C
	msgbox Text_PblockLink_NoPokeblock, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_SomeoneNotReady: @ 8294176
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_DifferentSelections: @ 8294183
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_CloseLink: @ 8294190
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_LinkError: @ 829419D
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

EventScript_PblocLink_SpawnPartners: @ 82941AA
	fadescreen 1
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerEventObject
	goto EventScript_PblocLink_Arrived
	end

EventScript_PblocLink_Arrived: @ 82941C4
	fadescreen 0
	switch VAR_0x8008
	case 2, EventScript_PblocLink_1Arrived
	case 3, EventScript_PblocLink_2Arrived
	case 4, EventScript_PblocLink_3Arrived
	end

LilycoveCity_ContestLobby_EventScript_2941ED: @ 82941ED
	setvar VAR_0x8004, 13
	goto EventScript_PblocLink_DecideLeader
	end

EventScript_PblocLink_DecideLeader: @ 82941F8
	message Text_DecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, 0
	switch VAR_RESULT
	case 0, EventScript_PblocLink_TryJoinGroup
	case 1, EventScript_PblocLink_TryBecomeLeader
	case 2, EventScript_PblocLink_CloseLink
	case MULTI_B_PRESSED, EventScript_PblocLink_CloseLink
	end

EventScript_PblocLink_TryBecomeLeader: @ 8294235
	call EventScript_PblocLink_BecomeLeader
	compare VAR_RESULT, 1
	goto_if_eq EventScript_PblocLink_SpawnPartners_
	compare VAR_RESULT, 5
	goto_if_eq EventScript_PblocLink_DecideLeader
	compare VAR_RESULT, 8
	goto_if_eq EventScript_PblocLink_TryBecomeLeader
	release
	end

EventScript_PblocLink_TryJoinGroup: @ 829425D
	call EventScript_PblocLink_JoinGroup
	compare VAR_RESULT, 1
	goto_if_eq EventScript_PblocLink_SpawnPartners_
	compare VAR_RESULT, 5
	goto_if_eq EventScript_PblocLink_DecideLeader
	compare VAR_RESULT, 8
	goto_if_eq EventScript_PblocLink_TryJoinGroup
	release
	end

EventScript_PblocLink_BecomeLeader: @ 8294285
	special TryBecomeLinkLeader
	waitstate
	return

EventScript_PblocLink_JoinGroup: @ 829428A
	special TryJoinLinkGroup
	waitstate
	return

EventScript_PblocLink_SpawnPartners_: @ 829428F
	goto EventScript_PblocLink_SpawnPartners
	end
