AbandonedShip_Rooms2_B1F_MapScripts:: @ 8238024
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_238025:: @ 8238025
	msgbox AbandonedShip_Rooms2_B1F_Text_23802E, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_23802E: @ 823802E
	.string "C'est l'endroit idéal pour une petite\n"
	.string "exploration! C'est passionnant ici!\p"
	.string "Je parie qu'il y a de stupéfiants\n"
	.string "trésors à bord.$"

