MtPyre_5F_MapScripts:: @ 8231C6D
	.byte 0

MtPyre_4F_EventScript_231C6E:: @ 8231C6E
	trainerbattle_single TRAINER_TASHA, MtPyre_4F_Text_231C85, MtPyre_4F_Text_231CDB
	msgbox MtPyre_4F_Text_231CEE, MSGBOX_AUTOCLOSE
	end

MtPyre_4F_Text_231C85: @ 8231C85
	.string "J'aime tout ce qui fait peur…\n"
	.string "C'est comme une maladie…\p"
	.string "Quand je suis ici…\n"
	.string "Je tremble de peur…$"

MtPyre_4F_Text_231CDB: @ 8231CDB
	.string "Perdre, je déteste ça…$"

MtPyre_4F_Text_231CEE: @ 8231CEE
	.string "Je veux voir des choses atroces…\n"
	.string "Je ne peux pas partir…\p"
	.string "Reste…\n"
	.string "Tu ne vas pas rester avec moi?$"

