SlateportCity_House2_MapScripts:: @ 820D9AE
	.byte 0

SlateportCity_House2_EventScript_20D9AF:: @ 820D9AF
	msgbox SlateportCity_House2_Text_20D9C1, MSGBOX_NPC
	end

SlateportCity_House2_EventScript_20D9B8:: @ 820D9B8
	msgbox SlateportCity_House2_Text_20DA59, MSGBOX_NPC
	end

SlateportCity_House2_Text_20D9C1: @ 820D9C1
	.string "Mon POKéMON est PRESSE.\n"
	.string "C'est sa nature.\p"
	.string "Sa VITESSE est plus élevée que celle de\n"
	.string "mes autres POKéMON.\p"
	.string "La nature des POKéMON a peut-être\n"
	.string "rapport avec leurs stats.$"

SlateportCity_House2_Text_20DA59: @ 820DA59
	.string "Tu es un DRESSEUR, n'est-ce pas?\p"
	.string "Tu dois vouloir te rendre à la TENTE\n"
	.string "DE COMBAT de POIVRESSEL, non?$"