PacifidlogTown_House1_MapScripts:: @ 820365C
	.byte 0

PacifidlogTown_House1_EventScript_20365D:: @ 820365D
	msgbox PacifidlogTown_House1_Text_20366F, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_203666:: @ 8203666
	msgbox PacifidlogTown_House1_Text_20373A, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_20366F: @ 820366F
	.string "Dans la région de HOENN, il existe trois\n"
	.string "POKéMON qui symbolisent la puissance\l"
	.string "de la pierre, de la glace et de l'acier.\p"
	.string "On raconte qu'ils se cachent dans\n"
	.string "des grottes obscures.\p"
	.string "C'est une histoire que j'ai entendue\n"
	.string "quand j'étais petit.$"

PacifidlogTown_House1_Text_20373A: @ 820373A
	.string "“Six points ouvrent trois portes.”\p"
	.string "Pépé disait souvent ça, mais je ne sais\n"
	.string "pas ce que ça veut dire.$"

