gBattleDomeOpponentPotentialText1::
	.string "Meilleur candidat au titre!$"

gBattleDomeOpponentPotentialText2::
	.string "Ira au moins jusqu'en demi-finale.$"

gBattleDomeOpponentPotentialText3::
	.string "Finira sûrement dans le trio gagnant.$"

gBattleDomeOpponentPotentialText4::
	.string "Candidat potentiel à la première place.$"

gBattleDomeOpponentPotentialText5::
	.string "Equipe à très fort potentiel.$"

gBattleDomeOpponentPotentialText6::
	.string "Equipe dont on ne sait rien.$"

gBattleDomeOpponentPotentialText7::
	.string "Equipe au-dessus de la moyenne.$"

gBattleDomeOpponentPotentialText8::
	.string "Equipe dans la moyenne.$"

gBattleDomeOpponentPotentialText9::
	.string "Equipe à potentiel moyen.$"

gBattleDomeOpponentPotentialText10::
	.string "Equipe en dessous de la moyenne.$"

gBattleDomeOpponentPotentialText11::
	.string "Equipe n'ayant encore jamais gagné.$"

gBattleDomeOpponentPotentialText12::
	.string "Une victoire les rendrait très fiers.$"

gBattleDomeOpponentPotentialText13::
	.string "Equipe assez faible dans l'ensemble.$"

gBattleDomeOpponentPotentialText14::
	.string "Equipe à potentiel très faible.$"

gBattleDomeOpponentPotentialText15::
	.string "Equipe qui n'ira sûrement pas en finale.$"

gBattleDomeOpponentPotentialText16::
	.string "Equipe au potentiel le plus faible.$"

gBattleDomeOpponentPotentialText17::
	.string "Superstar incontestée et invincible!$"

gBattleDomeOpponentStyleText1::
	.string "N'hésite pas à prendre des risques.$"

gBattleDomeOpponentStyleText2::
	.string "Fait preuve d'endurance au combat.$"

gBattleDomeOpponentStyleText3::
	.string "Change de tactique selon l'adversaire.$"

gBattleDomeOpponentStyleText4::
	.string "Profil de gagnant très prononcé.$"

gBattleDomeOpponentStyleText5::
	.string "Utilise parfois de très rares attaques.$"

gBattleDomeOpponentStyleText6::
	.string "Aime faire sursauter et déranger.$"

gBattleDomeOpponentStyleText7::
	.string "Observe tout le temps les PV au combat.$"

gBattleDomeOpponentStyleText8::
	.string "Stocke puis relâche de la puissance.$"

gBattleDomeOpponentStyleText9::
	.string "Sait bien affaiblir l'adversaire.$"

gBattleDomeOpponentStyleText10::
	.string "S'en remet souvent à la chance.$"

gBattleDomeOpponentStyleText11::
	.string "Attaque de façon majestueuse.$"

gBattleDomeOpponentStyleText12::
	.string "Capacités puissantes à faibles PP.$"

gBattleDomeOpponentStyleText13::
	.string "Affaiblit d'abord, attaque ensuite.$"

gBattleDomeOpponentStyleText14::
	.string "Grande résistance aux attaques.$"

gBattleDomeOpponentStyleText15::
	.string "Aime énerver les ennemis.$"

gBattleDomeOpponentStyleText16::
	.string "Capacités puissantes et directes.$"

gBattleDomeOpponentStyleText17::
	.string "Agressif, capacités puissantes.$"

gBattleDomeOpponentStyleText18::
	.string "Se bat en esquivant les attaques.$"

gBattleDomeOpponentStyleText19::
	.string "Aime contrarier l'adversaire.$"

gBattleDomeOpponentStyleText20::
	.string "Aime les capacités connues.$"

gBattleDomeOpponentStyleText21::
	.string "Capacités aux combinaisons puissantes.$"

gBattleDomeOpponentStyleText22::
	.string "Attaques à fort taux de réussite.$"

gBattleDomeOpponentStyleText23::
	.string "Capacités spectaculaires, agressif.$"

gBattleDomeOpponentStyleText24::
	.string "Préfère l'attaque à la défense.$"

gBattleDomeOpponentStyleText25::
	.string "Préfère la défense à l'attaque.$"

gBattleDomeOpponentStyleText26::
	.string "Rapide, capacités puissantes.$"

gBattleDomeOpponentStyleText27::
	.string "Aime les capacités à effets ajoutés.$"

gBattleDomeOpponentStyleText28::
	.string "Eventail de capacités bien équilibré.$"

gBattleDomeOpponentStyleTextUnused1::
	.string "C'est le message d'essai 1.$"

gBattleDomeOpponentStyleTextUnused2::
	.string "C'est le message d'essai 2.$"

gBattleDomeOpponentStyleTextUnused3::
	.string "C'est le message d'essai 3.$"

gBattleDomeOpponentStyleTextUnused4::
	.string "C'est le message d'essai 4.$"

gBattleDomeOpponentStatsText1::
	.string "Favorise les PV et l'ATTAQUE.$"

gBattleDomeOpponentStatsText2::
	.string "Favorise les PV et la DEFENSE.$"

gBattleDomeOpponentStatsText3::
	.string "Favorise les PV et la VITESSE.$"

gBattleDomeOpponentStatsText4::
	.string "Favorise les PV et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText5::
	.string "Favorise les PV et la DEF. SPE.$"

gBattleDomeOpponentStatsText6::
	.string "Favorise l'ATTAQUE et la DEFENSE.$"

gBattleDomeOpponentStatsText7::
	.string "Favorise l'ATTAQUE et la VITESSE.$"

gBattleDomeOpponentStatsText8::
	.string "Favorise l'ATTAQUE et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText9::
	.string "Favorise l'ATTAQUE et la DEF. SPE.$"

gBattleDomeOpponentStatsText10::
	.string "Favorise la DEFENSE et la VITESSE.$"

gBattleDomeOpponentStatsText11::
	.string "Favorise la DEFENSE et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText12::
	.string "Favorise la DEFENSE et la DEF. SPE.$"

gBattleDomeOpponentStatsText13::
	.string "Favorise la VITESSE et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText14::
	.string "Favorise la VITESSE et la DEF. SPE.$"

gBattleDomeOpponentStatsText15::
	.string "Favorise l'ATQ. SPE. et la DEF. SPE.$"

gBattleDomeOpponentStatsText16::
	.string "Favorise les PV.$"

gBattleDomeOpponentStatsText17::
	.string "Favorise l'ATTAQUE.$"

gBattleDomeOpponentStatsText18::
	.string "Favorise la DEFENSE.$"

gBattleDomeOpponentStatsText19::
	.string "Favorise la VITESSE.$"

gBattleDomeOpponentStatsText20::
	.string "Favorise l'ATQ. SPE.$"

gBattleDomeOpponentStatsText21::
	.string "Favorise la DEF. SPE.$"

gBattleDomeOpponentStatsText22::
	.string "Néglige les PV et l'ATTAQUE.$"

gBattleDomeOpponentStatsText23::
	.string "Néglige les PV et la DEFENSE.$"

gBattleDomeOpponentStatsText24::
	.string "Néglige les PV et la VITESSE.$"

gBattleDomeOpponentStatsText25::
	.string "Néglige les PV et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText26::
	.string "Néglige les PV et la DEF. SPE.$"

gBattleDomeOpponentStatsText27::
	.string "Néglige l'ATTAQUE et la DEFENSE.$"

gBattleDomeOpponentStatsText28::
	.string "Néglige l'ATTAQUE et la VITESSE.$"

gBattleDomeOpponentStatsText29::
	.string "Néglige l'ATTAQUE et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText30::
	.string "Néglige l'ATTAQUE et la DEF. SPE.$"

gBattleDomeOpponentStatsText31::
	.string "Néglige la DEFENSE et la VITESSE.$"

gBattleDomeOpponentStatsText32::
	.string "Néglige la DEFENSE et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText33::
	.string "Néglige la DEFENSE et la DEF. SPE.$"

gBattleDomeOpponentStatsText34::
	.string "Néglige la VITESSE et l'ATQ. SPE.$"

gBattleDomeOpponentStatsText35::
	.string "Néglige la VITESSE et la DEF. SPE.$"

gBattleDomeOpponentStatsText36::
	.string "Néglige l'ATQ. SPE. et la DEF. SPE.$"

gBattleDomeOpponentStatsText37::
	.string "Néglige les PV.$"

gBattleDomeOpponentStatsText38::
	.string "Néglige l'ATTAQUE.$"

gBattleDomeOpponentStatsText39::
	.string "Néglige la DEFENSE.$"

gBattleDomeOpponentStatsText40::
	.string "Néglige la VITESSE.$"

gBattleDomeOpponentStatsText41::
	.string "Néglige l'ATQ. SPE.$"

gBattleDomeOpponentStatsText42::
	.string "Néglige la DEF. SPE.$"

gBattleDomeOpponentStatsText43::
	.string "Elève ses POKéMON de façon équilibrée.$"

gBattleDomeWinText1::
	.string "Que le combat commence!$"

gBattleDomeWinText2::
	.string "{STR_VAR_1} a gagné avec {STR_VAR_2}!$"

gBattleDomeWinText3::
	.string "{STR_VAR_1} a le titre de champion!$"

gBattleDomeWinText4::
	.string "{STR_VAR_1} a gagné par forfait!$"

gBattleDomeWinText5::
	.string "{STR_VAR_1} a gagné par forfait!$"

gBattleDomeWinText6::
	.string "{STR_VAR_1} a gagné sans rien faire!$"

gBattleDomeWinText7::
	.string "{STR_VAR_1} a gagné sans rien faire!$"

gBattleDomeMatchNumberText1::
	.string "1{SUPER_ER} tour, combat nº 1$"

gBattleDomeMatchNumberText2::
	.string "1{SUPER_ER} tour, combat nº 2$"

gBattleDomeMatchNumberText3::
	.string "1{SUPER_ER} tour, combat nº 3$"

gBattleDomeMatchNumberText4::
	.string "1{SUPER_ER} tour, combat nº 4$"

gBattleDomeMatchNumberText5::
	.string "1{SUPER_ER} tour, combat nº 5$"

gBattleDomeMatchNumberText6::
	.string "1{SUPER_ER} tour, combat nº 6$"

gBattleDomeMatchNumberText7::
	.string "1{SUPER_ER} tour, combat nº 7$"

gBattleDomeMatchNumberText8::
	.string "1{SUPER_ER} tour, combat nº 8$"

gBattleDomeMatchNumberText9::
	.string "2{SUPER_E} tour, combat nº 1$"

gBattleDomeMatchNumberText10::
	.string "2{SUPER_E} tour, combat nº 2$"

gBattleDomeMatchNumberText11::
	.string "2{SUPER_E} tour, combat nº 3$"

gBattleDomeMatchNumberText12::
	.string "2{SUPER_E} tour, combat nº 4$"

gBattleDomeMatchNumberText13::
	.string "Demi-finale, combat nº 1$"

gBattleDomeMatchNumberText14::
	.string "Demi-finale, combat nº 2$"

gBattleDomeMatchNumberText15::
	.string "Finale$"
