CableClub_Text_WelcomeWhichCableClubService: @ 8277EA4
	.string "Bienvenue au CLUB LINK POKéMON.\p"
	.string "Lequel de nos services\n"
	.string "souhaiteriez-vous utiliser?$"

CableClub_Text_WhichService: @ 8277EF1
	.string "Lequel de nos services\n"
	.string "souhaiteriez-vous utiliser?$"

CableClub_Text_TradeUsingLinkCable:: @ 8277F1B
	.string "Echanger ses POKéMON avec un\n"
	.string "câble GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable:: @ 8277F5A
	.string "Vous pouvez affronter un autre\n"
	.string "joueur avec un câble GBA Game Link.$"

CableClub_Text_RecordCornerUsingLinkCable:: @ 8277F96
	.string "Le CENTRE DE DONNEES est ouvert aux\n"
	.string "personnes ayant un câble GBA Game Link.$"

@ Unused
CableClub_Text_CloseThisMenu: @ 8277FDD
	.string "Close this menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle: @ 8277FEE
	.string "Pour jouer en COMBAT DUO, il faut\n"
	.string "avoir au moins deux POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade: @ 8278027
	.string "Pour un échange, il faut avoir au moins\n"
	.string "deux POKéMON en sa possession.$"

CableClub_Text_CantTradeEnigmaBerry: @ 8278061
	.string "Votre POKéMON qui porte la BAIE {STR_VAR_1}\n"
	.string "ne peut pas être échangé.$"

gText_PleaseWaitForLink:: @ 8278091
	.string "Veuillez patienter.\n"
	.string "Appuyez sur le bouton B pour annuler…$"

gText_ConfirmLinkWhenPlayersReady:: @ 82780B3
	.string "Lorsque tous les joueurs sont prêts…\n"
	.string "Bouton A: Confirmer   Bouton B: Annuler$"

gText_ConfirmStartLinkWithXPlayers:: @ 82780F2
	.string "Démarrer connexion entre les {STR_VAR_1} joueurs.\n"
	.string "Bouton A: Confirmer   Bouton B: Annuler$"

gText_AwaitingLinkup:: @ 8278131
	.string "Connexion en cours…\n"
	.string "Bouton B: Annuler$"

@ Unused
CableClub_Text_OkayToSaveProgress:: @ 8278157
	.string "Your progress must be saved before\n"
	.string "linking. Is it okay to save?$"

CableClub_Text_PleaseEnter: @ 8278197
	.string "Veuillez entrer.$"

CableClub_Text_DirectYouToYourRoom: @ 82781A5
	.string "Je vais vous mener à la salle.$"

Text_SomeoneIsNotReadyToLink: @ 82781C7
	.string "Quelqu'un n'est pas prêt à se\n"
	.string "connecter.\p"
	.string "Veuillez revenir une fois que chacun\n"
	.string "des joueurs sera prêt.$"

Text_LinkErrorPleaseReset: @ 827821C
	.string "Erreur de connexion…\n"
	.string "Vérifiez les branchements et\l"
	.string "réinitialisez les consoles.$"

Text_PlayersMadeDifferentSelections: @ 8278255
	.string "Les joueurs se connectant semblent\n"
	.string "ne pas avoir fait le même choix.$"

CableClub_Text_PleaseVisitAgain: @ 8278291
	.string "Revenez quand vous voulez.$"

CableClub_Text_IncorrectNumberOfParticipants: @ 82782A8
	.string "Le nombre de participants n'est pas\n"
	.string "correct.$"

CableClub_Text_CantSingleBattleWithXPlayers: @ 82782D1
	.string "Il est impossible de jouer avec {STR_VAR_1}\n"
	.string "joueurs en mode COMBAT SOLO.$"

CableClub_Text_CantDoubleBattleWithXPlayers: @ 8278307
	.string "Il est impossible de jouer avec {STR_VAR_1}\n"
	.string "joueur(s) en mode COMBAT DUO.$"

CableClub_Text_NeedFourPlayers: @ 827833D
	.string "Il faut être quatre joueurs pour jouer\n"
	.string "à ce mode de combat.$"

CableClub_Text_PleaseConfirmNumberAndRestart: @ 8278372
	.string "Veuillez confirmer le nombre de joueurs\n"
	.string "et recommencer.$"

Text_TerminateLinkConfirmation: @ 82783A8
	.string "La connexion prendra fin si vous\n"
	.string "quittez la pièce. Sortir?$"

Text_TerminateLinkPleaseWait: @ 82783E9
	.string "Fin de la connexion. On vous conduira à\n"
	.string "la sortie de la pièce.\l"
	.string "Veuillez patienter.$"

CableClub_Text_TooBusyToNotice: @ 827842E
	.string "Ce DRESSEUR est trop occupé pour voir…$"

CableClub_Text_GotToLookAtTrainerCard: @ 8278452
	.string "Bravo! Tu peux regarder la CARTE\n"
	.string "DRESSEUR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard: @ 827847B
	.string "Bravo! Tu peux regarder la CARTE\n"
	.string "DRESSEUR de {STR_VAR_1}!\p"
	.string "C'est une carte en {STR_VAR_2}!$"

SingleBattleColosseum_Text_TakePlaceStartBattle: @ 82784B4
	.string "Veuillez prendre place et commencer\n"
	.string "à combattre.$"

TradeCenter_Text_TakeSeatStartTrade: @ 82784E2
	.string "Veuillez prendre place et commencer\n"
	.string "l'échange.$"

RecordCorner_Text_ThanksForComing: @ 827850E
	.string "Merci de votre visite.$"

CableClub_Text_TrainerCardDataOverwritten: @ 8278521
	.string "Les données sur la CARTE DRESSEUR\n"
	.string "vont être écrasées.$"

CableClub_Text_HopeToSeeYouAgain: @ 827854C
	.string "A une prochaine fois!$"

CableClub_Text_NotSetUpForFarAwayRegion: @ 8278565
	.string "Je suis terriblement désolée.\p"
	.string "Nous ne sommes pas équipés pour\n"
	.string "effectuer des échanges avec des\l"
	.string "DRESSEURS d'une région si lointaine.$"

CableClub_Text_OtherTrainerNotReady: @ 82785C9
	.string "L'autre DRESSEUR n'est pas prêt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken: @ 82785E9
	.string "Au moins un POKéMON ne peut\n"
	.string "pas être pris.$"

RecordCorner_Text_TakeSeatAndWait: @ 827861C
	.string "Veuillez prendre place et attendre.$"

RecordCorner_Text_PlayerSentOverOneX: @ 827863C
	.string "{STR_VAR_1} envoie un\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame: @ 8278651
	.string "Veuillez nous excuser.\n"
	.string "La connexion a été annulée.\p"
	.string "Vous ne pouvez pas échanger vos\n"
	.string "données avec des jeux\l"
	.string "Rubis ou Saphir japonais.\p"
	.string "De même, vous ne pouvez pas échanger\n"
	.string "vos données avec un jeu Emeraude\p"
	.string "japonais et des jeux Rubis et Saphir\n"
	.string "non japonais en même temps.$"

CableClub_Text_AdapterNotConnected: @ 827871F
	.string "L'adaptateur sans fil GBA n'est pas\n"
	.string "connecté correctement.$"

CableClub_Text_ParticipantsStepUpToCounter: @ 827874F
	.string "Les participants doivent se\n"
	.string "présenter à la réception.$"

@ Unused
CableClub_Text_Hello: @ 827878B
	.string "Hello!$"

@ Unused
CableClub_Text_PleaseWait: @ 8278792
	.string "Please wait.$"

CableClub_Text_YouMayTradeHere:: @ 827879F
	.string "Vous pouvez y faire des échanges\n"
	.string "de POKéMON avec un ami.$"

CableClub_Text_YouMayBattleHere:: @ 82787D5
	.string "Vous pouvez affronter vos amis ici.$"

CableClub_Text_CanMakeBerryPowder:: @ 82787FC
	.string "De deux à cinq DRESSEURS peuvent\n"
	.string "faire de la POUDRE BAIE ensemble.$"

CableClub_Text_CanMixRecords:: @ 8278831
	.string "Les données de deux à quatre joueurs\n"
	.string "peuvent être échangées.$"

OldaleTown_PokemonCenter_2F_Text_27886B: @ 827886B
	.string "A guide to the WIRELESS CLUB's\n"
	.string "various services.$"

CableClub_Text_CancelSelectedItem:: @ 827889C
	.string "Annuler le MENU sélectionné.$"

OldaleTown_PokemonCenter_2F_Text_2788BC: @ 82788BC
	.string "Which battle mode would you like?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep: @ 82788DE
	.string "Returns to the previous step.$"

CableClub_Text_NeedBerryForBerryCrush: @ 82788FC
	.string "Pour utiliser le BROYEUR DE BAIES,\n"
	.string "il faut avoir au moins une BAIE.$"

CableClub_Text_NeedTwoMonsForUnionRoom: @ 827893E
	.string "Pour entrer dans la SALLE UNION,\n"
	.string "il faut avoir au moins deux PKMN.$"

CableClub_Text_NoEnigmaBerryInUnionRoom: @ 827897B
	.string "Un PKMN tenant la BAIE {STR_VAR_1} ne\n"
	.string "peut entrer dans la SALLE UNION.$"

CableClub_Text_UnionRoomAdapterNotConnected: @ 82789B5
	.string "C'est la SALLE UNION du\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "Votre adaptateur sans fil GBA\n"
	.string "n'est pas connecté correctement.\p"
	.string "Revenez plus tard.$"

@ Unused
CableClub_Text_OhExcuseMe: @ 8278A39
	.string "Oh…\n"
	.string "Excuse me!$"

CableClub_Text_PlayerIsWaiting: @ 8278A48
	.string "On dirait que {STR_VAR_1} est en\n"
	.string "train de jouer.\l"
	.string "Allez-y!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame: @ 8278A7D
	.string "Je peux vous expliquer les règles\n"
	.string "du jeu, si vous le souhaitez.\p"
	.string "Vous voulez des infos sur\n"
	.string "quel jeu?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo: @ 8278ACB
	.string "SAUT POKéMON\p"
	.string "Faites sauter votre POKéMON à\n"
	.string "la corde avec le bouton A.\p"
	.string "Seuls les POKéMON jusqu'à\n"
	.string "environ 70 cm peuvent participer.\p"
	.string "Les POKéMON capables seulement\n"
	.string "de nager, creuser ou voler\p"
	.string "ne sont pas vraiment bons au saut\n"
	.string "et ne peuvent donc pas participer.\p"
	.string "Des choses intéressantes arrivent\n"
	.string "si tout le monde saute en rythme.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo: @ 8278BF1
	.string "ATTRAPE-BAIES DODRIO\p"
	.string "Faites bouger les têtes de DODRIO\n"
	.string "pour attraper les BAIES.\p"
	.string "Appuyez sur gauche, haut et droite\n"
	.string "sur la manette {PLUS}.\p"
	.string "Pour jouer à ce jeu, vous devez\n"
	.string "avoir un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay: @ 8278CAC
	.string "Si vous voulez commencer un jeu,\n"
	.string "allez voir le vieil homme à côté.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait: @ 8278CEB
	.string "Salut! Voulez-vous jouer en\n"
	.string "utilisant le système de\l"
	.string "communication sans fil?\p"
	.string "Vous pouvez patienter encore\n"
	.string "un petit peu? $"

MossdeepCity_GameCorner_1F_Text_ComeAgain: @ 8278D51
	.string "Très bien, à bientôt.$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected: @ 8278D68
	.string "L'adaptateur sans fil GBA n'est\n"
	.string "pas connecté.\p"
	.string "Revenez quand il sera branché!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame: @ 8278DAD
	.string "Très bien, à quel jeu\n"
	.string "vouliez-vous jouer?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon: @ 8278DD9
	.string "Quel POKéMON choisissez-vous?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo: @ 8278E00
	.string "Parfait, ça va bientôt commencer. Ne\n"
	.string "vous faites pas battre par les autres!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain: @ 8278E3C
	.string "Are you leaving now?\n"
	.string "Do come again!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon: @ 8278E60
	.string "Aucun de vos POKéMON ne peut\n"
	.string "participer…\p"
	.string "Voulez-vous savoir quels POKéMON\n"
	.string "peuvent participer?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed: @ 8278EDC
	.string "Le SAUT POKéMON est ouvert aux\n"
	.string "POKéMON jusqu'à environ 70 cm.\p"
	.string "Les POKéMON ne pouvant pas sauter\n"
	.string "ne peuvent pas participer.\p"
	.string "Comme ceux qui ne peuvent que\n"
	.string "nager, voler ou creuser.\p"
	.string "Voilà, c'est tout ce qu'il faut\n"
	.string "savoir.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed: @ 8278FA4
	.string "ATTRAPE-BAIES DODRIO est un jeu où\n"
	.string "seuls les DODRIO peuvent participer.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease: @ 8278FE0
	.string "Could you retry this from the start\n"
	.string "again, please?$"

CableClub_Text_WelcomeWhichDirectCornerRoom: @ 8279013
	.string "Bienvenue au CLUB SANS FIL\n"
	.string "POKéMON.\p"
	.string "Vous pouvez communiquer avec\n"
	.string "vos amis à partir d'ici.\p"
	.string "A quelle salle voulez-vous\n"
	.string "accéder?$"

CableClub_Text_TradePokemon: @ 827909D
	.string "Voulez-vous échanger un POKéMON?$"

CableClub_Text_WhichBattleMode: @ 82790BE
	.string "A quel mode de combat\n"
	.string "voulez-vous jouer?$"

CableClub_Text_AccessRecordCorner: @ 82790E8
	.string "Voulez-vous accéder au CENTRE\n"
	.string "DE DONNEES?$"

CableClub_Text_UseBerryCrush: @ 8279114
	.string "Voulez-vous utiliser le\n"
	.string "BROYEUR DE BAIES?$"

CableClub_Text_ExplainBattleModes: @ 8279142
	.string "Il existe trois modes de combat.\p"
	.string "En COMBAT SOLO, deux DRESSEURS\n"
	.string "avec au moins un POKéMON chacun\l"
	.string "combattent.\p"
	.string "Chaque DRESSEUR ne peut envoyer\n"
	.string "qu'un seul POKéMON à la fois au\l"
	.string "combat. \p"
	.string "En COMBAT DUO, deux DRESSEURS\n"
	.string "avec au moins deux POKéMON chacun\l"
	.string "combattent.\p"
	.string "Chaque DRESSEUR envoie au combat\n"
	.string "deux POKéMON en même temps.\p"
	.string "En COMBAT MULTI, quatre DRESSEURS\n"
	.string "avec au moins un POKéMON chacun\l"
	.string "combattent.\p"
	.string "Chaque DRESSEUR ne peut envoyer\n"
	.string "qu'un seul POKéMON à la fois au\l"
	.string "combat.$"

CableClub_Text_ChooseGroupLeaderOfTwo: @ 82792CD
	.string "Veuillez choisir lequel de vous\n"
	.string "deux sera le MENEUR.\p"
	.string "L'autre joueur devra ensuite\n"
	.string "choisir “JOINDRE”.$"

CableClub_Text_ChooseGroupLeaderOfFour: @ 8279334
	.string "Veuillez choisir lequel d'entre\n"
	.string "vous sera le MENEUR du GROUPE.\p"
	.string "Les autres joueurs devront ensuite\n"
	.string "choisir “JOINDRE”.$"

CableClub_Text_ChooseGroupLeader: @ 82793A3
	.string "Veuillez choisir lequel d'entre\n"
	.string "vous sera le MENEUR du GROUPE.\p"
	.string "Les autres joueurs devront ensuite\n"
	.string "choisir “JOINDRE”.$"

CableClub_Text_WelcomeUnionRoomEnter: @ 827940D
	.string "Bienvenue à la SALLE UNION du\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "Vous pouvez y communiquer avec\n"
	.string "d'autres DRESSEURS. Même avec\l"
	.string "ceux que vous ne connaissez pas.$"

CableClub_Text_UnionRoomInfo: @ 82794B8
	.string "Les DRESSEURS dans la SALLE\n"
	.string "UNION sont ceux autour de vous qui\l"
	.string "ont aussi pénétré dans la salle.\p"
	.string "Vous pouvez faire plein de choses\n"
	.string "ici, comme par exemple discuter.\p"
	.string "Vous pouvez faire entrer 2 POKéMON\n"
	.string "jusqu'au niveau 30 pour un combat\p"
	.string "un contre un. Vous pouvez aussi\n"
	.string "participer à des tchats\p"
	.string "réunissant de 2 à 5 personnes.\p"
	.string "Ou vous pouvez encore enregistrer\n"
	.string "un POKéMON pour un échange.\p"
	.string "Voulez-vous entrer dans la SALLE?$"

CableClub_Text_EnjoyUnionRoom: @ 827961C
	.string "J'espère que vous aimerez votre\n"
	.string "visite dans la SALLE UNION.$"

CableClub_Text_FirstTimeRightThisWay: @ 827964A
	.string "Bonjour!\n"
	.string "Je suis ZADIA.\p"
	.string "C'est la première fois que je\n"
	.string "vous vois ici.\p"
	.string "Je vais vous montrer comment le\n"
	.string "système sans fil fonctionne.\p"
	.string "Je dois d'abord vous faire visiter\n"
	.string "cet étage du CENTRE POKéMON.\p"
	.string "Par ici, s'il vous plaît.$"

CableClub_Text_ExplainWirelessClubFirstTime: @ 8279718
	.string "Au niveau supérieur, il y a\n"
	.string "deux salles.\p"
	.string "Tout d'abord, la salle à gauche\n"
	.string "est la SALLE UNION.\p"
	.string "Vous pouvez vous connecter avec\n"
	.string "les DRESSEURS autour de vous\l"
	.string "qui sont dans la SALLE UNION.\p"
	.string "Vous pouvez parler, faire des\n"
	.string "échanges ou combattre avec eux.\p"
	.string "Ensuite, la salle à droite\n"
	.string "est la SALLE LINK DIRECT. \p"
	.string "Vous pouvez combattre ou faire\n"
	.string "des échanges avec vos amis.\p"
	.string "Si l'adaptateur sans fil n'est pas\n"
	.string "utilisé, vous pouvez toujours vous\l"
	.string "connecter avec un câble Game Link.\p"
	.string "Si c'est le cas, allez directement\n"
	.string "dans la SALLE LINK DIRECT.\p"
	.string "J'espère que vous apprécierez\n"
	.string "le système sans fil.$"

CableClub_Text_AskAboutLinking: @ 8279937
	.string "Bonjour {PLAYER}!\p"
	.string "Je suis ZADIA, je m'occupe du 1er\n"
	.string "étage du CENTRE POKéMON.\p"
	.string "Y a-t-il quelque chose que vous\n"
	.string "aimeriez savoir sur la connexion?$"

CableClub_Text_ExplainWirelessClub: @ 82799AA
	.string "Laissez-moi vous décrire le\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "Au niveau supérieur, il y a\n"
	.string "deux salles.\p"
	.string "Tout d'abord, la salle à gauche\n"
	.string "est la SALLE UNION.\p"
	.string "Vous pouvez vous connecter avec\n"
	.string "les DRESSEURS autour de vous\l"
	.string "qui sont dans la SALLE UNION.\p"
	.string "Vous pouvez parler, faire des\n"
	.string "échanges ou combattre avec eux.\p"
	.string "Ensuite, la salle à droite\n"
	.string "est la SALLE LINK DIRECT. \p"
	.string "Vous pouvez combattre ou faire\n"
	.string "des échanges avec vos amis.\p"
	.string "Dans certains cas, vous ne\n"
	.string "pourrez vous connecter avec\l"
	.string "vos amis dans aucune des salles.\p"
	.string "Si c'est le cas, rapprochez-vous\n"
	.string "de vos amis.\p"
	.string "Si l'adaptateur sans fil n'est pas\n"
	.string "utilisé, vous pouvez toujours vous\l"
	.string "connecter avec un câble Game Link.\p"
	.string "Si c'est le cas, allez directement\n"
	.string "dans la SALLE LINK DIRECT.\p"
	.string "J'espère que vous apprécierez\n"
	.string "le système sans fil.$"

CableClub_Text_HopeYouEnjoyWirelessSystem: @ 8279C91
	.string "J'espère que vous apprécierez\n"
	.string "le système sans fil.$"
