Text_PictureBookShelf: @ 82A81E5
	.string "Ce sont des albums de POKéMON.$"

Text_BookShelf: @ 82A820D
	.string "Il y a toutes sortes de livres.$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "Des magazines POKéMON!\n"
	.string "NOS AMIS LES POKéMON…\p"
	.string "MANUEL POKéMON…\n"
	.string "GRAINE DE POKéMON…$"

Text_Vase: @ 82A8276
	.string "Ce vase semble avoir de la valeur!\p"
	.string "En regardant à l'intérieur, on\n"
	.string "s'aperçoit qu'il est vide.$"

Text_EmptyTrashCan: @ 82A82B3
	.string "C'est vide.$"

Text_ShopShelf: @ 82A82BF
	.string "Les étagères regorgent de toutes\n"
	.string "sortes de produits POKéMON.$"

Text_Blueprint: @ 82A82F7
	.string "Voilà un curieux plan!\n"
	.string "Ça a l'air compliqué.$"
