@ contest move effect descriptions

gContestEffect00hDescription:: @ 827CB82
	.string "Une démo très convaincante.$"

gContestEffect01hDescription:: @ 827CB9B
	.string "Le POKéMON est facilement\n"
	.string "effrayé après cette démo.$"

gContestEffect02hDescription:: @ 827CBCE
	.string "Plaît énormément, mais ne\n"
	.string "permet plus aucune démo.$"

gContestEffect03hDescription:: @ 827CC03
	.string "Peut être utilisé plusieurs\n"
	.string "fois sans ennuyer le JUGE.$"

gContestEffect04hDescription:: @ 827CC34
	.string "Peut éviter une fois d'être\n"
	.string "effrayé par les autres.$"

gContestEffect05hDescription:: @ 827CC5D
	.string "Peut éviter d'être effrayé\n"
	.string "par les autres.$"

gContestEffect06hDescription:: @ 827CC81
	.string "Peut un peu éviter d'être\n"
	.string "effrayé par les autres.$"

gContestEffect07hDescription:: @ 827CCAE
	.string "Le POKéMON a moins de\n"
	.string "chances d'être effrayé.$"

gContestEffect08hDescription:: @ 827CCE7
	.string "Effraie légèrement le\n"
	.string "POKéMON précédent.$"

gContestEffect09hDescription:: @ 827CD0F
	.string "Effraie légèrement ceux\n"
	.string "qui ont déjà fait leur démo.$"

gContestEffect0AhDescription:: @ 827CD3F
	.string "Effraie le POKéMON ayant\n"
	.string "fait sa démo avant.$"

gContestEffect0BhDescription:: @ 827CD73
	.string "Effraie les POKéMON ayant\n"
	.string "fait leur démonstration.$"

gContestEffect0ChDescription:: @ 827CDA6
	.string "Effraie beaucoup le\n"
	.string "POKéMON précédent.$"

gContestEffect0DhDescription:: @ 827CDCB
	.string "Effraie beaucoup ceux\n"
	.string "qui ont déjà fait leur démo.$"

gContestEffect0EhDescription:: @ 827CDF8
	.string "Effraie le POKéMON ayant\n"
	.string "fait sa démo avant.$"

gContestEffect0FhDescription:: @ 827CE2C
	.string "Effraie tous les POKéMON\n"
	.string "ayant fait leur démo avant.$"

gContestEffect10hDescription:: @ 827CE5F
	.string "Détourne l'attention du\n"
	.string "JUGE des autres POKéMON.$"

gContestEffect11hDescription:: @ 827CE89
	.string "Effraie le POKéMON qui\n"
	.string "a l'attention du JUGE.$"

gContestEffect12hDescription:: @ 827CEBE
	.string "Bloque les autres, mais\n"
	.string "perd un tour de démo.$"

gContestEffect13hDescription:: @ 827CEEF
	.string "Effraie ceux ayant exécuté\n"
	.string "une démo du même type.$"

gContestEffect14hDescription:: @ 827CF1E
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo SG-FD.$"

gContestEffect15hDescription:: @ 827CF4D
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo BEAUTE.$"

gContestEffect16hDescription:: @ 827CF7E
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo GRACE.$"

gContestEffect17hDescription:: @ 827CFAD
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo INTEL.$"

gContestEffect18hDescription:: @ 827CFDD
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo ROBUS.$"

gContestEffect19hDescription:: @ 827D00D
	.string "Rend nerveux le POKéMON\n"
	.string "suivant.$"

gContestEffect1AhDescription:: @ 827D037
	.string "Rend nerveux tous les\n"
	.string "POKéMON suivants.$"

gContestEffect1BhDescription:: @ 827D061
	.string "Diminue la condition de\n"
	.string "ceux qui ont fait une démo.$"

gContestEffect1ChDescription:: @ 827D093
	.string "Effraie beaucoup ceux qui\n"
	.string "sont en bonne condition.$"

gContestEffect1DhDescription:: @ 827D0BD
	.string "Cette démo plaît beaucoup\n"
	.string "si on l'exécute en premier.$"

gContestEffect1EhDescription:: @ 827D0E8
	.string "Cette démo plaît beaucoup\n"
	.string "si on l'exécute en dernier.$"

gContestEffect1FhDescription:: @ 827D112
	.string "Rend la démo aussi réussie\n"
	.string "que les précédentes.$"

gContestEffect20hDescription:: @ 827D13F
	.string "Rend la démo aussi réussie\n"
	.string "que la précédente.$"

gContestEffect21hDescription:: @ 827D16E
	.string "Plus cette démo est lancée\n"
	.string "tard, plus elle est réussie.$"

gContestEffect22hDescription:: @ 827D1A1
	.string "La qualité de la démo\n"
	.string "dépend de son timing.$"

gContestEffect23hDescription:: @ 827D1D6
	.string "Démo réussie si du même\n"
	.string "type que la précédente.$"

gContestEffect24hDescription:: @ 827D20A
	.string "Démo réussie si de type\n"
	.string "différent de la précédente.$"

gContestEffect25hDescription:: @ 827D23F
	.string "Dépend de la façon dont la\n"
	.string "démo précédente se passe.$"

gContestEffect26hDescription:: @ 827D26E
	.string "Monte la condition.\n"
	.string "Empêche d'être nerveux.$"

gContestEffect27hDescription:: @ 827D2A3
	.string "Démo réussie si la condi-\n"
	.string "tion du POKéMON est bonne.$"

gContestEffect28hDescription:: @ 827D2DA
	.string "Prochaine démo exécutée\n"
	.string "plus tôt au tour suivant.$"

gContestEffect29hDescription:: @ 827D309
	.string "Prochaine démo exécutée\n"
	.string "plus tard au tour suivant.$"

gContestEffect2AhDescription:: @ 827D336
	.string "Facilite le changement des\n"
	.string "passages du prochain tour.$"

gContestEffect2BhDescription:: @ 827D369
	.string "Mélange l'ordre de passage\n"
	.string "des démos du prochain tour.$"

gContestEffect2ChDescription:: @ 827D39A
	.string "Une démo qui enthousiasme\n"
	.string "le public de tout CONCOURS.$"

gContestEffect2DhDescription:: @ 827D3CE
	.string "Effraie beaucoup tous les\n"
	.string "POKéMON qui ont plu.$"

gContestEffect2EhDescription:: @ 827D401
	.string "La démo est plus réussie si\n"
	.string "le public est enthousiaste.$"

gContestEffect2FhDescription:: @ 827D436
	.string "Empêche provisoirement le\n"
	.string "public d'être enthousiaste.$"

@ unused move names

gUnusedContestMoveName0:: @ 827D468
	.string "DANSE PLUIE$"

gUnusedContestMoveName1:: @ 827D473
	.string "FRENESIE$"

gUnusedContestMoveName2:: @ 827D478
	.string "PUISSANCE$"

gUnusedContestMoveName3:: @ 827D485
	.string "HYPNOSE$"

gUnusedContestMoveName4:: @ 827D48E
	.string "E-COQUE$"

gUnusedContestMoveName5:: @ 827D499
	.string "KOUD'KORNE$"

gUnusedContestMoveName6:: @ 827D4A5
	.string "DANSE-LAMES$"

gUnusedContestMoveName7:: @ 827D4B2
	.string "ADAPTATION$"

gUnusedContestMoveName8:: @ 827D4BD
	.string "ZENITH$"

gUnusedContestMoveName9:: @ 827D4C7
	.string "REPOS$"

gUnusedContestMoveName10:: @ 827D4CC
	.string "FORCE POIGNE$"

gUnusedContestMoveName11:: @ 827D4D5
	.string "BOUL'ARMURE$"

gUnusedContestMoveName12:: @ 827D4E2
	.string "VERROUILLAGE$"

@ contest type names

gContestMoveTypeCoolText:: @ 827D4EA
	.string "SG-FD$"

gContestMoveTypeBeautyText:: @ 827D4EF
	.string "BEAUTE$"

gContestMoveTypeCuteText:: @ 827D4F6
	.string "GRACE$"

gContestMoveTypeSmartText:: @ 827D4FB
	.string "INTEL.$"

gContestMoveTypeToughText:: @ 827D501
	.string "ROBUS.$"

gText_0827D507:: @ 827D507
	.string "Démonstration nº {STR_VAR_1}!\n"
	.string "Ce sera quelle capacité?$"

gText_0827D531:: @ 827D531
	.string "Démonstration nº {STR_VAR_1}!\n"
	.string "Il ne peut pas participer!$"

gText_0827D55A:: @ 827D55A
	.string "{STR_VAR_1} exécute\n"
	.string "{STR_VAR_2}!$"

gText_0827D56F:: @ 827D56F
	.string "{STR_VAR_1} regarde\n"
	.string "les autres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827D597:: @ 827D597
	.string "Le concours est \n"
	.string "terminé!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827D5C1:: @ 827D5C1
	.string "Mais la démonstration\n"
	.string "est bloquée.$"

gText_0827D5DC:: @ 827D5DC
	.string "Il a suivi l'exemple d'un\n"
	.string "autre POKéMON.$"

gText_0827D600:: @ 827D600
	.string "Mais ça n'a pas marché.$"

gText_0827D612:: @ 827D612
	.string "C'est mieux que\n"
	.string "d'habitude.$"

gText_0827D62D:: @ 827D62D
	.string "Le JUGE a détourné\n"
	.string "le regard.$"

gText_0827D654:: @ 827D654
	.string "Il a travaillé dur pour\n"
	.string "réparer ses erreurs.$"

gText_0827D67E:: @ 827D67E
	.string "Il ne peut plus bouger.$"

gText_0827D69C:: @ 827D69C
	.string "Ça a super bien \n"
	.string "marché.$"

gText_0827D6BA:: @ 827D6BA
	.string "C'était aussi bien que le\n"
	.string "POKéMON en tête.$"

gText_0827D6E5:: @ 827D6E5
	.string "Le JUGE lance un regard\n"
	.string "intéressé.$"

gText_0827D706:: @ 827D706
	.string "Il a plutôt bien réussi.$"

gText_0827D71D:: @ 827D71D
	.string "C'était un peu mieux\n"
	.string "que d'habitude.$"

gText_0827D743:: @ 827D743
	.string "{STR_VAR_1} n'a pas été\n"
	.string "convaincant du tout…{PAUSE_UNTIL_PRESS}$"

gText_0827D764:: @ 827D764
	.string "{STR_VAR_1} n'a pas été\n"
	.string "très convaincant…{PAUSE_UNTIL_PRESS}$"

gText_0827D785:: @ 827D785
	.string "{STR_VAR_1} a un peu\n"
	.string "attiré l'attention.{PAUSE_UNTIL_PRESS}$"

gText_0827D7A5:: @ 827D7A5
	.string "{STR_VAR_1} a beaucoup\n"
	.string "attiré l'attention.{PAUSE_UNTIL_PRESS}$"

gText_0827D7C8:: @ 827D7C8
	.string "{STR_VAR_1} a attiré\n"
	.string "toute l'attention.{PAUSE_UNTIL_PRESS}$"

gText_0827D7E8:: @ 827D7E8
	.string "{STR_VAR_1} n'a pas fait\n"
	.string "sa démonstration.{PAUSE_UNTIL_PRESS}$"

gText_0827D805:: @ 827D805
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_0827D830:: @ 827D830
	.string "$"

gText_0827D831:: @ 827D831
	.string "Le JUGE n'a pas changé\n"
	.string "d'opinion sur {STR_VAR_1}.$"

gText_0827D855:: @ 827D855
	.string "{STR_VAR_3} de {STR_VAR_1}\n"
	.string "change de perceptions.$"

gText_0827D872:: @ 827D872
	.string "L'effet de la démo du\n"
	.string "{STR_VAR_1} se dissipe.$"

gText_0827D88F:: @ 827D88F
	.string "L'effet de la démonstra-\n"
	.string "tion spéciale se dissipe.$"

gText_0827D8B5:: @ 827D8B5
	.string "Toutes les démonstra-\n"
	.string "tions se ressemblent.$"

gText_0827D8E4:: @ 827D8E4
	.string "Ça a déprécié la démons-\n"
	.string "tration de {STR_VAR_2}.$"

gText_0827D8FE:: @ 827D8FE
	.string "Les démos des premiers\n"
	.string "ont été dépréciées.$"

gText_0827D926:: @ 827D926
	.string "Ça a détourné l'attention\n"
	.string "de {STR_VAR_2}.$"

gText_0827D947:: @ 827D947
	.string "Ça a déprécié la démons-\n"
	.string "tration de {STR_VAR_2}.$"

gText_0827D961:: @ 827D961
	.string "Ça a fortement déprécié\n"
	.string "les autres démos.$"

gText_0827D986:: @ 827D986
	.string "Le public a hâte de revoir\n"
	.string "{STR_VAR_1}.$"

gText_0827D9B1:: @ 827D9B1
	.string "Les démos des premiers\n"
	.string "ont été dépréciées.$"

gText_0827D9D9:: @ 827D9D9
	.string "Ça a déprécié la démo\n"
	.string "favorite du JUGE.$"

gText_0827DA03:: @ 827DA03
	.string "Les démos des autres ont\n"
	.string "été dépréciées de moitié.$"

gText_0827DA31:: @ 827DA31
	.string "Il essaye de compenser \n"
	.string "car il a été bloqué.$"

gText_0827DA5B:: @ 827DA5B
	.string "Il ne peut plus participer\n"
	.string "aux démonstrations.$"

gText_0827DA85:: @ 827DA85
	.string "Sa superbe démonstration\n"
	.string "a ému le JUGE.$"

gText_0827DAB2:: @ 827DAB2
	.string "Tout le monde a hâte de\n"
	.string "voir la suite.$"

gText_0827DADA:: @ 827DADA
	.string "Aussi bien que les dé-\n"
	.string "monstrations spéciales.$"

gText_0827DB03:: @ 827DB03
	.string "C'est aussi bien que\n"
	.string "{STR_VAR_1}.$"

gText_0827DB1F:: @ 827DB1F
	.string "Les démos bloquées\n"
	.string "passent inaperçues.$"

gText_0827DB4E:: @ 827DB4E
	.string "Toutes les démonstra-\n"
	.string "tions se ressemblent.$"

gText_827DB75:: @ 827DB75
	.string "Il est plus conscient\n"
	.string "des autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DBB0:: @ 827DBB0
	.string "{STR_VAR_1} ne peut rien\n"
	.string "faire après ça.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DBE0:: @ 827DBE0
	.string "Il s'est un petit\n"
	.string "peu calmé.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DC0F:: @ 827DC0F
	.string "Il a oublié la présence\n"
	.string "des autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DC45:: @ 827DC45
	.string "Il a un peu oublié les\n"
	.string "autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DC7C:: @ 827DC7C
	.string "Il a arrêté de penser\n"
	.string "aux autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DCB4:: @ 827DCB4
	.string "Il a essayé d'effrayer \n"
	.string "les autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DCE7:: @ 827DCE7
	.string "Il a essayé d'éblouir\n"
	.string "les autres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DD12:: @ 827DD12
	.string "Le JUGE n'a pas\n"
	.string "regardé {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DD3D:: @ 827DD3D
	.string "Il a essayé de troubler\n"
	.string "le prochain POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DD6F:: @ 827DD6F
	.string "{STR_VAR_1} est devenu\n"
	.string "nerveux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DD8E:: @ 827DD8E
	.string "Il a essayé de troubler\n"
	.string "les POKéMON suivants.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DDC7:: @ 827DDC7
	.string "Il s'est moqué des\n"
	.string "POKéMON qui réussissent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DDF2:: @ 827DDF2
	.string "{STR_VAR_1} a repris\n"
	.string "sa forme.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DE14:: @ 827DE14
	.string "Il a essayé de bloquer les\n"
	.string "POKéMON qui réussissent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DE44:: @ 827DE44
	.string "{STR_VAR_1}, en tête,\n"
	.string "s'est encore plus démené.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DE73:: @ 827DE73
	.string "{STR_VAR_1} finit par\n"
	.string "être remarqué.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DEA5:: @ 827DEA5
	.string "Il a fait aussi bien que\n"
	.string "le POKéMON précédent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DED9:: @ 827DED9
	.string "La démo du {STR_VAR_1} \n"
	.string "était mauvaise.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DF02:: @ 827DF02
	.string "Il a réussi aussi bien que\n"
	.string "le POKéMON d'avant.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DF3A:: @ 827DF3A
	.string "La démo du {STR_VAR_1} \n"
	.string "était mauvaise.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DF63:: @ 827DF63
	.string "La démo du {STR_VAR_1} \n"
	.string "était mauvaise.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DF8C:: @ 827DF8C
	.string "La démo du {STR_VAR_1}\n"
	.string "était à peu près bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DFB8:: @ 827DFB8
	.string "La démo du {STR_VAR_1}\n"
	.string "était plutôt bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827DFE2:: @ 827DFE2
	.string "La démo du {STR_VAR_1}\n"
	.string "était excellente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E00C:: @ 827E00C
	.string "La démo du {STR_VAR_1}\n"
	.string "était ratée.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E02F:: @ 827E02F
	.string "La démo du {STR_VAR_1}\n"
	.string "s'est mal passée.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E05F:: @ 827E05F
	.string "La démo du {STR_VAR_1}\n"
	.string "était à peu près bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E08B:: @ 827E08B
	.string "La démo du {STR_VAR_1}\n"
	.string "était plutôt bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E0B5:: @ 827E0B5
	.string "La démo du {STR_VAR_1}\n"
	.string "était très bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E0DD:: @ 827E0DD
	.string "La démo du {STR_VAR_1}\n"
	.string "était excellente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E107:: @ 827E107
	.string "C'est le même type que le\n"
	.string "POKéMON précédent. Bien!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E143:: @ 827E143
	.string "Ce n'est pas le même type\n"
	.string "que celui d'avant. Bien!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E17F:: @ 827E17F
	.string "C'était beaucoup mieux\n"
	.string "que le POKéMON précédent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E1BB:: @ 827E1BB
	.string "C'était moins bien que\n"
	.string "le POKéMON précédent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E1F3:: @ 827E1F3
	.string "La condition du\n"
	.string "{STR_VAR_1} a augmenté!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E220:: @ 827E220
	.string "{STR_VAR_1} a réussi\n"
	.string "grâce à son super statut!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E254:: @ 827E254
	.string "Il passera en premier\n"
	.string "au prochain tour.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E289:: @ 827E289
	.string "Il passera en dernier\n"
	.string "au prochain tour.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_827E2C5:: @ 827E2C5
	.string "Il a changé l'ordre pour\n"
	.string "le prochain tour.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E2FE:: @ 827E2FE
	.string "Le JUGE lance un regard\n"
	.string "intéressé à {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E32E:: @ 827E32E
	.string "C'était un bon\n"
	.string "combo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E35B:: @ 827E35B
	.string "C'était un très bon\n"
	.string "combo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E38D:: @ 827E38D
	.string "C'était un excellent\n"
	.string "combo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E3C1:: @ 827E3C1
	.string "{STR_VAR_1} a réussi à\n"
	.string "détourner les yeux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E3EB:: @ 827E3EB
	.string "{STR_VAR_1} a réussi à ne\n"
	.string "pas voir ça.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E416:: @ 827E416
	.string "Ça ne déstabilise pas\n"
	.string "{STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E448:: @ 827E448
	.string "{STR_VAR_1} s'est laissé\n"
	.string "un peu distraire.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E473:: @ 827E473
	.string "Il a essayé d'effrayer \n"
	.string "les autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E4A6:: @ 827E4A6
	.string "Distrait, {STR_VAR_1} a\n"
	.string "baissé la tête.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E4D5:: @ 827E4D5
	.string "Distrait, {STR_VAR_1}\n"
	.string "s'est retourné.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E504:: @ 827E504
	.string "{STR_VAR_1} n'a pas pu \n"
	.string "s'empêcher de crier.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E531:: @ 827E531
	.string "{STR_VAR_1} n'a pas pu\n"
	.string "s'empêcher de sursauter.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E55A:: @ 827E55A
	.string "Distrait, {STR_VAR_1} a\n"
	.string "trébuché.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E58A:: @ 827E58A
	.string "{STR_VAR_1} était trop\n"
	.string "nerveux pour bouger.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E5B2:: @ 827E5B2
	.string "Mais ça n'a pas marché.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E5D0:: @ 827E5D0
	.string "Mais il n'a pas rendu\n"
	.string "sa cible nerveuse.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E606:: @ 827E606
	.string "Mais il n'a rendu personne\n"
	.string "nerveux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E638:: @ 827E638
	.string "Mais il a été ignoré…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E658:: @ 827E658
	.string "Mais il n'a pas pu\n"
	.string "améliorer sa condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E68B:: @ 827E68B
	.string "Sa démo a été mauvaise\n"
	.string "à cause de sa condition.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E6C4:: @ 827E6C4
	.string "Ça n'a eu aucun effet sur\n"
	.string "{STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal:: @ 827E6E3
	.string "{STR_VAR_1}, décevant, a\n"
	.string "refait la même démo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E717:: @ 827E717
	.string "Succès pour {STR_VAR_3}\n"
	.string "du {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E73C:: @ 827E73C
	.string "{STR_VAR_3} du\n"
	.string "{STR_VAR_1} ne plaît pas.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E76A:: @ 827E76A
	.string "Ovation pour {STR_VAR_3}\n"
	.string "du {STR_VAR_1}!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E793:: @ 827E793
	.string "{STR_VAR_1} ne peut par-\n"
	.string "ticiper au prochain tour…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E7BA:: @ 827E7BA
	.string "Il a captivé la foule.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E7EA:: @ 827E7EA
	.string "La foule continue de\n"
	.string "regarder {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_0827E817:: @ 827E817
	.string "{STR_VAR_2} du\n"
	.string "{STR_VAR_1} est ignoré.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness:: @ 827E837
	.string "timidité$"

gText_Contest_Anxiety:: @ 827E83F
	.string "anxiété$"

gText_Contest_Laziness:: @ 827E847
	.string "paresse$"

gText_Contest_Hesitancy:: @ 827E850
	.string "hésitation$"

gText_Contest_Fear:: @ 827E85A
	.string "peur$"

gText_0827E85F:: @ 827E85F
	.string "SANG-FROID$"

gText_0827E868:: @ 827E868
	.string "BEAUTE$"

gText_0827E86F:: @ 827E86F
	.string "GRACE$"

gText_0827E878:: @ 827E878
	.string "INTEL.$"

gText_0827E882:: @ 827E882
	.string "ROBUSTESSE$"

gText_0827E88C:: @ 827E88C
	.string "TENSION$"

gText_0827E894:: @ 827E894
	.string "Cap. SG-FD$"

gText_0827E89E:: @ 827E89E
	.string "Cap. BEAUTE$"

gText_0827E8AA:: @ 827E8AA
	.string "Cap. GRACE$"

gText_0827E8B4:: @ 827E8B4
	.string "Cap. INTEL.$"

gText_0827E8BF:: @ 827E8BF
	.string "Cap. ROBUS.$"

gText_0827E8CA:: @ 827E8CA
	.string "???$"
