EventTicket_Text_OldSeaMapTooFar: @ 82C68A5
	.string "Quoi, mon p'tit?\p"
	.string "Tu as une vieille carte toute\n"
	.string "abîmée?\p"
	.string "Voyons ça.\n"
	.string "… … … … … …\p"
	.string "Oh là là. Ce n'est pas la porte à côté!\n"
	.string "J'ai bien peur de ne pas pouvoir t'aider…$"

EventTicket_Text_BrineyHoldOnASecond: @ 82C6951
	.string "M. MARCO: Attends!\p"
	.string "Je lui dois tellement…\n"
	.string "Bien sûr que nous y allons!$"

EventTicket_Text_BrineyLetsSail: @ 82C69AA
	.string "{PLAYER}{KUN}, je suis vraiment désolé.\p"
	.string "Tu viens me demander de l'aide et\n"
	.string "on t'envoie promener.\p"
	.string "Laisse-moi me rattraper!\p"
	.string "Allez, on lève l'ancre!\p"
	.string "Direction l'île qui se trouve sur\n"
	.string "la VIEILLECARTE!$"

EventTicket_Text_OddTicketGetOnBoard: @ 82C6A71
	.string "C'est un drôle de ticket que tu as là!\p"
	.string "L'île où tu veux aller est très loin\n"
	.string "d'ici, tu sais…\p"
	.string "Personne ne sait ce qui s'y trouve,\n"
	.string "d'ailleurs…\p"
	.string "Je dois dire que ça m'intrigue,\n"
	.string "mon p'tit!!!\p"
	.string "Monte, va.\n"
	.string "On lève l'ancre!$"

FarawayIsland_Entrance_Text_SailorReturn: @ 82C6B42
	.string "M. MARCO est parfois un peu\n"
	.string "imprévisible…\p"
	.string "Tu veux retourner à NENUCRIQUE?$"

BirthIsland_Harbor_Text_SailorReturn: @ 82C6B90
	.string "Cette île a vraiment une drôle de forme!\n"
	.string "Tu veux retourner à NENUCRIQUE?$"

EventTicket_Text_OddTicketsWhereTo: @ 82C6BD4
	.string "Ce sont de drôles de tickets que\n"
	.string "tu as là!\p"
	.string "… … …\n"
	.string "Hum.\p"
	.string "Les îles où tu peux te rendre avec eux\n"
	.string "sont très loin d'ici, tu sais…\p"
	.string "Personne ne sait ce qui s'y trouve,\n"
	.string "d'ailleurs…\p"
	.string "Je dois dire que ça m'intrigue,\n"
	.string "mon p'tit!!\p"
	.string "Monte, va.\n"
	.string "Où va-t-on en premier?$"

NavelRock_Harbor_Text_SailorReturn: @ 82C6CE6
	.string "Est-ce… Est-ce que tu as entendu ça?\n"
	.string "Ce grondement sourd là-dessous?\p"
	.string "On est peut-être en danger.\n"
	.string "Tu crois qu'on devrait partir?$"

FarawayIsland_Entrance_Text_Sign: @ 82C6D5A
	.string "Le texte est presque effacé. Ça a dû\n"
	.string "être écrit il y a très longtemps…\p"
	.string "“… bre… 6… jou…\n"
	.string "Si un humain devai… poser à nouveau le\l"
	.string "pied… cette île, que ce soit… personne\l"
	.string "de cœur… Dans cet espoir, je m'en vai…”$"

FarawayIsland_Interior_Text_Mew: @ 82C6DFF
	.string "Miou…$"
