EventTicket_Text_ShowOldSeaMap: @ 82A6848
	.string "Le ferry allant à POIVRESSEL est…\p"
	.string "Pardon? Est-ce que nous pouvons aller\n"
	.string "à cet endroit indiqué sur la carte?\p"
	.string "Je connais quelqu'un qui pourra t'aider.\n"
	.string "Un instant.$"

EventTicket_Text_ThatPass: @ 82A68D2
	.string "Le ferry allant à POIVRESSEL est…\p"
	.string "Oh?\n"
	.string "Ce PASSE…$"

EventTicket_Text_ShowEonTicket: @ 82A68FC
	.string "Hé, mon p'tit, c'est toi qui as apporté\n"
	.string "ce drôle de PASSE?\p"
	.string "J'vais t'dire, tu te diriges vers une\n"
	.string "île minuscule beaucoup plus au sud.\p"
	.string "Impossible de dire ce qui t'attend\n"
	.string "là-bas, mon p'tit.\p"
	.string "Ça me donne la chair de poule!\p"
	.string "Tout le monde à bord!$"

EventTicket_Text_SouthernIslandSailBack: @ 82A69F1
	.string "Dis, mon p'tit, y a absolument rien à voir\n"
	.string "sur cette île perdue.\p"
	.string "On retourne à NENUCRIQUE?$"

EventTicket_Text_SailHome: @ 82A6A5D
	.string "C'est d'accord, mon p'tit!\n"
	.string "On est partis!$"

EventTicket_Text_AsYouLike: @ 82A6A82
	.string "D'accord, mon p'tit, comme tu veux.$"

SouthernIsland_Interior_Text_Sign: @ 82A6AA1
	.string "“Les rêves ne sont qu'une autre\n"
	.string "réalité. Ne jamais l'oublier…”$"

SouthernIsland_Exterior_Text_Sign: @ 82A6AD5
	.string "“Ceux dont les souvenirs s'estompent\n"
	.string "cherchent à les graver dans leur cœur.”$"
