gText_082C843F:: @ 82C843F
	.string "C'est très décevant…$"

gText_082C8458:: @ 82C8458
	.string "D'accord, je vois…$"

gText_082C846C:: @ 82C846C
	.string "Je suis désolée…$"

gText_082C8480:: @ 82C8480
	.string "Merci…$"

gText_082C848B:: @ 82C848B
	.string "Tu n'as pas honte?\n"
	.string "Tout le monde nous regarde!$"

gText_082C84C1:: @ 82C84C1
	.string "Grr…\n"
	.string "Mais…$"

gText_082C84D0:: @ 82C84D0
	.string "Ce n'est pas pour rien qu'on m'appelle\n"
	.string "la STAR DU DOME!$"

gText_082C84F7:: @ 82C84F7
	.string "Ha, ha, ha!\n"
	.string "Tu m'amuses!$"

gText_082C8512:: @ 82C8512
	.string "On t'a donné une bonne leçon, non?$"

gText_082C853B:: @ 82C853B
	.string "Joli travail!\n"
	.string "Tu te débrouilles plutôt bien!$"

gText_082C8561:: @ 82C8561
	.string "Hé, hé, hé!\n"
	.string "C'est déjà fini?$"

gText_082C8589:: @ 82C8589
	.string "Je n'y crois pas…$"

gText_082C859D:: @ 82C859D
	.string "Oh, j'ai gagné…$"

gText_082C85A4:: @ 82C85A4
	.string "Oh, j'ai perdu…$"

gText_082C85A9:: @ 82C85A9
	.string "Oui!$"

gText_082C85AE:: @ 82C85AE
	.string "Grrr…$"

gText_082C85B4:: @ 82C85B4
	.string "Tu n'étais pas à fond!\n"
	.string "Tu dois te surpasser!$"

gText_082C85E3:: @ 82C85E3
	.string "Pas possible!\n"
	.string "Chapeau!$"

gText_082C85F5:: @ 82C85F5
	.string "Hé, hé!\n"
	.string "Mais qu'est-ce que tu espérais?$"

gText_082C8611:: @ 82C8611
	.string "Quoi?\n"
	.string "Mais c'est impossible…$"

gText_082C8628:: @ 82C8628
	.string "Tes POKéMON sont nuls!\n"
	.string "Et toi, tu es une mauviette!$"

gText_082C8662:: @ 82C8662
	.string "Ah…\n"
	.string "Je ne m'attendais pas à ça…$"

gText_082C8682:: @ 82C8682
	.string "Ha, ha, ha!\n"
	.string "Nous ne craignons personne!$"

gText_082C86B3:: @ 82C86B3
	.string "Non!\n"
	.string "Ahhhh!!!$"

gText_082C86C3:: @ 82C86C3
	.string "Hé, quel est ton problème?\n"
	.string "Un peu de nerf!$"

gText_082C86FE:: @ 82C86FE
	.string "Bravo! Tu as été superbe!\n"
	.string "Cette victoire, tu la mérites!$"

gText_082C8739:: @ 82C8739
	.string "Ne baisse pas les bras!\n"
	.string "Tu dois croire en toi!$"

gText_082C877B:: @ 82C877B
	.string "Tu as réussi!\n"
	.string "Tes efforts ont enfin payé!$"
