LilycoveCity_DepartmentStore_1F_Text_2A6390: @ 82A6390
	.string "Vous êtes à la LOTERIE POKéMON.\p"
	.string "Tous les clients du CENTRE COMMERCIAL\n"
	.string "peuvent retirer un BILLET DE LOTERIE\l"
	.string "POKéMON.\p"
	.string "Si le numéro sur le BILLET DE LOTERIE\n"
	.string "correspond au numéro ID d'un de vos\l"
	.string "POKéMON, vous recevrez un beau cadeau.\p"
	.string "Voulez-vous retirer un BILLET DE\n"
	.string "LOTERIE POKéMON?$"

LilycoveCity_DepartmentStore_1F_Text_2A6496: @ 82A6496
	.string "Revenez demain.$"

LilycoveCity_DepartmentStore_1F_Text_2A64B1: @ 82A64B1
	.string "A bientôt.$"

LilycoveCity_DepartmentStore_1F_Text_2A64C8: @ 82A64C8
	.string "Veuillez prendre un BILLET DE LOTERIE.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_2A650B: @ 82A650B
	.string "Le numéro du BILLET DE LOTERIE est\n"
	.string "{STR_VAR_1}.\p"
	.string "Je vais voir si ce numéro correspond\n"
	.string "à l'un des numéros ID de vos POKéMON.\p"
	.string "Veuillez patienter.$"

LilycoveCity_DepartmentStore_1F_Text_2A6592: @ 82A6592
	.string "Félicitations!\p"
	.string "Le numéro ID de {STR_VAR_1}, qui est\n"
	.string "dans votre équipe, correspond à celui\l"
	.string "du BILLET DE LOTERIE!$"

LilycoveCity_DepartmentStore_1F_Text_2A65E6: @ 82A65E6
	.string "Félicitations!\p"
	.string "Le numéro ID de {STR_VAR_1}, qui est\n"
	.string "stocké sur le PC, correspond à\l"
	.string "celui du BILLET DE LOTERIE!$"

LilycoveCity_DepartmentStore_1F_Text_2A663C: @ 82A663C
	.string "Quel dommage!\n"
	.string "Aucun des numéros ne correspond.$"

LilycoveCity_DepartmentStore_1F_Text_2A6664: @ 82A6664
	.string "Deux chiffres correspondent, vous\n"
	.string "remportez le troisième prix!\p"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_2A66A7: @ 82A66A7
	.string "Trois chiffres correspondent, vous\n"
	.string "remportez le deuxième prix!\p"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_2A66ED: @ 82A66ED
	.string "Quatre chiffres correspondent, vous\n"
	.string "remportez le premier prix!\p"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_2A6731: @ 82A6731
	.string "Magnifique, tous les chiffres\n"
	.string "correspondent!\p"
	.string "Vous avez gagné le super prix!\n"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_2A678C: @ 82A678C
	.string "Oh?\n"
	.string "On dirait que vous n'avez plus de place.\p"
	.string "Faites de la place dans votre SAC et\n"
	.string "revenez me voir.$"

LilycoveCity_DepartmentStore_1F_Text_2A67E1: @ 82A67E1
	.string "{PLAYER}?\n"
	.string "Oui, je vous attendais.\p"
	.string "Nous vous avons gardé votre prix.$"

LilycoveCity_DepartmentStore_1F_Text_2A6831: @ 82A6831
	.string "A bientôt.$"
