@ Only contains a portion of the mauville_man text. The rest is in scripts/mauville_man.inc
gText_SoPretty:: @ 8294295
	.string " vraiment bien!$"

gText_SoDarling:: @ 82942A1
	.string " vraiment adorable!$"

gText_SoRelaxed:: @ 82942AE
	.string " vraiment cool!$"

gText_SoSunny:: @ 82942BB
	.string " extraordinaire!$"

gText_SoDesirable:: @ 82942C6
	.string " vraiment fantastique!$"

gText_SoExciting:: @ 82942D5
	.string " vraiment super!$"

gText_SoAmusing:: @ 82942E3
	.string " vraiment drôle!$"

gText_SoMagical:: @ 82942F0
	.string " vraiment magique!$"

gOtherText_Is:: @ 82942FD
	.string " est$"

gOtherText_DontYouAgree:: @ 8294301
	.string "\n"
	.string "Tu es d'accord?$"

gMauvilleManText_ISoWantToGoOnAVacation:: @ 8294313
	.string "J'ai vraiment envie d'aller en vacances.\n"
	.string "Il y a un endroit sympa dans le coin?$"

gMauvilleManText_IBoughtCrayonsWith120Colors:: @ 8294359
	.string "J'ai acheté des crayons de 120 couleurs\n"
	.string "différentes! Ils sont pas beaux?$"

gMauvilleManText_WouldntItBeNiceIfWeCouldFloat:: @ 8294398
	.string "Ne serait-ce pas génial, si on pouvait\n"
	.string "s'envoler sur un nuage de bulles?$"

gMauvilleManText_WhenYouWriteOnASandyBeach:: @ 82943DA
	.string "Quand on écrit sur du sable, tout est\n"
	.string "effacé par les vagues. C'est triste.$"

gMauvilleManText_WhatsTheBottomOfTheSeaLike:: @ 829441C
	.string "J'aimerais aller voir les fonds marins!\n"
	.string "Ça doit être beau, tu crois pas?$"

gMauvilleManText_WhenYouSeeTheSettingSunDoesIt:: @ 8294460
	.string "Les couchers de soleil, ça donne envie\n"
	.string "de rentrer chez soi, non?$"

gMauvilleManText_LyingBackInTheGreenGrass:: @ 82944A0
	.string "S'allonger sur de l'herbe bien verte…\n"
	.string "Waouh, ça c'est super!$"

gMauvilleManText_SecretBasesAreSoWonderful:: @ 82944D5
	.string "Les BASES SECRETES, c'est génial!\n"
	.string "Non?$"
