Mevent_Text_FillOutQuestionnaire:: @ 827339F
	.string "Il y a un questionnaire…\n"
	.string "Voulez-vous y répondre?$"

Mevent_Text_QuestionnaireThankYou:: @ 82733D8
	.string "Merci d'avoir pris le temps de\n"
	.string "répondre à notre questionnaire.\p"
	.string "Vos réponses nous permettront\n"
	.string "de mieux vous servir.$"

Mevent_Text_YouKnowThoseWordsGift:: @ 8273446
	.string "Oh, bonjour!\n"
	.string "Vous connaissez ces mots?\p"
	.string "Donc vous devez aussi\n"
	.string "connaître le CADEAU MYST.\p"
	.string "A partir de maintenant, vous allez\n"
	.string "recevoir des CADEAUX MYST.!$"

Mevent_Text_YouCanAccessMysteryGift:: @ 82734CC
	.string "Après avoir sauvegardé, vous\n"
	.string "aurez accès aux CADEAUX MYST.!$"

Mevent_Text_YouKnowThoseWordsEvent:: @ 8273506
	.string "Oh, bonjour!\n"
	.string "Vous connaissez ces mots?\p"
	.string "Donc vous devez aussi\n"
	.string "connaître les EVENEMENTS MYSTERE.$"

Mevent_Text_YouCanAccessMysteryEvent:: @ 8273559
	.string "Après avoir sauvegardé, vous\n"
	.string "aurez accès aux EVENEMENTS MYSTERE.$"

Mevent_Text_TheresATicketForYou:: @ 8273594
	.string "Merci d'utiliser le système\n"
	.string "EVENEMENTS MYSTERE.\p"
	.string "Vous devez être {PLAYER}.\n"
	.string "Il y a un ticket pour vous.$"

Mevent_Text_TryUsingItAtLilycovePort:: @ 82735F2
	.string "Il peut être utilisé au port de\n"
	.string "NENUCRIQUE.\p"
	.string "Essayez-le pour voir de quoi \n"
	.string "il s'agit.$"
