gText_ObtainedTheItem:: @ 8272A78
	.string "Obtenu: {STR_VAR_2}!$"

gText_TheBagIsFull:: @ 8272A89
	.string "Le SAC est plein…$"

gText_PutItemInPocket:: @ 8272A9A
	.string "{PLAYER} met {STR_VAR_2} dans\n"
	.string "POCHE {STR_VAR_3} .$"

gText_PlayerFoundOneItem:: @ 8272ABF
	.string "{PLAYER} trouve {STR_VAR_2}!$"

gText_TooBadBagIsFull:: @ 8272AD0
	.string "Dommage!\n"
	.string "Le SAC est plein…$"

gText_PlayerPutItemInBag:: @ 8272AEA
	.string "{PLAYER} met {STR_VAR_2} dans\n"
	.string "le SAC.$"

gText_ObtainedTheDecor:: @ 8272B09
	.string "Obtenu: {STR_VAR_2}!$"

gText_NoRoomLeftForAnother:: @ 8272B1A
	.string "Dommage! Il n'y a plus assez de place\n"
	.string "pour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC:: @ 8272B48
	.string "Transfert de {STR_VAR_2} sur le PC.$"
