Text_BootUpPC: @ 827265A
	.string "{PLAYER} allume le PC.$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "Accéder à quel PC?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "PC de ??? connecté.$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Gestion de Stocks de POKéMON en ligne.$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "PC personnel connecté.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "PC d'ANNETTE connecté.$"
