gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2} a été transféré sur le\n"
	.string "PC de ???.\p"
	.string "Il a été placé dans la BOITE\n"
	.string "appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC:: @ 8273256
	.string "{STR_VAR_2} a été transféré sur le\n"
	.string "PC d'ANNETTE.\p"
	.string "Il a été placé dans la BOITE\n"
	.string "appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull:: @ 8273296
	.string "La BOITE {STR_VAR_3} sur le PC\n"
	.string "de ??? est pleine.\p"
	.string "{STR_VAR_2} a été placé dans la\n"
	.string "BOITE appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull:: @ 82732D9
	.string "La BOITE “{STR_VAR_3}” sur le PC\n"
	.string "d'ANNETTE est pleine.\p"
	.string "{STR_VAR_2} a été placé dans la\n"
	.string "BOITE appelée “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "Il n'y a plus de place pour\n"
	.string "les POKéMON.\p"
	.string "Les BOITES sont pleines et\n"
	.string "ne peuvent plus rien recevoir.$"

gText_NicknameThisPokemon:: @ 8273374
	.string "Voulez-vous donner un surnom\n"
	.string "à {STR_VAR_1}?$"
