gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
	.string "Bonjour! Bienvenue au CENTRE\n"
	.string "POKéMON.\p"
	.string "Nous pouvons soigner vos POKéMON.\p"
	.string "Voulez-vous les soigner?$"

gText_IllTakeYourPkmn:: @ 8272768
	.string "OK, je prends vos POKéMON un instant.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
	.string "Merci d'avoir attendu.\p"
	.string "Vos POKéMON sont en super\n"
	.string "forme.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
	.string "A une prochaine fois peut-être!$"

gText_WelcomeCutShort:: @ 82727F5
	.string "Bonjour! Bienvenue au CENTRE\n"
	.string "POKéMON.\p"
	.string "Nous pouvons soigner vos POKéMON.\p"
	.string "Voulez-vous les…$"

gText_NoticesGoldCard:: @ 8272860
	.string "Ce… Cette carte…\n"
	.string "Serait-ce la CARTE OR?!\p"
	.string "Oh, ce jaune or est si brillant!\n"
	.string "Les quatre étoiles étincellent presque!\p"
	.string "J'ai déjà vu des DRESSEURS avec\n"
	.string "des CARTES ARGENT, mais…\p"
	.string "Vous êtes le premier DRESSEUR que je\n"
	.string "vois avec une CARTE OR!\p"
	.string "Accordez-moi l'honneur de soigner\n"
	.string "vos POKéMON un instant!$"

gText_YouWantTheUsual:: @ 8272982
	.string "Contente de vous voir, {PLAYER}!\n"
	.string "On fait comme d'habitude?$"

gText_IllTakeYourPkmn2:: @ 82729C0
	.string "OK, je prends vos POKéMON un instant.$"

gText_ThankYouForWaiting:: @ 82729F0
	.string "Merci d'avoir attendu.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
	.string "Encore merci et à bientôt!$"
