	.align 2
gText_ConfirmSave:: @ 82C87B4
	.string "Voulez-vous sauvegarder la partie?$"

gText_AlreadySavedFile:: @ 82C87D5
	.string "Il y a déjà une partie sauvegardée.\n"
	.string "Voulez-vous la remplacer?$"

gText_SavingDontTurnOff:: @ 82C8810
	.string "SAUVEGARDE EN COURS…\n"
	.string "N'ETEIGNEZ PAS LA CONSOLE.$"

gText_PlayerSavedGame:: @ 82C8832
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile:: @ 82C8845
	.string "Une partie différente est déjà\n"
	.string "sauvegardée.\p"
	.string "Voulez-vous la remplacer?$"

gText_SaveError:: @ 82C892A
	.string "Erreur de sauvegarde.\p"
	.string "Changer la mémoire de sauvegarde.$"

gText_SavingDontTurnOffPower:: @ 82C8959
	.string "SAUVEGARDE EN COURS…\n"
	.string "NE PAS ETEINDRE.$"
