SecretBase_Text_Trainer0PreBattle: @ 82748A0
	.string "Tu as déjà créé une BASE SECRETE?\p"
	.string "J'ai parcouru le monde avant de choisir\n"
	.string "cet endroit.\p"
	.string "Puisque tu es ici, qu'est-ce que tu\n"
	.string "dirais d'un petit combat?$"

SecretBase_Text_Trainer0AcceptBattle: @ 8274939
	.string "OK!\n"
	.string "C'est parti!$"

SecretBase_Text_Trainer0DeclineBattle: @ 827494D
	.string "Hein?\n"
	.string "Oh, tu n'as pas le temps, maintenant…$"

SecretBase_Text_Trainer0Defeated:: @ 8274966
	.string "Ouaaarg! Tu es trop balèze!\n"
	.string "Heu, ne parle de ma défaite à personne!$"

SecretBase_Text_Trainer0PostBattle: @ 82749AA
	.string "Qu'est-ce que tu penses de ma BASE\n"
	.string "SECRETE? Reviens me voir demain.$"

SecretBase_Text_Trainer0PreChampion: @ 82749ED
	.string "Tu as déjà créé une BASE SECRETE?\p"
	.string "J'ai parcouru le monde avant de choisir\n"
	.string "cet endroit.\p"
	.string "Tu peux y venir quand tu veux!$"

SecretBase_Text_Trainer5PreBattle: @ 8274A64
	.string "Tu peux faire une BASE SECRETE dans de\n"
	.string "nombreux endroits.\p"
	.string "Mais cet endroit est mon préféré.\n"
	.string "Il est cool, non?\p"
	.string "Oh, ça te dirait, un petit combat?$"

SecretBase_Text_Trainer5AcceptBattle: @ 8274AFA
	.string "OK, c'est parti!$"

SecretBase_Text_Trainer5DeclineBattle: @ 8274B0B
	.string "Oh… Tu n'as pas le temps, maintenant?\n"
	.string "Tant pis.$"

SecretBase_Text_Trainer5Defeated:: @ 8274B24
	.string "Humm… Une défaite…\n"
	.string "N'en parle à personne!\p"
	.string "Motus et bouche cousue!$"

SecretBase_Text_Trainer5PostBattle: @ 8274B6C
	.string "Si tu repasses dans le coin,\n"
	.string "j'espère que tu me rendras visite.$"

SecretBase_Text_Trainer5PreChampion: @ 8274BA2
	.string "Tu peux faire une BASE SECRETE dans de\n"
	.string "nombreux endroits.\p"
	.string "Mais cet endroit est mon préféré.\n"
	.string "Il est cool, non?$"

SecretBase_Text_Trainer1PreBattle: @ 8274C13
	.string "Cet endroit est très apprécié.\n"
	.string "Il est toujours occupé par quelqu'un.\p"
	.string "Oh! Tu pensais occuper cet endroit\n"
	.string "aussi?\p"
	.string "Dans ce cas, si tu parviens à me battre,\n"
	.string "je te le laisserai.$"

SecretBase_Text_Trainer1AcceptBattle: @ 8274CB0
	.string "OK!\n"
	.string "Je vais défendre ma BASE SECRETE!$"

SecretBase_Text_Trainer1DeclineBattle: @ 8274CDA
	.string "Quoi? C'est vrai?\n"
	.string "Cet endroit ne t'intéresse pas?$"

SecretBase_Text_Trainer1Defeated:: @ 8274D13
	.string "Je n'en peux plus!\n"
	.string "Je me rends!$"

SecretBase_Text_Trainer1PostBattle: @ 8274D34
	.string "OK, quand je partirai d'ici, tu pourras\n"
	.string "prendre possession de l'endroit!$"

SecretBase_Text_Trainer1PreChampion: @ 8274D69
	.string "Cet endroit est très apprécié.\n"
	.string "Il est toujours occupé par quelqu'un.\p"
	.string "J'ai dû attendre longtemps avant d'y\n"
	.string "entrer. Finalement, j'ai réussi!$"

SecretBase_Text_Trainer6PreBattle: @ 8274DD2
	.string "Bienvenue dans mon LABO POKéMON.\p"
	.string "J'étudie secrètement les méthodes de\n"
	.string "combat.\p"
	.string "Tu veux voir comme je suis forte?$"

SecretBase_Text_Trainer6AcceptBattle: @ 8274E41
	.string "Je vais me donner à fond!$"

SecretBase_Text_Trainer6DeclineBattle: @ 8274E5A
	.string "Oh.\n"
	.string "Tant pis. Ce sera pour une autre fois!$"

SecretBase_Text_Trainer6Defeated:: @ 8274E75
	.string "Hum… J'ai encore beaucoup à apprendre.\n"
	.string "Je vais continuer mes recherches.$"

SecretBase_Text_Trainer6PostBattle: @ 8274EB3
	.string "Merci d'avoir accepté ce combat.\n"
	.string "Reviens me voir demain.$"

SecretBase_Text_Trainer6PreChampion: @ 8274EF1
	.string "Bienvenue dans mon LABO POKéMON.\p"
	.string "J'étudie secrètement les méthodes de\n"
	.string "combat.$"

SecretBase_Text_Trainer2PreBattle: @ 8274F39
	.string "C'est sympa d'avoir un grand manoir,\n"
	.string "mais je préfère cet endroit.\p"
	.string "Je l'aime bien, car des gens de tous\n"
	.string "les horizons viennent me rendre visite.\p"
	.string "A part ça, que dirais-tu d'un combat?$"

SecretBase_Text_Trainer2AcceptBattle: @ 8274FCA
	.string "Excellent!$"

SecretBase_Text_Trainer2DeclineBattle: @ 8274FDA
	.string "Préviens-moi quand tu voudras!$"

SecretBase_Text_Trainer2Defeated:: @ 8274FFE
	.string "Pfffou! Je suis épuisé!\n"
	.string "Mais c'est toujours marrant, un combat!$"

SecretBase_Text_Trainer2PostBattle: @ 827502A
	.string "Quoi qu'il en soit, je dois aller acheter\n"
	.string "des meubles et des décorations.\p"
	.string "Je veux que les gens se sentent\n"
	.string "bien dans ma BASE SECRETE.$"

SecretBase_Text_Trainer2PreChampion: @ 82750A4
	.string "C'est sympa d'avoir un grand manoir,\n"
	.string "mais je préfère cet endroit.\p"
	.string "Je l'aime bien, car des gens de tous\n"
	.string "les horizons viennent me rendre visite.$"

SecretBase_Text_Trainer7PreBattle: @ 8275114
	.string "J'adore faire du shopping pour trouver\n"
	.string "des meubles et des décorations.\p"
	.string "Mais j'aime bien aussi élever\n"
	.string "des POKéMON.\p"
	.string "Tu as l'air sympa. Tu veux te battre\n"
	.string "contre mes POKéMON et moi?$"

SecretBase_Text_Trainer7AcceptBattle: @ 82751AF
	.string "Cool.\n"
	.string "On commence?$"

SecretBase_Text_Trainer7DeclineBattle: @ 82751CA
	.string "Oh.\n"
	.string "Je suis terriblement déçue…$"

SecretBase_Text_Trainer7Defeated:: @ 82751E1
	.string "J'abandonne…$"

SecretBase_Text_Trainer7PostBattle: @ 82751EC
	.string "C'était super marrant! Je vais aller\n"
	.string "faire du shopping maintenant.$"

SecretBase_Text_Trainer7PreChampion: @ 8275226
	.string "J'adore faire du shopping pour trouver\n"
	.string "des meubles et des décorations.\p"
	.string "Mais j'aime bien aussi élever\n"
	.string "des POKéMON.$"

SecretBase_Text_Trainer3PreBattle: @ 8275287
	.string "Certaines personnes font leur BASE\n"
	.string "SECRETE dans des endroits bien cachés.\l"
	.string "Est-ce qu'ils veulent éviter de se\l"
	.string "faire remarquer?\p"
	.string "Bon, puisque tu m'as trouvé, qu'est-ce\n"
	.string "que tu dirais d'un combat?$"

SecretBase_Text_Trainer3AcceptBattle: @ 8275315
	.string "Je vais te donner du fil à retordre!$"

SecretBase_Text_Trainer3DeclineBattle: @ 8275330
	.string "Oh… Tu as sûrement fait beaucoup\n"
	.string "d'efforts pour trouver cet endroit.$"

SecretBase_Text_Trainer3Defeated:: @ 8275367
	.string "Je me suis étalé…$"

SecretBase_Text_Trainer3PostBattle: @ 8275374
	.string "Où est ta BASE SECRETE?\n"
	.string "Je viendrai te rendre visite.$"

SecretBase_Text_Trainer3PreChampion: @ 82753AB
	.string "Certaines personnes font leur BASE\n"
	.string "SECRETE dans des endroits bien cachés.\p"
	.string "Est-ce qu'ils veulent éviter de se\n"
	.string "faire remarquer?$"

SecretBase_Text_Trainer8PreBattle: @ 8275405
	.string "On m'a dit qu'il y avait plusieurs façons\n"
	.string "d'obtenir des décorations.\p"
	.string "On devrait faire un concours et voir\n"
	.string "qui aura les plus belles décorations!\p"
	.string "En attendant, ça te tente un combat?$"

SecretBase_Text_Trainer8AcceptBattle: @ 82754B2
	.string "Nous sommes dans ma BASE SECRETE.\n"
	.string "Je ne peux pas perdre!$"

SecretBase_Text_Trainer8DeclineBattle: @ 82754D8
	.string "Quand tu voudras, alors!$"

SecretBase_Text_Trainer8Defeated:: @ 82754F6
	.string "Quoi?\n"
	.string "J'ai perdu, là?$"

SecretBase_Text_Trainer8PostBattle: @ 827550C
	.string "Je me rattraperai sur les décorations.\n"
	.string "Reviens me faire un petit coucou!$"

SecretBase_Text_Trainer8PreChampion: @ 8275546
	.string "On m'a dit qu'il y avait plusieurs façons\n"
	.string "d'obtenir des décorations.\p"
	.string "On devrait faire un concours et voir\n"
	.string "qui aura les plus belles décorations!$"

SecretBase_Text_Trainer4PreBattle: @ 82755D2
	.string "J'ai trouvé un endroit qui me plaisait et\n"
	.string "je l'ai décoré avec mes objets préférés.\p"
	.string "En plus, j'élève mon POKéMON préféré.\n"
	.string "Grâce à lui, je suis plus fort.\p"
	.string "C'est mon passe-temps préféré.\n"
	.string "Tu veux te battre contre moi?$"

SecretBase_Text_Trainer4AcceptBattle: @ 8275679
	.string "Montre-moi de quoi tu es capable!$"

SecretBase_Text_Trainer4DeclineBattle: @ 8275696
	.string "Je suppose que tu n'as pas toujours\n"
	.string "envie de te battre.$"

SecretBase_Text_Trainer4Defeated:: @ 82756C7
	.string "OK, je sais de quoi tu es capable.\n"
	.string "Pas la peine d'insister!$"

SecretBase_Text_Trainer4PostBattle: @ 82756EF
	.string "On pourrait tous les deux devenir plus\n"
	.string "forts. Continuons à nous entraîner!$"

SecretBase_Text_Trainer4PreChampion: @ 827571E
	.string "J'ai trouvé un endroit qui me plaisait et\n"
	.string "je l'ai décoré avec mes objets préférés.\p"
	.string "En plus, j'élève mon POKéMON préféré.\n"
	.string "Grâce à lui, je suis plus fort.\p"
	.string "Chaque jour est une aventure.$"

SecretBase_Text_Trainer9PreBattle: @ 82757B5
	.string "Tu peux en apprendre beaucoup sur les\n"
	.string "goûts des autres en regardant leurs\l"
	.string "décorations et la façon dont elles\l"
	.string "sont disposées.\p"
	.string "Qu'est-ce que tu penses de mes goûts?\n"
	.string "Tu restes sans voix, hein?\p"
	.string "Tu veux connaître mes goûts\n"
	.string "en matière de combat?$"

SecretBase_Text_Trainer9AcceptBattle: @ 8275884
	.string "Il est trop tard pour reculer\n"
	.string "maintenant!$"

SecretBase_Text_Trainer9DeclineBattle: @ 827589D
	.string "Je peux te faire une démonstration\n"
	.string "de mon style quand tu veux.$"

SecretBase_Text_Trainer9Defeated:: @ 82758CC
	.string "Quel talent formidable!\n"
	.string "Ton pouvoir semble sans limites…$"

SecretBase_Text_Trainer9PostBattle: @ 8275909
	.string "Alors, qu'est-ce que tu as pensé de\n"
	.string "mon style? Je vais encore le peaufiner!$"

SecretBase_Text_Trainer9PreChampion: @ 8275944
	.string "Tu peux en apprendre beaucoup sur les\n"
	.string "goûts des autres en regardant leurs\l"
	.string "décorations et la façon dont elles\l"
	.string "sont disposées.\p"
	.string "Qu'est-ce que tu penses de mes goûts?\n"
	.string "Tu restes sans voix, hein?$"
