Route102_Text_CalvinIntro: @ 8294513
	.string "Si tu as un POKéMON avec toi, alors\n"
	.string "tu es officiellement un DRESSEUR\l"
	.string "de POKéMON!\p"
	.string "Tu ne peux pas refuser mon défi!$"

Route102_Text_CalvinDefeated: @ 829457C
	.string "Grrrr, j'ai perdu… J'aurais dû davantage\n"
	.string "entraîner mon POKéMON…$"

Route102_Text_CalvinPostBattle: @ 82945AC
	.string "Ecoute, toi. T'aurais pu me le dire\n"
	.string "avant, que tu avais un tel niveau!$"

Route102_Text_CalvinRegister: @ 82945EB
	.string "Je me suis beaucoup entraîné depuis\n"
	.string "notre dernière rencontre.\p"
	.string "J'aimerais t'affronter de nouveau,\n"
	.string "tu m'enregistres dans ton POKéNAV?$"

Route102_Text_CalvinRegisterShort: @ 8294668
	.string "J'aimerais t'affronter de nouveau,\n"
	.string "tu m'enregistres dans ton POKéNAV?$"

Route102_Text_CalvinRematchIntro: @ 82946AE
	.string "Depuis que j'ai perdu contre toi, je n'ai\n"
	.string "pas cessé de m'entraîner.\p"
	.string "Tu ne peux pas refuser mon défi!$"

Route102_Text_CalvinRematchDefeated: @ 829470C
	.string "Grrrr, j'ai perdu…\n"
	.string "Mon entraînement est-il mauvais?$"

Route102_Text_CalvinRematchPostBattle: @ 829473C
	.string "Si tu t'améliores, je m'améliorerai aussi.$"

Route102_Text_AllenIntro: @ 8294775
	.string "Tu viens juste de devenir DRESSEUR?\n"
	.string "On est tous les deux des débutants!$"

Route102_Text_AllenDefeated: @ 82947AA
	.string "Je voulais me mesurer à toi parce que\n"
	.string "je pensais pouvoir te battre…$"

Route102_Text_AllenPostBattle: @ 82947DB
	.string "Je n'ai même pas gagné une seule fois…\n"
	.string "J'espère que je vais bientôt y arriver…$"

Route102_Text_RickIntro: @ 829480C
	.string "Ah, ah! Nos regards se sont croisés!\n"
	.string "Bats-toi contre mes POKéMON INSECTE!$"

Route102_Text_RickDefeated: @ 8294847
	.string "Hou! Je suis hors d'état de combattre!$"

Route102_Text_RickPostBattle: @ 8294859
	.string "Si tu fixes ton regard sur un DRESSEUR,\n"
	.string "tu dois l'affronter! C'est la règle!$"

Route102_Text_TianaIntro: @ 829489E
	.string "Je vais continuer à gagner pour\n"
	.string "devenir le meilleur DRESSEUR.\p"
	.string "Fais-moi avancer dans ma carrière!$"

Route102_Text_TianaDefeated: @ 82948F3
	.string "En fait, c'est moi qui contribue à faire\n"
	.string "avancer ta carrière…$"

Route102_Text_TianaPostBattle: @ 8294916
	.string "Pour prendre le chemin de la victoire,\n"
	.string "je vais devoir attraper plus de\l"
	.string "POKéMON.$"

Route103_Text_DaisyIntro: @ 829495A
	.string "Ne sens-tu pas le parfum de la défaite?$"

Route103_Text_DaisyDefeated: @ 829498F
	.string "Tu n'as pas laissé notre parfum\n"
	.string "te distraire…$"

Route103_Text_DaisyPostBattle: @ 82949B4
	.string "L'aromathérapie utilise les parfums\n"
	.string "pour soigner des troubles psychiques.$"

Route103_Text_AmyIntro: @ 82949F9
	.string "EVE: Je suis EVE.\n"
	.string "Et voici ma petite sœur, AWA.\p"
	.string "On combat ensemble!$"

Route103_Text_AmyDefeated: @ 8294A3D
	.string "EVE: Oooh, on a perdu.$"

Route103_Text_AmyPostBattle: @ 8294A52
	.string "EVE: Il faut penser à tout un tas\n"
	.string "de choses quand tu te bats contre deux\l"
	.string "DRESSEURS.$"

Route103_Text_AmyNotEnoughPokemon: @ 8294AAE
	.string "EVE: Oh, tu n'as qu'un seul POKéMON\n"
	.string "avec toi.\l"
	.string "Tu ne vas pas pouvoir nous affronter.$"

Route103_Text_LivIntro: @ 8294AFD
	.string "AWA: On se bat ensemble, comme une\n"
	.string "équipe.$"

Route103_Text_LivDefeated: @ 8294B22
	.string "AWA: Oh, on a perdu, grande sœur…$"

Route103_Text_LivPostBattle: @ 8294B40
	.string "AWA: On fonctionne très bien\n"
	.string "ensemble, ma grande sœur et moi…\p"
	.string "Mais on a quand même perdu…$"

Route103_Text_AmyLivRegister: @ 8294B8A
	.string "AWA: Nous sommes bien meilleures…\n"
	.string "C'est vrai, on te montrera une\l"
	.string "prochaine fois!$"

Route103_Text_LivNotEnoughPokemon: @ 8294BD0
	.string "AWA: Si tu veux te battre contre\n"
	.string "nous, il faut que tu aies deux POKéMON!\l"
	.string "Sinon, ce ne serait pas juste!$"

Route103_Text_AmyRematchIntro: @ 8294C29
	.string "EVE: Je suis EVE.\n"
	.string "Et voici ma petite sœur, AWA.\p"
	.string "On combat ensemble!$"

Route103_Text_AmyRematchDefeated: @ 8294C6D
	.string "EVE: Ah, bouhou!\n"
	.string "On n'a toujours pas réussi à gagner…$"

Route103_Text_AmyRematchPostBattle: @ 8294C93
	.string "EVE: Il faut penser à tout un tas\n"
	.string "de choses quand tu te bats contre deux\l"
	.string "DRESSEURS.$"

Route103_Text_AmyRematchNotEnoughPokemon: @ 8294CEF
	.string "EVE: Oh, tu n'as qu'un seul POKéMON\n"
	.string "avec toi.\l"
	.string "Tu ne vas pas pouvoir nous affronter.$"

Route103_Text_LivRematchIntro: @ 8294D3E
	.string "AWA: On se bat ensemble, comme une\n"
	.string "équipe.$"

Route103_Text_LivRematchDefeated: @ 8294D63
	.string "AWA: Arrrg, on a encore perdu…\n"
	.string "Grande sœur…$"

Route103_Text_LivRematchPostBattle: @ 8294D89
	.string "AWA: On fonctionne très bien\n"
	.string "ensemble, ma grande sœur et moi…\p"
	.string "Mais pourquoi a-t-on encore perdu?$"

Route103_Text_LivRematchNotEnoughPokemon: @ 8294DDB
	.string "AWA: Si tu veux te battre contre\n"
	.string "nous, il faut que tu aies deux POKéMON!\l"
	.string "Sinon, ce ne serait pas juste!$"

Route103_Text_AndrewIntro: @ 8294E34
	.string "Arrg! Ma ligne est emmêlée!\n"
	.string "Ça m'énerve et ça me rend agressif!\p"
	.string "Allez! Viens te battre!$"

Route103_Text_AndrewDefeated: @ 8294E92
	.string "Ah! Perdu!\n"
	.string "Je suis encore plus énervé maintenant!$"

Route103_Text_AndrewPostBattle: @ 8294EBB
	.string "Ah, je vais devenir fou…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro: @ 8294EDF
	.string "Mon POKéMON est tellement adorable!\n"
	.string "Ne sois pas timide. J'te l'montre!$"

Route103_Text_MiguelDefeated: @ 8294F21
	.string "Oh, ça alors!\n"
	.string "Mon POKéMON chéri!$"

Route103_Text_MiguelPostBattle: @ 8294F42
	.string "Mon POKéMON chéri est à croquer,\n"
	.string "même quand il est K.O.!$"

Route103_Text_MiguelRegister: @ 8294F7E
	.string "Il faudra que tu viennes pour voir mes\n"
	.string "adorables POKéMON!$"

Route103_Text_MiguelRematchIntro: @ 8294FC3
	.string "Salut, toi! Mon adorable POKéMON est\n"
	.string "vraiment à croquer. De plus en plus!$"

Route103_Text_MiguelRematchDefeated: @ 8295006
	.string "Oh!\n"
	.string "Mon POKéMON chéri!$"

Route103_Text_MiguelRematchPostBattle: @ 829501E
	.string "Plus je passe de temps avec mon\n"
	.string "POKéMON et plus il est adorable.$"

Route103_Text_PeteIntro: @ 8295063
	.string "Pour une si petite distance…\n"
	.string "Rien de mieux que la nage…$"

Route103_Text_PeteDefeated: @ 8295093
	.string "Bloub!$"

Route103_Text_PetePostBattle: @ 82950AA
	.string "Oh, je comprends d'où tu viens\n"
	.string "maintenant.\p"
	.string "Si j'avais un POKéMON en qui je puisse\n"
	.string "avoir confiance, je l'utiliserais aussi\l"
	.string "avec SURF.$"

Route103_Text_IsabelleIntro: @ 8295116
	.string "Regarde où tu vas! On a failli se rentrer\n"
	.string "dedans!$"

Route103_Text_IsabelleDefeated: @ 8295146
	.string "Méeuh…$"

Route103_Text_IsabellePostBattle: @ 829514D
	.string "Je ne suis pas très bonne, alors je\n"
	.string "m'entraîne à la nage…\p"
	.string "Désolée, j'ai failli te rentrer dedans.$"

Route103_Text_RhettIntro: @ 8295199
	.string "On est un peu à l'étroit ici.$"

Route103_Text_RhettDefeated: @ 82951C6
	.string "Tu te débrouilles bien pour ton âge!$"

Route103_Text_RhettPostBattle: @ 82951DE
	.string "Tu aimes bien les petits endroits\n"
	.string "comme ça?$"

Route103_Text_MarcosIntro: @ 8295206
	.string "Je vais t'électriser avec mon\n"
	.string "solo de guitare!$"

Route103_Text_MarcosDefeated: @ 829522B
	.string "Ma carrière est fichue!$"

Route103_Text_MarcosPostBattle: @ 8295246
	.string "Je jouais de la guitare un peu à l'écart\n"
	.string "et soudain, je me suis retrouvé entouré\l"
	.string "de fans.\p"
	.string "Hé, peut-être que je devrais faire\n"
	.string "carrière!$"

Route104_Text_2952BB: @ 82952BB
	.string "GINA: D'accord, on n'a qu'à se battre\n"
	.string "avec nos POKéMON!$"

Route104_Text_2952E6: @ 82952E6
	.string "GINA: Ça m'embête de perdre!$"

Route104_Text_2952FE: @ 82952FE
	.string "GINA: On n'a pas le niveau!\n"
	.string "Il va falloir qu'on s'entraîne bien plus!$"

Route104_Text_295330: @ 8295330
	.string "GINA: Oh? Un seul POKéMON?\n"
	.string "Alors on ne se bat pas contre toi.\p"
	.string "Avec un seul POKéMON, ça va pas \n"
	.string "l'faire. C'est pas cool.$"

Route104_Text_2953AF: @ 82953AF
	.string "MIA: On est jumelles, alors on\n"
	.string "combat ensemble.$"

Route104_Text_2953E1: @ 82953E1
	.string "MIA: On s'est battues ensemble et\n"
	.string "on a perdu toutes les deux…$"

Route104_Text_29540D: @ 829540D
	.string "MIA: On va davantage entraîner nos\n"
	.string "POKéMON pour être aussi fortes que toi.$"

Route104_Text_295449: @ 8295449
	.string "MIA: Tu veux te mesurer à nous?\p"
	.string "On te dira non et non, si tu n'as pas\n"
	.string "deux POKéMON avec toi.\p"
	.string "On est trop fortes pour toi!$"

Route104_Text_2954BD: @ 82954BD
	.string "Pourquoi en faire un secret?\n"
	.string "Je suis l'expert en POKéMON EAU!\p"
	.string "Hum?\n"
	.string "Tu ne me connais pas?$"

Route104_Text_295509: @ 8295509
	.string "Je pensais ne pas être trop mauvais,\n"
	.string "mais je suppose que si… Fffff…$"

Route104_Text_29554E: @ 829554E
	.string "J'étais si occupé à pêcher que j'en ai \n"
	.string "oublié de dresser mes POKéMON.$"

Route104_Text_29558A: @ 829558A
	.string "C'est trop cool de laisser des traces\n"
	.string "de pas sur le sable!$"

Route104_Text_2955B4: @ 82955B4
	.string "Waah! J'ai du sable dans mes\n"
	.string "chaussures! Elles sont dégoûtantes!$"

Route104_Text_2955E8: @ 82955E8
	.string "Je veux laisser les traces de mes pas\n"
	.string "partout sur le sable, mais elles\l"
	.string "disparaissent aussitôt…$"

Route104_Text_29563A: @ 829563A
	.string "Je devrais peut-être…\n"
	.string "Ou peut-être pas…\p"
	.string "Oui, c'est décidé, je me bats!$"

Route104_Text_29566F: @ 829566F
	.string "Je n'aurais pas dû me battre…$"

Route104_Text_295689: @ 8295689
	.string "Si tu dois prendre une décision et que\n"
	.string "tu laisses quelqu'un d'autre la prendre\l"
	.string "à ta place, tu le regretteras de toute\l"
	.string "façon, quoi qu'il arrive.$"

Route104_Text_2956FF: @ 82956FF
	.string "Tu sais te battre, mais est-ce que\n"
	.string "je devrais t'inscrire dans mon POKéNAV?\p"
	.string "Je suis pas trop sûre…\p"
	.string "Je plaisante! Bien sûr que je vais\n"
	.string "t'enregistrer!$"

Route104_Text_29576B: @ 829576B
	.string "Tu sais te battre, mais est-ce que\n"
	.string "je devrais t'inscrire dans mon POKéNAV?\p"
	.string "Je suis pas trop sûre…\p"
	.string "Je plaisante! Bien sûr que je vais\n"
	.string "t'enregistrer!$"

Route104_Text_2957D7: @ 82957D7
	.string "Viens te battre!$"

Route104_Text_2957F0: @ 82957F0
	.string "Oooh…\n"
	.string "Je pensais pouvoir gagner…$"

Route104_Text_29580C: @ 829580C
	.string "J'ai fait le choix de me battre, alors je\n"
	.string "dois accepter la défaite avec élégance.\p"
	.string "Je suis quand même triste d'avoir perdu.$"

Route104_Text_295870: @ 8295870
	.string "Oh, oui, je relève le défi.\n"
	.string "J'ai beaucoup d'argent.$"

Route104_Text_2958AD: @ 82958AD
	.string "Pourquoi n'ai-je pas réussi à gagner?$"

Route104_Text_2958C1: @ 82958C1
	.string "S'il y a bien une chose que l'argent ne\n"
	.string "peut acheter, ce sont les POKéMON…$"

Route104_Text_2958F8: @ 82958F8
	.string "Hmm?\n"
	.string "Tu as obtenu un POKéNAV.\p"
	.string "Tu veux de l'argent pour que je puisse\n"
	.string "t'enregistrer dans mon POKéNAV?$"

Route104_Text_29595A: @ 829595A
	.string "Hmm?\n"
	.string "Tu as obtenu un POKéNAV.\p"
	.string "Tu veux de l'argent pour que je puisse\n"
	.string "t'enregistrer dans mon POKéNAV?$"

Route104_Text_2959BC: @ 82959BC
	.string "Après ma défaite contre toi, j'ai appris\n"
	.string "un tas de choses sur les POKéMON.$"

Route104_Text_2959FC: @ 82959FC
	.string "J'ai encore perdu?\n"
	.string "Pourquoi je n'ai pas réussi à gagner?$"

Route104_Text_295A1E: @ 8295A1E
	.string "Je suis riche et cependant, je ne semble\n"
	.string "pas pouvoir gagner avec les POKéMON…\p"
	.string "Le monde des POKéMON est mystérieux…$"

Route104_Text_295A7E: @ 8295A7E
	.string "Le destin nous a fait nous rencontrer.\n"
	.string "Accepterais-tu un petit combat?$"

Route104_Text_295ABB: @ 8295ABB
	.string "Oh, ça alors!$"

Route104_Text_295AC3: @ 8295AC3
	.string "“Bonjour” est le début\n"
	.string "d'“au revoir”.\p"
	.string "J'espère qu'on se reverra.$"

Route104_Text_295B01: @ 8295B01
	.string "Salut, contente de te revoir.\p"
	.string "C'est le destin qui nous fait nous\n"
	.string "rencontrer de nouveau. On devrait\l"
	.string "s'enregistrer dans nos POKéNAVS.$"

Route104_Text_295B60: @ 8295B60
	.string "On devrait fêter ces retrouvailles!\p"
	.string "Enregistrons nos numéros dans\n"
	.string "nos POKéNAVS.$"

Route104_Text_295BC8: @ 8295BC8
	.string "Salut! Comme on se retrouve!\n"
	.string "Que dirais-tu d'un petit combat?$"

Route104_Text_295BFA: @ 8295BFA
	.string "Oh, non…\n"
	.string "J'ai fait du mieux que j'pouvais…$"

Route104_Text_295C1F: @ 8295C1F
	.string "“Bonjour” est le début\n"
	.string "d'“au revoir”.\p"
	.string "J'espère qu'on se reverra.$"

Route104_Text_295C5D: @ 8295C5D
	.string "J'ai attrapé ce POKéMON qui a\n"
	.string "l'air super fort!\p"
	.string "Il y a un je ne sais quoi de magique\n"
	.string "chez lui!\p"
	.string "Je suis sûr qu'il est très fort, ouaip!$"

Route104_Text_295CC9: @ 8295CC9
	.string "Que…$"

Route104_Text_295CD3: @ 8295CD3
	.string "Hé, MAGICARPE, on ne peut pas vraiment\n"
	.string "dire que tu mérites ton nom!$"

Route105_Text_FosterIntro: @ 8295D0F
	.string "On raconte qu'il y a une pierre\n"
	.string "mystérieuse par ici.\l"
	.string "Tu sais quelque chose là-dessus?$"

Route105_Text_FosterDefeated: @ 8295D62
	.string "J'étais si préoccupé par cette pierre\n"
	.string "que mes POKéMON sont restés faibles…$"

Route105_Text_FosterPostBattle: @ 8295DAB
	.string "Je peux rester des heures à contempler\n"
	.string "une belle pierre sans m'en lasser.$"

Route105_Text_LuisIntro: @ 8295DF5
	.string "Ouf! En te voyant, j'ai eu peur que ce\n"
	.string "soit un enfant en train de se noyer.\p"
	.string "Mais ça a l'air d'aller, alors que\n"
	.string "dirais-tu de te battre?$"

Route105_Text_LuisDefeated: @ 8295E66
	.string "Glou… Glou…$"

Route105_Text_LuisPostBattle: @ 8295E72
	.string "Si tu es en train de te noyer, il faut\n"
	.string "agiter un bras pour le signaler.$"

Route105_Text_DominikIntro: @ 8295EB7
	.string "Nager dans la mer d'un bleu intense…\n"
	.string "C'est formidable!$"

Route105_Text_DominikDefeated: @ 8295EEA
	.string "J'ai perdu…\n"
	.string "Maintenant, je broie du noir…$"

Route105_Text_DominikPostBattle: @ 8295F08
	.string "Pourquoi la mer est-elle bleue?\p"
	.string "Je l'ai appris au MUSEE de POIVRESSEL,\n"
	.string "mais j'ai oublié.$"

Route105_Text_BeverlyIntro: @ 8295F5C
	.string "Mon corps semble plus léger dans l'eau.\n"
	.string "C'est comme si j'avais maigri!$"

Route105_Text_BeverlyDefeated: @ 8295FA0
	.string "Je flotte…$"

Route105_Text_PostBattle: @ 8295FAE
	.string "Le poids de ton corps n'est réduit que\n"
	.string "d'un dixième dans l'eau.\p"
	.string "Je ferais donc…\n"
	.string "Hé! J'vais pas te dire combien je pèse!$"

Route105_Text_ImaniIntro: @ 8296025
	.string "Le bleu du ciel…\n"
	.string "L'étendue de la mer…\l"
	.string "C'est tellement paisible…$"

Route105_Text_ImaniDefeated: @ 8296059
	.string "J'ai perdu car je me suis laissée aller!$"

Route105_Text_ImaniPostBattle: @ 8296076
	.string "Je veux qu'on trouve ça apaisant d'être\n"
	.string "avec moi. Hi, hi, hi…$"

Route105_Text_AndresIntro: @ 82960A9
	.string "Je suis convaincu que la mer nous\n"
	.string "cache de nombreux secrets.$"

Route105_Text_AndresDefeated: @ 82960DB
	.string "Oui…\n"
	.string "Je ne suis pas très bon au combat…$"

Route105_Text_AndresPostBattle: @ 82960FA
	.string "Il y a sûrement plein de secrets à\n"
	.string "découvrir au fond des océans.\p"
	.string "Je veux tous les trouver!$"

Route105_Text_AndresRegister: @ 8296159
	.string "Heu? Tu veux quand même m'enregistrer\n"
	.string "dans ton POKéNAV?$"

Route105_Text_AndresRematchIntro: @ 829619E
	.string "Je t'ai déjà dit que je n'étais pas\n"
	.string "très fort…\p"
	.string "Mais si tu insistes…$"

Route105_Text_AndresRematchDefeated: @ 82961DD
	.string "Oui…\n"
	.string "Je m'en doutais un peu…$"

Route105_Text_AndresRematchPostBattle: @ 82961FE
	.string "Je ne me bats peut-être pas très bien,\n"
	.string "mais personne ne m'arrive à la cheville\l"
	.string "quand il s'agit d'exploration.\p"
	.string "Je vais parcourir les océans à travers\n"
	.string "le monde!$"

Route105_Text_JosueIntro: @ 829626F
	.string "Nager, ça m'a épuisé.\n"
	.string "J'suis pas vraiment habitué.\p"
	.string "Un petit combat pour changer?$"

Route105_Text_JosueDefeated: @ 82962CB
	.string "J'ai perdu parce qu'on était près\n"
	.string "de l'eau.$"

Route105_Text_JosuePostBattle: @ 82962EC
	.string "Dans le ciel, je me sens plus à \n"
	.string "l'aise que dans l'eau!$"

Route106_Text_ElliotIntro: @ 8296327
	.string "Que préfères-tu: pêcher en mer ou\n"
	.string "en rivière?$"

Route106_Text_ElliotDefeated: @ 829635C
	.string "Comme à la pêche en mer, j'ai perdu\n"
	.string "de façon spectaculaire!$"

Route106_Text_ElliotPostBattle: @ 829638C
	.string "La pêche, c'est ce qu'il y a de mieux, peu\n"
	.string "importe que ce soit en mer ou en rivière.\l"
	.string "T'es d'accord avec moi?$"

Route106_Text_ElliotRegister: @ 82963E3
	.string "C'est cool la pêche, un peu comme les\n"
	.string "combats quoi!\p"
	.string "Il faudrait qu'on remette ça un jour.$"

Route106_Text_ElliotRematchIntro: @ 829642E
	.string "En pêchant, j'ai attrapé un paquet de \n"
	.string "POKéMON. Le combat va être terrible!$"

Route106_Text_ElliotRematchDefeated: @ 8296477
	.string "J'ai encore perdu de façon prodigieuse!$"

Route106_Text_ElliotRematchPostBattle: @ 8296493
	.string "Gagner ou perdre… De toute façon, les\n"
	.string "POKéMON, y a rien de mieux!$"

Route106_Text_NedIntro: @ 82964D4
	.string "Que font les gens s'ils ont envie d'aller\n"
	.string "aux toilettes?\p"
	.string "J'fais quoi si j'ai une touche quand je\n"
	.string "suis aux toilettes? Je suis obligé de\l"
	.string "rester là…$"

Route106_Text_NedDefeated: @ 8296553
	.string "J'ai perdu parce que j'essaie\n"
	.string "de me retenir…$"

Route106_Text_NedPostBattle: @ 8296588
	.string "Oh, non! Je croyais que j'allais avoir\n"
	.string "une grosse prise!$"

Route106_Text_DouglasIntro: @ 82965BB
	.string "Ah, ah, ah! Je suis un mauvais coureur\n"
	.string "mais dans l'eau, on ne m'attrape pas!$"

Route106_Text_DouglasDefeated: @ 82965FD
	.string "J'abandonne!$"

Route106_Text_DouglasPostBattle: @ 8296608
	.string "Je ne perdrai pas une course à la nage…$"

Route106_Text_KylaIntro: @ 8296628
	.string "La mer est mon repaire. Même si tu\n"
	.string "es jeune, je n'vais pas te\l"
	.string "faciliter la tâche!$"

Route106_Text_KylaDefeated: @ 8296674
	.string "Est-ce que par hasard, tu as trouvé\n"
	.string "ça trop facile?$"

Route106_Text_KylaPostBattle: @ 829669E
	.string "Se laisser aller au gré des vagues…\n"
	.string "J'adore ça! Pourquoi tu n'essaierais\l"
	.string "pas?$"

Route107_Text_DarrinIntro: @ 82966E5
	.string "Ouhaaaa…\p"
	.string "Je me suis endormi en me laissant\n"
	.string "porter par les vagues.$"

Route107_Text_DarrinDefeated: @ 829672F
	.string "Ah, ah, j'ai perdu…\n"
	.string "J'vais faire une p'tite sieste…$"

Route107_Text_DarrinPostBattle: @ 829675B
	.string "Flotter et se laisser bercer par les\n"
	.string "vagues, c'est comme dormir dans\l"
	.string "un bon lit bien douillet.$"

Route107_Text_TonyIntro: @ 82967AD
	.string "La mer est comme ma seconde maison.\n"
	.string "Battons-nous!$"

Route107_Text_TonyDefeated: @ 82967D8
	.string "J'ai perdu sur mon territoire…\n"
	.string "Quel choc!$"

Route107_Text_TonyPostBattle: @ 82967FF
	.string "Je traverse les mers à la nage, le cœur\n"
	.string "rempli de rêves…\p"
	.string "C'est une chanson!\n"
	.string "De toute façon, je nage encore un peu.$"

Route107_Text_TonyRegister: @ 829685A
	.string "J'en suis tout retourné!\n"
	.string "Comme ça, tu te souviendras de moi!$"

Route107_Text_TonyRematchIntro: @ 8296897
	.string "A nager dans cette large et vaste mer,\n"
	.string "mon POKéMON est devenu plus fort.$"

Route107_Text_TonyRematchDefeated: @ 82968D5
	.string "Quel choc!\p"
	.string "Mon POKéMON est devenu plus fort,\n"
	.string "mais je suis resté faible…$"

Route107_Text_TonyRematchPostBattle: @ 8296923
	.string "Ce que tu apprends au combat te rend\n"
	.string "plus fort en tant que DRESSEUR.\p"
	.string "Les vagues m'ont appris ça.$"

Route107_Text_DeniseIntro: @ 8296974
	.string "Tu connais une petite ville appelée\n"
	.string "MYOKARA?$"

Route107_Text_DeniseDefeated: @ 829699E
	.string "Je déteste ça!$"

Route107_Text_DenisePostBattle: @ 82969AB
	.string "Un curieux proverbe est en train de\n"
	.string "devenir à la mode au CENTRE\l"
	.string "CULTUREL DE MYOKARA.$"

Route107_Text_BethIntro: @ 82969E4
	.string "Tu voulais te battre contre moi?\n"
	.string "Oui, c'est OK pour moi!$"

Route107_Text_BethDefeated: @ 8296A17
	.string "Je n'étais pas assez forte pour toi.$"

Route107_Text_BethPostBattle: @ 8296A35
	.string "Je crois que les choses iront de mieux\n"
	.string "en mieux pour toi. Je me lance aussi!$"

Route107_Text_LisaIntro: @ 8296A77
	.string "LISA: Accepte le défi d'un frère\n"
	.string "et d'une sœur!$"

Route107_Text_LisaDefeated: @ 8296AA7
	.string "LISA: Impressionnant!\n"
	.string "Tu as un niveau bien plus élevé.$"

Route107_Text_LisaPostBattle: @ 8296ADC
	.string "LISA: As-tu des amis qui aimeraient\n"
	.string "aller à la plage avec toi?$"

Route107_Text_LisaNotEnoughPokemon: @ 8296B1E
	.string "LISA: Si tu veux nous affronter,\n"
	.string "apporte plus de POKéMON.$"

Route107_Text_RayIntro: @ 8296B57
	.string "RAY: Avec ma sœur, on est toujours\n"
	.string "en train de faire des combats POKéMON.\p"
	.string "Je perds toujours, mais on peut te\n"
	.string "battre en 2 contre 2!$"

Route107_Text_RayDefeated: @ 8296BB3
	.string "RAY: Waouh, tu as un meilleur niveau\n"
	.string "que nous!$"

Route107_Text_RayPostBattle: @ 8296BE1
	.string "RAY: C'est ma sœur qui m'a donné\n"
	.string "mon POKéMON. Je l'ai élevé et\l"
	.string "maintenant, c'est mon meilleur allié!$"

Route107_Text_RayNotEnoughPokemon: @ 8296C34
	.string "RAY: Si tu veux nous affronter,\n"
	.string "ramène d'autres POKéMON!$"

Route107_Text_CamronIntro: @ 8296C6F
	.string "Je suis en plein triathlon, mais je\n"
	.string "n'ai rien contre un petit match!$"

Route107_Text_CamronDefeated: @ 8296CAD
	.string "J'en peux plus…$"

Route107_Text_CamronPostBattle: @ 8296CC0
	.string "Il me reste encore les épreuves de\n"
	.string "vélo et de course après ça.\p"
	.string "Je ne tiendrai jamais…$"

Route108_Text_JeromeIntro: @ 8296D10
	.string "Mon rêve est de parcourir les sept mers\n"
	.string "du monde à la nage!$"

Route108_Text_JeromeDefeated: @ 8296D3C
	.string "C'est pas comme ça que j'vais pouvoir\n"
	.string "parcourir les sept mers à la nage…$"

Route108_Text_JeromePostBattle: @ 8296D6E
	.string "Jouer avec les POKéMON marins, c'est\n"
	.string "l'un des plaisirs de la nage!$"

Route108_Text_MatthewIntro: @ 8296DAF
	.string "Eho, toi là-bas! Tu vas aussi à l'EPAVE?$"

Route108_Text_MatthewDefeated: @ 8296DEA
	.string "Je me noie!\n"
	.string "Glou… Glou…$"

Route108_Text_MatthewPostBattle: @ 8296E03
	.string "Certaines personnes sont même allées\n"
	.string "à l'intérieur de cette EPAVE.$"

Route108_Text_TaraIntro: @ 8296E33
	.string "Mon menteur de petit ami m'a dit que\n"
	.string "j'étais très jolie en bikini…$"

Route108_Text_TaraDefeated: @ 8296E71
	.string "Oh, bouh!$"

Route108_Text_TaraPostBattle: @ 8296E7A
	.string "Même si ce n'est pas vrai, j'aime bien\n"
	.string "qu'on me dise que je suis jolie…\p"
	.string "Ah, nous les filles…$"

Route108_Text_MissyIntro: @ 8296EC7
	.string "J'adore la mer!\n"
	.string "J'oublie tous mes soucis quand je nage.$"

Route108_Text_MissyDefeated: @ 8296EFC
	.string "Quand je perds un combat,\n"
	.string "ça me stresse!$"

Route108_Text_MissyPostBattle: @ 8296F2A
	.string "Nager pour évacuer son stress!\n"
	.string "C'est tellement sain!$"

Route108_Text_CoryIntro: @ 8296F5D
	.string "J'adore les POKéMON de type EAU.\n"
	.string "Les autres aussi d'ailleurs!$"

Route108_Text_CoryDefeated: @ 8296F93
	.string "Aaaaah! J'ai perdu!\n"
	.string "Noooon!$"

Route108_Text_CoryPostBattle: @ 8296FB0
	.string "Crie un coup quand ça va pas!\n"
	.string "Ça soulage!$"

Route108_Text_CoryRegister: @ 8296FD8
	.string "J'adore les DRESSEURS difficiles!\n"
	.string "Enregistre-moi dans ton POKéNAV!$"

Route108_Text_CoryRematchIntro: @ 8297011
	.string "Gagner ou perdre, peu importe tant\n"
	.string "que je me bats sur l'eau!$"

Route108_Text_CoryRematchDefeated: @ 8297036
	.string "Aaaaaaaah! J'ai encore perdu!\n"
	.string "Nooooooon!$"

Route108_Text_CoryRematchPostBattle: @ 8297059
	.string "Si tu cherches un challenge,\n"
	.string "essaie de crier en mer!$"

Route108_Text_CarolinaIntro: @ 8297094
	.string "Je suis très fière de mes POKéMON.\n"
	.string "Laisse-moi un peu te montrer!$"

Route108_Text_CarolinaDefeated: @ 82970D7
	.string "C'était vraiment pas sympa de ta part!$"

Route108_Text_CarolinaPostBattle: @ 82970F0
	.string "Comme je suis à la mer, je n'ai rien\n"
	.string "contre l'idée de mettre un petit\l"
	.string "maillot de bain rose…$"

Route109_Text_DavidIntro: @ 8297140
	.string "Hé, hé! Regarde un peu mes abdos!\n"
	.string "On appelle ça “être bien bâti”!$"

Route109_Text_DavidDefeated: @ 829717D
	.string "Oh, oh!\n"
	.string "A côté d'la plaque!$"

Route109_Text_DavidPostBattle: @ 8297191
	.string "Hé, hé!\p"
	.string "Mes abdos bien sculptés n'ont rien à\n"
	.string "voir avec les combats de POKéMON!$"

Route109_Text_AliceIntro: @ 82971D1
	.string "Tu as une bonne protection contre le\n"
	.string "soleil?$"

Route109_Text_AliceDefeated: @ 82971FD
	.string "Ouille, ouille, ouille!$"

Route109_Text_AlicePostBattle: @ 829720F
	.string "Ce sont les joues qui sont les plus\n"
	.string "exposées aux coups de soleil.$"

Route109_Text_HueyIntro: @ 8297235
	.string "J'ai jeté l'ancre dans tous les ports du\n"
	.string "monde, mais c'est POIVRESSEL\l"
	.string "que je préfère.$"

Route109_Text_HueyDefeated: @ 829727B
	.string "Y a pas meilleur que toi!$"

Route109_Text_HueyPostBattle: @ 829728C
	.string "Dans le plus beau port se trouve donc\n"
	.string "le plus fort des DRESSEURS…$"

Route109_Text_EdmondIntro: @ 82972B3
	.string "Aaaaaaaaaah…\n"
	.string "Te battre? Contre moi?$"

Route109_Text_EdmondDefeated: @ 82972CE
	.string "Aah… Oooooooohhhhh…\n"
	.string "Aaaaaaaaaah…$"

Route109_Text_EdmondPostBattle: @ 82972ED
	.string "D'habitude, je suis meilleur que ça!\n"
	.string "Je suis juste malade comme un chien!\p"
	.string "Je suis MARIN, mais j'ai le mal de mer…$"

Route109_Text_RickyIntro: @ 829733B
	.string "J'ai si soif… Je pourrais aller prendre\n"
	.string "un SODA COOL à la MAISON DU BORD DE MER.$"

Route109_Text_RickyDefeated: @ 8297379
	.string "Grrrrrr…$"

Route109_Text_RickyPostBattle: @ 8297380
	.string "Je suis affamé… Ma bouée\n"
	.string "ressemble à un beignet géant…$"

Route109_Text_RickyRegister: @ 82973C1
	.string "On se battra encore?\n"
	.string "Dès que je n'aurai plus soif, OK?$"

Route109_Text_RickyRematchIntro: @ 82973FF
	.string "Je suis affamé, mais j'ai encore assez\n"
	.string "de forces en moi pour combattre!$"

Route109_Text_RickyRematchDefeated: @ 8297437
	.string "J'ai perdu…\n"
	.string "C'est parce que je suis affamé…$"

Route109_Text_RickyRematchPostBattle: @ 8297458
	.string "Quand on mange sur la plage,\n"
	.string "tout semble meilleur.$"

Route109_Text_LolaIntro: @ 829749C
	.string "Ne trouves-tu pas qu'un parasol\n"
	.string "ressemble à une fleur géante?$"

Route109_Text_LolaDefeated: @ 82974CF
	.string "Maman!$"

Route109_Text_LolaPostBattle: @ 82974D6
	.string "La plage vue du ciel ressemble à un\n"
	.string "grand jardin de fleurs!$"

Route109_Text_LolaRegister: @ 8297520
	.string "Moi?\n"
	.string "Je suis là tous les jours!$"

Route109_Text_LolaRematchIntro: @ 8297538
	.string "Je n'vais pas encore perdre contre toi!\n"
	.string "C'est pour ça que j'ai ma bouée!$"

Route109_Text_LolaRematchDefeated: @ 8297576
	.string "Maman!$"

Route109_Text_LolaRematchPostBattle: @ 829757D
	.string "Avec une bouée, la grâce de mes POKéMON\n"
	.string "va augmenter, et la mienne aussi!$"

Route109_Text_AustinaIntro: @ 82975C0
	.string "Je ne peux pas nager sans ma bouée,\n"
	.string "mais je ne perdrai pas aux POKéMON!$"

Route109_Text_AustinaDefeated: @ 8297601
	.string "C'est parce que j'avais une bouée que\n"
	.string "j'ai perdu?$"

Route109_Text_AustinaPostBattle: @ 829762A
	.string "Ma bouée est un accessoire de mode.\n"
	.string "Je ne sors jamais sans elle.$"

Route109_Text_GwenIntro: @ 8297667
	.string "Salut, grand DRESSEUR.\n"
	.string "Tu veux te battre contre moi?$"

Route109_Text_GwenDefeated: @ 8297691
	.string "Oh, quelle puissance!$"

Route109_Text_GwenPostBattle: @ 82976A4
	.string "Comment as-tu atteint un tel niveau?$"

Route109_Text_CarterIntro: @ 82976C5
	.string "Waaouh! Qu'est-ce que tu vas t'prendre!$"

Route109_Text_CarterDefeated: @ 82976FC
	.string "J'ai perdu…$"

Route109_Text_CarterPostBattle: @ 8297715
	.string "Je pense que tu es remarquable.\n"
	.string "Non, que tu vas devenir remarquable!$"

Route109_Text_PaulIntro: @ 8297754
	.string "PAUL: Eh bien, on peut dire que tu\n"
	.string "sais casser l'ambiance.\p"
	.string "Tu ne souhaiterais pas gâcher notre\n"
	.string "précieux temps ensemble, par hasard?$"

Route109_Text_PaulDefeated: @ 82977B0
	.string "PAUL: Bon, j'abandonne.$"

Route109_Text_PaulPostBattle: @ 82977C7
	.string "PAUL: Ne dis à personne qu'on est là.\n"
	.string "C'est juste notre monde secret à tous\l"
	.string "les deux!$"

Route109_Text_PaulNotEnoughPokemon: @ 829781D
	.string "PAUL: On s'aime profondément.\n"
	.string "C'est pour ça qu'on fait combattre nos\l"
	.string "POKéMON ensemble.$"

Route109_Text_MelIntro: @ 8297872
	.string "MEL: On est follement amoureux.\n"
	.string "Notre amour enflamme tout HOENN!$"

Route109_Text_MelDefeated: @ 82978BD
	.string "MEL: On a perdu et c'est ma faute!\n"
	.string "PAUL va me détester!$"

Route109_Text_MelPostBattle: @ 82978F1
	.string "MEL: Euh, PAUL, tu m'en veux?\n"
	.string "Ne te fâche pas, je t'en prie.$"

Route109_Text_MelNotEnoughPokemon: @ 829792E
	.string "MEL: On s'aime profondément.\n"
	.string "C'est pour ça qu'on fait combattre nos\l"
	.string "POKéMON ensemble.$"

Route109_Text_ChandlerIntro: @ 829798A
	.string "Tadaaah! Tu vois?\n"
	.string "Ma bouée est toute ronde!$"

Route109_Text_ChandlerDefeated: @ 82979AE
	.string "Oh oh!\n"
	.string "C'est trop dommage!$"

Route109_Text_ChandlerPostBattle: @ 82979BF
	.string "Et tout ça après que je t'ai montré\n"
	.string "ma bouée…$"

Route109_Text_HaileyIntro: @ 82979EC
	.string "Je ne sais pas nager, alors je fais\n"
	.string "juste semblant.$"

Route109_Text_HaileyDefeated: @ 8297A15
	.string "C'est bien ce que je pensais!\n"
	.string "Je ne pouvais pas gagner!$"

Route109_Text_HaileyPostBattle: @ 8297A40
	.string "Quand je me suis mise à la natation,\n"
	.string "je pensais que mes POKéMON\l"
	.string "deviendraient plus forts.$"

Route109_Text_ElijahIntro: @ 8297A82
	.string "Pour un macho comme moi, cette\n"
	.string "combinaison de POKéMON est\l"
	.string "la paire idéale.$"

Route109_Text_ElijahDefeated: @ 8297AC7
	.string "Je reste cool même dans la défaite.$"

Route109_Text_ElijahPostBattle: @ 8297AE5
	.string "Pour un macho comme moi, un port\n"
	.string "est le lieu idéal!\p"
	.string "Je pense donc aller faire un tour\n"
	.string "à POIVRESSEL.$"

Route110_Text_JacobIntro: @ 8297B3F
	.string "Waouh! Regarde ça! Tu ne dois pas trop\n"
	.string "connaître les courses de VELO.$"

Route110_Text_JacobDefeated: @ 8297B77
	.string "Waouh! \n"
	.string "Mes freins ont lâché!$"

Route110_Text_JacobPostBattle: @ 8297B8F
	.string "Des pneus à plat et des problèmes de\n"
	.string "freins peuvent faire de sérieux dégâts!\p"
	.string "Vérifie ton VELO!$"

Route110_Text_AnthonyIntro: @ 8297BE7
	.string "Hé, toi!\n"
	.string "Tu peux aller aussi vite que moi?$"

Route110_Text_AnthonyDefeated: @ 8297C0F
	.string "Je suis anéanti!$"

Route110_Text_AnthonyPostBattle: @ 8297C1F
	.string "La vitesse ne suffira pas à me faire\n"
	.string "gagner aux POKéMON. Je dois revoir ça…$"

Route110_Text_BenjaminIntro: @ 8297C63
	.string "Ne panique pas quand ton VELO va vite!$"

Route110_Text_BenjaminDefeated: @ 8297C8A
	.string "Je ne devrais pas m'affoler pendant les\n"
	.string "combats de POKéMON…$"

Route110_Text_BenjaminPostBattle: @ 8297CB4
	.string "Pas la peine de paniquer ou de stresser.\n"
	.string "T'énerve pas! Rien ne presse!$"

Route110_Text_BenjaminRegister: @ 8297CFE
	.string "Ce qui compte c'est l'entraînement.\n"
	.string "Appelle-moi si tu veux qu'on\l"
	.string "se retrouve.$"

Route110_Text_BenjaminRematchIntro: @ 8297D4B
	.string "T'irais pas un peu trop vite?\n"
	.string "T'énerve pas et viens te battre!$"

Route110_Text_BenjaminRematchDefeated: @ 8297D8E
	.string "Je n'ai pas paniqué, mais j'ai perdu…$"

Route110_Text_BenjaminRematchPostBattle: @ 8297DB0
	.string "Pas la peine de paniquer ou de stresser.\n"
	.string "T'énerve pas! Rien ne presse!$"

Route110_Text_AbigailIntro: @ 8297DFA
	.string "Le triathlon est extrêmement difficile.\p"
	.string "Il faut réussir trois épreuves:\n"
	.string "natation, cyclisme et course à pied.$"

Route110_Text_AbigailDefeated: @ 8297E69
	.string "C'est difficile aussi, les combats\n"
	.string "de POKéMON!$"

Route110_Text_AbigailPostBattle: @ 8297E88
	.string "Je suis exténuée. Une pause s'impose.\n"
	.string "C'est important de bien se reposer.$"

Route110_Text_AbigailRegister: @ 8297ECD
	.string "Tu sais, je t'aime bien!\n"
	.string "Ça te dit une revanche sur la\l"
	.string "PISTE CYCLABLE?$"

Route110_Text_AbigailRematchIntro: @ 8297F09
	.string "C'est pratique de livrer bataille en\n"
	.string "faisant du VELO, non?$"

Route110_Text_AbigailRematchDefeated: @ 8297F37
	.string "Waouh… Comment peut-on avoir autant\n"
	.string "de talent?$"

Route110_Text_AbigailRematchPostBattle: @ 8297F58
	.string "T'essayais de battre un record?\p"
	.string "Désolée si je te retarde!$"

Route110_Text_JasmineIntro: @ 8297F93
	.string "Je n'ai pas arrêté de faire du vélo.\n"
	.string "J'ai des cuisses en béton!$"

Route110_Text_JasmineDefeated: @ 8297FD0
	.string "J'ai peur d'avoir des crampes…$"

Route110_Text_JasminePostBattle: @ 8297FF1
	.string "Oh, tu as des BADGES D'ARENE?\n"
	.string "Pas étonnant que tu aies un tel niveau!$"

Route110_Text_EdwardIntro: @ 829802B
	.string "J'ai deviné tes intentions!\n"
	.string "Impossible que je perde!$"

Route110_Text_EdwardDefeated: @ 8298064
	.string "Je n'ai même pas vu ma propre fin!$"

Route110_Text_EdwardPostBattle: @ 829808A
	.string "Je vois ton avenir…\p"
	.string "Hum…\n"
	.string "Je vois une lumière briller…$"

Route110_Text_JaclynIntro: @ 82980B9
	.string "Ahahahaha!\n"
	.string "Mes prodiges vont t'éblouir!$"

Route110_Text_JaclynDefeated: @ 82980E5
	.string "J'ai perdu de façon prodigieuse!$"

Route110_Text_JaclynPostBattle: @ 82980F8
	.string "T'as gagné, mais c'était juste un\n"
	.string "miracle! Oui, un miracle! Ne crois pas\l"
	.string "que tu vas gagner à tous les coups!$"

Route110_Text_EdwinIntro: @ 829815E
	.string "Je pourrais voir tes POKéMON?\n"
	.string "Juste un coup d'œil, s'il te plaît.$"

Route110_Text_EdwinDefeated: @ 829818F
	.string "Je voudrais compléter ma\n"
	.string "collection…$"

Route110_Text_EdwinPostBattle: @ 82981B3
	.string "Quand je vois un POKéMON que je ne\n"
	.string "connais pas, ma passion s'enflamme!$"

Route110_Text_EdwinRegister: @ 8298201
	.string "J'adore collectionner les numéros\n"
	.string "de MATCH PHONE…$"

Route110_Text_EdwinRematchIntro: @ 8298232
	.string "Salut, t'as attrapé de nouveaux\n"
	.string "POKéMON?\p"
	.string "Je pourrais voir tes POKéMON?\n"
	.string "Juste un coup d'œil, s'il te plaît.$"

Route110_Text_EdwinRematchDefeated: @ 8298288
	.string "Tes POKéMON…\n"
	.string "Je t'envie.$"

Route110_Text_EdwinRematchPostBattle: @ 82982A2
	.string "Oh, je rêve de m'approprier tous les\n"
	.string "POKéMON rares!$"

Route110_Text_DaleIntro: @ 82982CC
	.string "Hé!\n"
	.string "Ne te faufile pas derrière moi comme ça!$"

Route110_Text_DaleDefeated: @ 82982F5
	.string "J'ai perdu!\n"
	.string "Sapristi!$"

Route110_Text_DalePostBattle: @ 8298303
	.string "La pêche repose sur la concentration.\n"
	.string "Il faut se concentrer sur le bouchon.$"

Route110_Text_IsabelIntro: @ 8298349
	.string "Ahahahaha! Je voudrais aller partout\n"
	.string "pour montrer mes adorables POKéMON.$"

Route110_Text_IsabelDefeated: @ 8298389
	.string "Oh, non, j'peux pas accepter ça…$"

Route110_Text_IsabelPostBattle: @ 82983A2
	.string "Plutôt que de me battre, je devrais\n"
	.string "peut-être montrer mes POKéMON au\l"
	.string "FAN CLUB.$"

Route110_Text_IsabelRegister: @ 82983EE
	.string "Ce n'est pas comme ça que je pourrai\n"
	.string "frimer avec mes POKéMON.\p"
	.string "Je te demanderai ton avis aussi\n"
	.string "souvent que possible!$"

Route110_Text_IsabelRematchIntro: @ 8298466
	.string "Ahahahaha! Je serais heureuse de te\n"
	.string "montrer mes POKéMON quand tu voudras!$"

Route110_Text_IsabelRematchDefeated: @ 82984AF
	.string "Oh, non, j'peux pas accepter ça…$"

Route110_Text_IsabelRematchPostBattle: @ 82984C8
	.string "Les CONCOURS, c'est charmant, je ne\n"
	.string "peux pas m'empêcher de montrer mes\l"
	.string "POKéMON.\p"
	.string "Mais j'aime aussi combattre!$"

Route110_Text_TimmyIntro: @ 8298525
	.string "J'ai trouvé des POKéMON sympas dans\n"
	.string "l'herbe aux alentours!$"

Route110_Text_TimmyDefeated: @ 8298559
	.string "Etre sympa ne suffit pas pour gagner…$"

Route110_Text_TimmyPostBattle: @ 8298579
	.string "C'est difficile de combattre avec des\n"
	.string "POKéMON tout juste attrapés.$"

Route110_Text_AlyssaIntro: @ 82985AB
	.string "Je suis tombée de la PISTE CYCLABLE…\p"
	.string "Je vais faire passer ma honte avec un\n"
	.string "petit combat contre toi!$"

Route110_Text_AlyssaDefeated: @ 82985F9
	.string "Oups!\n"
	.string "Tu as réussi à gagner!$"

Route110_Text_AlyssaPostBattle: @ 8298612
	.string "Tomber… Perdre…\n"
	.string "Tout ça est si humiliant pour moi!$"

Route110_Text_JosephIntro: @ 8298642
	.string "OK!\n"
	.string "C'est parti pour un duo électrique!$"

Route110_Text_JosephDefeated: @ 8298686
	.string "T'as le groove toi!$"

Route110_Text_JosephPostBattle: @ 82986A9
	.string "C'est pas grave. La défaite a fait de\n"
	.string "moi un homme meilleur!$"

Route110_Text_KalebIntro: @ 82986ED
	.string "Rien de plus beau que deux POKéMON\n"
	.string "qui s'entraident!$"

Route110_Text_KalebDefeated: @ 8298735
	.string "N'as-tu donc aucune compassion?$"

Route110_Text_KalebPostBattle: @ 8298755
	.string "Mes POKéMON ont fait de leur mieux,\n"
	.string "je ne leur en veux pas.$"

Route111_Text_29878E: @ 829878E
	.string "Oh, hé! Ces LUNET. SABLE te vont bien.\n"
	.string "Mais je trouve qu'elles me vont mieux.\p"
	.string "Réglons ça au combat! Voyons à qui\n"
	.string "elles vont le mieux!$"

Route111_Text_29880A: @ 829880A
	.string "Avec les LUNET. SABLE, j'ai pas pu\n"
	.string "voir ce qui s'est passé.$"

Route111_Text_298853: @ 8298853
	.string "Les LUNET. SABLE permettent de\n"
	.string "passer à travers les tempêtes de sable.\l"
	.string "J'en suis très content!$"

Route111_Text_2988A3: @ 82988A3
	.string "Je pique-nique dans le désert.\p"
	.string "Il y a souvent des DRESSEURS, alors\n"
	.string "je peux aussi prendre plaisir au combat!$"

Route111_Text_298908: @ 8298908
	.string "Ohhh! Quelle méchanceté!$"

Route111_Text_29891B: @ 829891B
	.string "Quand tu combats durant une tempête\n"
	.string "de sable, vérifie les PV de ton POKéMON.\p"
	.string "Il peut être mis K.O. si tu ne gardes pas\n"
	.string "un œil dessus!$"

Route111_Text_29898E: @ 829898E
	.string "Avec ces LUNET. SABLE, j'ai l'impression\n"
	.string "d'être un super héros.\p"
	.string "Plus personne ne peut me battre!$"

Route111_Text_2989E6: @ 82989E6
	.string "Y croire ne suffit pas pour gagner…$"

Route111_Text_298A03: @ 8298A03
	.string "Un jour, je serai un vrai héros.\n"
	.string "Je vais travailler davantage pour que\l"
	.string "mes POKéMON et moi soyons plus forts.$"

Route111_Text_298A65: @ 8298A65
	.string "Il paraît qu'il y a des fossiles\n"
	.string "dans le désert. Où peuvent-ils être?$"

Route111_Text_298AAF: @ 8298AAF
	.string "Je n'ai fait qu'une apparition…$"

Route111_Text_298AC0: @ 8298AC0
	.string "Si on peut trouver des fossiles dans le\n"
	.string "désert, il devait y avoir une mer avant.$"

Route111_Text_298B08: @ 8298B08
	.string "J'ai cherché des ruines antiques\n"
	.string "pendant trente ans!\p"
	.string "Peux-tu me défier?$"

Route111_Text_298B53: @ 8298B53
	.string "Comme je cherchais des ruines, je n'ai\n"
	.string "pas cherché de POKéMON forts.$"

Route111_Text_298B9A: @ 8298B9A
	.string "J'ai cherché des ruines antiques\n"
	.string "pendant trente ans!\p"
	.string "Non, attends, quarante ans?\n"
	.string "Ça fait combien maintenant?$"

Route111_Text_298C00: @ 8298C00
	.string "Je n'ai pas trop cherché de POKéMON\n"
	.string "vraiment coriaces.\p"
	.string "Mais ça ne m'empêche pas de bien\n"
	.string "aimer les POKéNAVS.$"

Route111_Text_298C5F: @ 8298C5F
	.string "J'ai cherché des ruines antiques\n"
	.string "pendant trente ans!\p"
	.string "Non, attends, quarante ans?\n"
	.string "De toute façon, tu peux me défier?$"

Route111_Text_298CD2: @ 8298CD2
	.string "Je n'ai trouvé ni ruines,\n"
	.string "ni POKéMON forts…$"

Route111_Text_298D0C: @ 8298D0C
	.string "J'ai cherché des ruines antiques\n"
	.string "pendant trente ans!\p"
	.string "Non, attends, ça ferait quarante ans\n"
	.string "en fait?\p"
	.string "Ça pourrait même faire cinquante ans…\n"
	.string "Mince, ça fait combien de temps?$"

Route111_Text_298DA9: @ 8298DA9
	.string "J'ai la pêche!\n"
	.string "Et mon POKéMON a de l'entrain aussi!$"

Route111_Text_298DD8: @ 8298DD8
	.string "Mon POKéMON a perdu son entrain…$"

Route111_Text_298DF1: @ 8298DF1
	.string "Quand je vois un DRESSEUR plein\n"
	.string "d'entrain, je veux voir ce qu'il vaut.$"

Route111_Text_298E2F: @ 8298E2F
	.string "Je ne sais pas où tu vas, mais tu\n"
	.string "voudrais bien te battre?$"

Route111_Text_298E6E: @ 8298E6E
	.string "Oh, t'as une force pas possible!$"

Route111_Text_298E8C: @ 8298E8C
	.string "Je me disais que je devrais aller au\n"
	.string "MONT CHIMNEE, mais la vue est\l"
	.string "également superbe ici.$"

Route111_Text_298EE6: @ 8298EE6
	.string "Pour m'entraîner, je défie tous ceux\n"
	.string "que je rencontre!$"

Route111_Text_298F14: @ 8298F14
	.string "Je déclare forfait! J'abandonne!$"

Route111_Text_298F26: @ 8298F26
	.string "Tout ce que je peux faire, c'est\n"
	.string "continuer à m'entraîner jusqu'à ce que\l"
	.string "je puisse battre des DRESSEURS\l"
	.string "aussi forts que toi.$"

Route111_Text_298F79: @ 8298F79
	.string "Fais-moi voir comme tu as endurci\n"
	.string "tes POKéMON!$"

Route111_Text_298FA9: @ 8298FA9
	.string "Je vois, tu les as considérablement\n"
	.string "endurcis.$"

Route111_Text_298FD4: @ 8298FD4
	.string "Les POKéMON et les DRESSEURS\n"
	.string "apprennent beaucoup au combat.\p"
	.string "Le plus important, c'est de ne jamais\n"
	.string "abandonner, même quand on perd.$"

Route111_Text_29903D: @ 829903D
	.string "Il y aurait beaucoup à dire sur ton\n"
	.string "style de combat.\p"
	.string "Si tu es d'accord, j'aimerais vraiment\n"
	.string "une revanche.$"


Route111_Text_29909B: @ 829909B
	.string "On s'entraîne ici pour passer au\n"
	.string "niveau supérieur.\l"
	.string "Reste et entraîne-toi avec nous!$"

Route111_Text_2990EE: @ 82990EE
	.string "Oh, pas si mal!$"

Route111_Text_299102: @ 8299102
	.string "Si tu as un tel niveau, tu devrais\n"
	.string "viser la LIGUE POKéMON.$"

Route111_Text_299143: @ 8299143
	.string "Oh, tes POKéMON ont l'air de faire\n"
	.string "bonne figure.\l"
	.string "Je vais les enrôler.$"

Route111_Text_299193: @ 8299193
	.string "Ils ne paraissent pas seulement forts,\n"
	.string "ils le sont réellement!$"

Route111_Text_2991C2: @ 82991C2
	.string "Je pensais entraîner mes POKéMON\n"
	.string "assidûment, mais il y a encore du pain\l"
	.string "sur la planche.$"

Route111_Text_29921D: @ 829921D
	.string "J'aimerais tant avoir plus d'amis aussi\n"
	.string "forts que toi.$"

Route111_Text_29925D: @ 829925D
	.string "Tu peux rendre tes POKéMON plus\n"
	.string "ou moins forts en fonction des\l"
	.string "capacités que tu leur apprends.\p"
	.string "Quelles sortes de capacités tes\n"
	.string "POKéMON connaissent-ils?$"

Route111_Text_2992D6: @ 82992D6
	.string "Tu leur as appris de bonnes capacités!$"

Route111_Text_2992F5: @ 82992F5
	.string "J'aurais peut-être dû empêcher mes\n"
	.string "POKéMON d'évoluer jusqu'à ce qu'ils\l"
	.string "apprennent de meilleures capacités…$"

Route111_Text_29934B: @ 829934B
	.string "Je n'aurais vraiment pas dû venir ici\n"
	.string "pour un pique-nique!$"

Route111_Text_299384: @ 8299384
	.string "Aïe!\n"
	.string "Je n'aurais vraiment pas dû venir!$"

Route111_Text_2993A7: @ 82993A7
	.string "Dans une tempête de sable comme ça,\n"
	.string "il est vraiment impossible de faire\p"
	.string "un pique-nique, même avec\n"
	.string "les LUNET. SABLE!$"

Route111_Text_299401: @ 8299401
	.string "Es-tu vraiment si redoutable?\n"
	.string "Je vais tenter de percer ce secret!$"

Route111_Text_299431: @ 8299431
	.string "Oh, ta force!\n"
	.string "Elle est entourée de mystère!$"

Route111_Text_29945F: @ 829945F
	.string "Ce désert regorge de mystères enfouis\n"
	.string "sous le sable!$"

Route111_Text_299493: @ 8299493
	.string "Si je gagne, je te donnerai un de mes\n"
	.string "sandwichs!$"

Route111_Text_2994C5: @ 82994C5
	.string "Pff, je pensais qu'un sandwich\n"
	.string "suffirait à te corrompre…$"

Route111_Text_2994FB: @ 82994FB
	.string "Mon SABELETTE adore manger\n"
	.string "mes sandwichs.$"

Route111_Text_299524: @ 8299524
	.string "C'est mon genre de POKéMON préféré!$"

Route111_Text_299549: @ 8299549
	.string "Attends!\n"
	.string "Tu as bien regardé mon POKéMON?$"

Route111_Text_299576: @ 8299576
	.string "Au début d'un combat, j'adore le\n"
	.string "moment où je présente mes POKéMON.\p"
	.string "Mais je suis sûr que tout le monde\n"
	.string "ressent la même fierté, non?$"

Route111_Text_2995F0: @ 82995F0
	.string "Montre-moi comment mettre un\n"
	.string "peu de piment dans ma vie!$"

Route111_Text_299625: @ 8299625
	.string "Oh… Non…\n"
	.string "C'était trop épicé pour moi!$"

Route111_Text_29964B: @ 829964B
	.string "Mon cœur bat encore à tout rompre.\n"
	.string "Tu es un DRESSEUR d'exception.$"

Route111_Text_299682: @ 8299682
	.string "Quelqu'un d'aussi connu que moi ne\n"
	.string "connaît aucune pitié.$"

Route111_Text_2996BE: @ 82996BE
	.string "Grr…$"

Route111_Text_2996C5: @ 82996C5
	.string "Mon estomac gargouille!\n"
	.string "Je devrais essayer de me faire griller\l"
	.string "quelques BAIES…$"

Route111_Text_2996FE: @ 82996FE
	.string "Tu viens de LAVANDIA?\n"
	.string "Quelle énergie tu dois avoir!$"

Route111_Text_29973D: @ 829973D
	.string "Ooh là là!\n"
	.string "C'était trop pour moi!$"

Route111_Text_29975D: @ 829975D
	.string "Cette route…\p"
	.string "Tu n'es pas encore au bout de\n"
	.string "tes peines.$"

Route112_Text_29978E: @ 829978E
	.string "Ahahahaha!\n"
	.string "Et si on s'affrontait?\p"
	.string "Toi et moi!\n"
	.string "Ahahahaha!$"

Route112_Text_2997CA: @ 82997CA
	.string "J'ai perdu!\n"
	.string "Ahahahaha!$"

Route112_Text_2997DC: @ 82997DC
	.string "Ahahahahaha! Quelque chose me monte\n"
	.string "au nez! Ahahahaha-tchoum!$"

Route112_Text_299815: @ 8299815
	.string "Mes jambes se sont endurcies à fouler\n"
	.string "le sol rocheux des montagnes.\p"
	.string "Elles ne vont pas flancher facilement,\n"
	.string "camarade!$"

Route112_Text_29987C: @ 829987C
	.string "Ouille!\n"
	.string "J'ai des crampes dans les jambes!$"

Route112_Text_299896: @ 8299896
	.string "Essaie d'escalader ces sentiers de\n"
	.string "montagne en portant un bon poids\l"
	.string "sur le dos.\p"
	.string "Ça, camarade, ça te fera un bon\n"
	.string "exercice.$"

Route112_Text_29993C: @ 829993C
	.string "Mes jambes sont pleines de crampes.\n"
	.string "Tu peux m'attraper la pommade qui\l"
	.string "est dans mon sac à dos?\p"
	.string "Non, ça c'est mon POKéNAV!\n"
	.string "OK, je t'enregistre!$"

Route112_Text_2999BD: @ 82999BD
	.string "J'ai gardé la forme grâce à la\n"
	.string "randonnée.\p"
	.string "De la puissance, j'en ai à la pelle!$"

Route112_Text_2999F7: @ 82999F7
	.string "Me suis-je fait battre en puissance?$"

Route112_Text_299A0F: @ 8299A0F
	.string "J'ai entendu dire qu'il y avait des\n"
	.string "DRESSEURS en haut du MONT CHIMNEE.\p"
	.string "Je compte y monter pour leur lancer\n"
	.string "un défi!$"

Route112_Text_299A89: @ 8299A89
	.string "Je suis fort.\n"
	.string "J'vais pas pleurer si je perds.$"

Route112_Text_299AAC: @ 8299AAC
	.string "Ouuuin!$"

Route112_Text_299AB4: @ 8299AB4
	.string "J'pleure pas parce que maman me manque!\n"
	.string "Sniff…$"

Route112_Text_299AE4: @ 8299AE4
	.string "Quand tu pars faire un pique-nique,\n"
	.string "il faut chanter!\l"
	.string "Viens, chante avec moi!$"

Route112_Text_299B36: @ 8299B36
	.string "Oh, quel talent!$"

Route112_Text_299B4C: @ 8299B4C
	.string "Peu importe que tu sois bon ou mauvais\n"
	.string "en chant et en POKéMON.\p"
	.string "Le gagnant est celui qui prend le plus\n"
	.string "de plaisir!$"

Route112_Text_299BAE: @ 8299BAE
	.string "J'ai attrapé des POKéMON brûlants sur\n"
	.string "le CHEMIN ARDENT!\p"
	.string "Tu veux les voir?$"

Route112_Text_299BDF: @ 8299BDF
	.string "C'était vraiment chaud!$"

Route112_Text_299BFB: @ 8299BFB
	.string "J'aime beaucoup ta façon de combattre.\p"
	.string "On sent que l'inspiration te vient\n"
	.string "naturellement.$"

Route112_Text_299C34: @ 8299C34
	.string "Oh, quel DRESSEUR adorable tu es!\p"
	.string "Battons-nous de façon courtoise,\n"
	.string "je t'en prie!$"

Route112_Text_299C8F: @ 8299C8F
	.string "Oh, quelle force!\n"
	.string "J'en suis toute retournée.$"

Route112_Text_299CC6: @ 8299CC6
	.string "Tu as des choses à faire en ce moment?\n"
	.string "Je pensais qu'on pourrait peut-être\l"
	.string "faire notre match de revanche…\p"
	.string "Mais ne t'inquiète pas, ce n'est pas\n"
	.string "grave si tu n'as pas le temps.$"

Route113_Text_299D3C: @ 8299D3C
	.string "Tu sais pourquoi il fait si frais dans\n"
	.string "les alentours?$"

Route113_Text_299D68: @ 8299D68
	.string "Arrrg!\n"
	.string "J'suis dégoûté!$"

Route113_Text_299D7D: @ 8299D7D
	.string "Comme les cendres volcaniques gênent \n"
	.string "le soleil, il ne fait pas trop chaud.\p"
	.string "Tant mieux, je ne supporte pas\n"
	.string "la chaleur!$"

Route113_Text_299DE3: @ 8299DE3
	.string "Les éruptions volcaniques prouvent que\n"
	.string "la terre est en vie.$"

Route113_Text_299E1C: @ 8299E1C
	.string "T'es quelqu'un de fort!$"

Route113_Text_299E38: @ 8299E38
	.string "Ah! J'peux plus avancer! Les cendres\n"
	.string "m'empêchent de descendre!\p"
	.string "Tu piges? Les cendres et descendre?\p"
	.string "D'accord, c'était pas terrible. Désolé…$"

Route113_Text_299EA6: @ 8299EA6
	.string "Je prends ce parasol pour que mon cher\n"
	.string "CHAMALLOT ne soit pas recouvert de ces\l"
	.string "fichues cendres dégoûtantes.$"

Route113_Text_299EF9: @ 8299EF9
	.string "Fooouuu…\n"
	.string "Je suis exténuée…$"

Route113_Text_299F15: @ 8299F15
	.string "Tu as vraiment du talent!\n"
	.string "Je dois dire que je suis impressionnée!$"

Route113_Text_299F49: @ 8299F49
	.string "Viens te mettre à l'abri sous mon\n"
	.string "parasol.\p"
	.string "Laisse-moi t'enregistrer dans mon\n"
	.string "POKéNAV.$"

Route113_Text_299F8A: @ 8299F8A
	.string "Oh salut, ça faisait longtemps, hein?\n"
	.string "Puis-je t'inviter à combattre?$"

Route113_Text_299FC9: @ 8299FC9
	.string "Oh, génial!$"

Route113_Text_299FD8: @ 8299FD8
	.string "Tu as toujours autant de talent.\n"
	.string "Je dois dire que je suis impressionnée!$"

Route113_Text_29A015: @ 829A015
	.string "Je jaillis des cendres! Yaha!\n"
	.string "Je t'mets au défi!$"

Route113_Text_29A04C: @ 829A04C
	.string "J'admets la défaite avec dignité!$"

Route113_Text_29A067: @ 829A067
	.string "Il me faut parfaire l'art de la\n"
	.string "dissimulation. Je te fais mes adieux.$"

Route113_Text_29A0A2: @ 829A0A2
	.string "Yahah! Admire l'ancienne technique\n"
	.string "ninja d'enregistrement sur POKéNAV!$"

Route113_Text_29A0E8: @ 829A0E8
	.string "Je jaillis des cendres! Yaha!\n"
	.string "Je t'mets au défi!$"

Route113_Text_29A11F: @ 829A11F
	.string "J'admets la défaite avec dignité!$"

Route113_Text_29A13A: @ 829A13A
	.string "Mon manque d'expérience au combat\n"
	.string "a déprécié ma dissimulation parfaite.\p"
	.string "Je te fais mes adieux.$"

Route113_Text_29A192: @ 829A192
	.string "Merci de m'avoir trouvé!\n"
	.string "Mais on va quand même devoir se battre!$"

Route113_Text_29A1C6: @ 829A1C6
	.string "Je vais utiliser mon pouvoir de ninja\n"
	.string "sur toi…\p"
	.string "“Que les cendres volcaniques\n"
	.string "tournoient!” \p"
	.string "… Comment? C'est déjà fini?$"

Route113_Text_29A219: @ 829A219
	.string "Tu sais c'que c'est le pire quand tu\n"
	.string "te caches?\p"
	.string "C'est de rester seul si personne\n"
	.string "ne vient.$"

Route113_Text_29A261: @ 829A261
	.string "LILA: On ramasse des cendres toutes\n"
	.string "les deux et on fait des combats\l"
	.string "de POKéMON.$"

Route113_Text_29A29D: @ 829A29D
	.string "LILA: On a perdu… Ça m'énerve, alors\n"
	.string "j'vais aller ramasser d'autres cendres.$"

Route113_Text_29A2DE: @ 829A2DE
	.string "LILA: On a quoi en cendres? Assez\n"
	.string "pour faire une FLUTEBLANCHE, j'espère.$"

Route113_Text_29A31F: @ 829A31F
	.string "LILA: On veut se battre en 2 contre\n"
	.string "2. Sinon, on risquerait de perdre!$"

Route113_Text_29A35C: @ 829A35C
	.string "NELLY: Toutes les deux, on ramasse des\n"
	.string "cendres et on combat avec des POKéMON.$"

Route113_Text_29A397: @ 829A397
	.string "NELLY: On n'a pas gagné… Ça m'agace!\n"
	.string "Je vais aller ramasser d'autres cendres.$"

Route113_Text_29A3DA: @ 829A3DA
	.string "NELLY: On a tout plein de cendres! \n"
	.string "Assez je pense pour une FLUTEBLANCHE!$"

Route113_Text_29A419: @ 829A419
	.string "NELLY: On veut se battre en\n"
	.string "2 contre 2. Sinon, on va perdre!$"

Route113_Text_29A453: @ 829A453
	.string "Pff, avec ces ailes, je pourrais\n"
	.string "facilement t'envoyer balader!$"

Route113_Text_29A480: @ 829A480
	.string "Euh… Quoi?$"

Route113_Text_29A489: @ 829A489
	.string "Je ne sais pas vraiment quoi dire après\n"
	.string "une si grosse défaite…$"

Route113_Text_29A4BF: @ 829A4BF
	.string "La chaleur qu'il fait ici me fait\n"
	.string "somnoler.\p"
	.string "Battons-nous pour me faire rester\n"
	.string "debout.$"

Route113_Text_29A508: @ 829A508
	.string "Je suis en train de rêver,\n"
	.string "j'en suis sûre…$"

Route113_Text_29A529: @ 829A529
	.string "Ça m'énerve de perdre!\n"
	.string "Je préfère encore dormir…\l"
	.string "Zzzz…$"

Route113_Text_29A566: @ 829A566
	.string "Tu étais peut-être en train de récolter\n"
	.string "des cendres?$"

Route113_Text_29A5A0: @ 829A5A0
	.string "Oups.\n"
	.string "Tu nous as eus proprement!$"

Route113_Text_29A5BE: @ 829A5BE
	.string "Je ferais mieux de me cacher aussi\n"
	.string "sous les cendres!$"

Route113_Text_29A5E4: @ 829A5E4
	.string "T… tu veux… te battre\n"
	.string "contre moi?\p"
	.string "Mais je viens à peine d'attraper\n"
	.string "mes POKéMON!$"

Route113_Text_29A628: @ 829A628
	.string "Que… Gagner a l'air de te\n"
	.string "faire plaisir…\p"
	.string "Même contre quelqu'un comme moi?$"

Route113_Text_29A65D: @ 829A65D
	.string "Oh, alors tu veux dire un mot au\n"
	.string "perdant?\p"
	.string "L'humilité, tu connais?$"

Route114_Text_29A6B1: @ 829A6B1
	.string "Lalalahihou!\p"
	.string "… …\p"
	.string "Il faut que tu cries “Lalalahihou!”\n"
	.string "si tu veux entendre ton écho!$"

Route114_Text_29A707: @ 829A707
	.string "Lalalahihou!$"

Route114_Text_29A715: @ 829A715
	.string "Quand j'étais môme, je croyais que\n"
	.string "quelqu'un m'imitait et répétait\l"
	.string "“Lalalahihou”.$"

Route114_Text_29A777: @ 829A777
	.string "Tu ne devrais pas grimper dans\n"
	.string "les montagnes sans préparation!$"

Route114_Text_29A7B5: @ 829A7B5
	.string "La montagne ne pardonne pas…$"

Route114_Text_29A7D4: @ 829A7D4
	.string "En hiver, le blizzard et les avalanches\n"
	.string "rendent la montagne mortelle.$"

Route114_Text_29A818: @ 829A818
	.string "C'est sympa le camping! On pêche, on\n"
	.string "fait griller des marshmallows et on\l"
	.string "raconte des histoires qui font peur!\p"
	.string "Mais le top, ce sont les combats de\n"
	.string "POKéMON!$"

Route114_Text_29A88F: @ 829A88F
	.string "Trop dur pour moi!$"

Route114_Text_29A89F: @ 829A89F
	.string "Je trouve ça bien de pouvoir aller\n"
	.string "faire du camping avec mes POKéMON.$"

Route114_Text_29A8D9: @ 829A8D9
	.string "J'ai besoin d'exercice après un repas.\n"
	.string "Affrontons-nous!$"

Route114_Text_29A90E: @ 829A90E
	.string "Oh, non!$"

Route114_Text_29A916: @ 829A916
	.string "Je viens de prendre un délicieux repas,\n"
	.string "alors je m'endors un peu…$"

Route114_Text_29A943: @ 829A943
	.string "Ohohohoh…\n"
	.string "Tu veux affronter mon POKéMON?$"

Route114_Text_29A973: @ 829A973
	.string "M… Mon POKéMON…$"

Route114_Text_29A981: @ 829A981
	.string "Un grand corps tout dur, d'énormes\n"
	.string "cornes et de puissants crocs…\p"
	.string "Ohohohoh…\n"
	.string "J'aimerais avoir un POKéMON comme ça…$"

Route114_Text_29A9F7: @ 829A9F7
	.string "N'oublie pas ce que tu viens de me faire!\n"
	.string "Moi, je n'oublierai pas!$"

Route114_Text_29AA3E: @ 829AA3E
	.string "Ohohohoho…\n"
	.string "Viens te battre contre moi…$"

Route114_Text_29AA67: @ 829AA67
	.string "J'ai de la chance d'avoir pu voir\n"
	.string "tes POKéMON…$"

Route114_Text_29AA94: @ 829AA94
	.string "Ohohohoho…\p"
	.string "Quand je vois des POKéMON se battre,\n"
	.string "j'ai des frissons et je tremble…$"

Route114_Text_29AADB: @ 829AADB
	.string "Avant d'allumer un feu de camp, il faut\n"
	.string "s'assurer d'avoir de l'eau à proximité.$"

Route114_Text_29AB1A: @ 829AB1A
	.string "Merci d'avoir éteint mon feu!$"

Route114_Text_29AB36: @ 829AB36
	.string "En forêt, il faut faire très attention\n"
	.string "au feu sous toutes ses formes.\p"
	.string "Ne sous-estime pas la puissance du\n"
	.string "feu.$"

Route114_Text_29ABA6: @ 829ABA6
	.string "Je meurs d'envie d'avoir une revanche!\n"
	.string "Enregistrons-nous dans nos POKéNAVS!$"

Route114_Text_29ABDC: @ 829ABDC
	.string "Tu sais que pour faire un feu de camp,\n"
	.string "il faut avoir de l'eau à portée de main?$"

Route114_Text_29AC10: @ 829AC10
	.string "Je me suis pris une douche avant même\n"
	.string "de m'enflammer.$"

Route114_Text_29AC43: @ 829AC43
	.string "En forêt, il faut faire très attention\n"
	.string "au feu sous toutes ses formes.\p"
	.string "Ne sous-estime pas sa puissance.$"

Route114_Text_29ACB3: @ 829ACB3
	.string "Si on s'affrontait à la pêche, tu\n"
	.string "n'aurais aucune chance contre moi.\l"
	.string "Alors, amène tes POKéMON!$"

Route114_Text_29AD0A: @ 829AD0A
	.string "Si on avait pêché, j'aurais gagné…$"

Route114_Text_29AD2E: @ 829AD2E
	.string "Je crois que je vais essayer de faire\n"
	.string "une bonne prise au SITE METEORE.\p"
	.string "Il doit y avoir quelque chose là-bas.\n"
	.string "Je le sens!$"

Route114_Text_29ADA1: @ 829ADA1
	.string "J'aime pêcher. Mais j'aime bien\n"
	.string "combattre aussi!\p"
	.string "Si quelqu'un me défie, je suis toujours\n"
	.string "prêt, même si je suis en train de pêcher.$"

Route114_Text_29AE05: @ 829AE05
	.string "J'aime combattre, mais ça ne veut pas\n"
	.string "dire que je suis bon…$"

Route114_Text_29AE3D: @ 829AE3D
	.string "Cette fois, je vais y arriver!\p"
	.string "Je me dis toujours ça, alors j'arrête\n"
	.string "jamais avec la pêche et les POKéMON.$"

Route114_Text_29AE96: @ 829AE96
	.string "TYRA: Eh bien, oui.\n"
	.string "Je me sens d'humeur.\p"
	.string "Je vais t'en apprendre sur les POKéMON.$"

Route114_Text_29AEE7: @ 829AEE7
	.string "TYRA: Etonnante façon de se battre!$"

Route114_Text_29AF0B: @ 829AF0B
	.string "TYRA: Je donnais à IVY une\n"
	.string "leçon sur les POKéMON.$"

Route114_Text_29AF3D: @ 829AF3D
	.string "TYRA: Hi, hi, hi…\n"
	.string "Si tu veux te battre contre nous, un\l"
	.string "seul POKéMON ne suffira pas!$"

Route114_Text_29AF89: @ 829AF89
	.string "IVY: Qui t'a appris ce que tu sais\n"
	.string "sur les POKéMON?$"

Route114_Text_29AFAC: @ 829AFAC
	.string "IVY: Etonnante façon de se battre!$"

Route114_Text_29AFCF: @ 829AFCF
	.string "IVY: J'ai commencé à entraîner des\n"
	.string "POKéMON parce que TYRA, mon cher\l"
	.string "professeur, me l'a enseigné!$"

Route114_Text_29B01B: @ 829B01B
	.string "IVY: Tu n'as qu'un seul POKéMON?\n"
	.string "Il doit se sentir seul.$"

Route114_Text_29B05D: @ 829B05D
	.string "J'en ai attrapé un gros!\n"
	.string "Un gros, je te dis!$"

Route114_Text_29B089: @ 829B089
	.string "Quoi la taille?\n"
	.string "Le mien a perdu à cause de sa taille?$"

Route114_Text_29B0B5: @ 829B0B5
	.string "OK…\n"
	.string "Je vais en attraper un plus gros!$"

Route114_Text_29B0DB: @ 829B0DB
	.string "Moi, je n'ai pas qu'un joli minois!$"

Route114_Text_29B0FB: @ 829B0FB
	.string "C'était pas mignon de ta part!$"

Route114_Text_29B11A: @ 829B11A
	.string "Je ne veux pas de POKéMON qui soient\n"
	.string "seulement mignons.\p"
	.string "Ils doivent avoir un petit je ne sais\n"
	.string "quoi en plus!$"

Route114_Text_29B16F: @ 829B16F
	.string "As-tu bien fait évoluer tes POKéMON?$"

Route114_Text_29B19C: @ 829B19C
	.string "Oh, je vois…\n"
	.string "C'est bon à savoir!$"

Route114_Text_29B1BC: @ 829B1BC
	.string "Certains POKéMON changent\n"
	.string "radicalement en évoluant,\l"
	.string "c'est vraiment impressionnant!$"

Route115_Text_29B1FA: @ 829B1FA
	.string "Hum…\n"
	.string "Tu as l'air tout à fait capable…\l"
	.string "Laisse-moi te tenir compagnie!$"

Route115_Text_29B230: @ 829B230
	.string "Tu as plus de puissance que je ne\n"
	.string "l'avais imaginé!$"

Route115_Text_29B258: @ 829B258
	.string "Rien n'est inné!\n"
	.string "Tout s'acquiert par le travail!\l"
	.string "C'est ce que je crois…$"

Route115_Text_29B2B3: @ 829B2B3
	.string "Hmm… Cette défaite est un vieux\n"
	.string "souvenir pour moi.\p"
	.string "Si tu le permets, j'aimerais bien avoir\n"
	.string "ma revanche!$"

Route115_Text_29B32C: @ 829B32C
	.string "Hum… Comme toujours, ton agilité\n"
	.string "parle d'elle-même.\l"
	.string "Viens me tenir compagnie!$"

Route115_Text_29B372: @ 829B372
	.string "Plus de force que jamais!$"

Route115_Text_29B385: @ 829B385
	.string "Tout est une question d'efforts!\p"
	.string "J'ai perdu parce que je n'ai pas fait\n"
	.string "assez d'efforts!$"

Route115_Text_29B3CC: @ 829B3CC
	.string "Toi!\n"
	.string "Mes MACHOC!\p"
	.string "J'exige un combat!$"

Route115_Text_29B3ED: @ 829B3ED
	.string "Oh là là!$"

Route115_Text_29B3FF: @ 829B3FF
	.string "Mon équipe de MACHOC!\p"
	.string "Tant qu'ils chercheront la puissance, je\n"
	.string "m'endurcirai avec eux!$"

Route115_Text_29B449: @ 829B449
	.string "Mon plus grand talent, c'est de pouvoir\n"
	.string "casser des briques avec mon front!$"

Route115_Text_29B480: @ 829B480
	.string "Aaaaaaaah!\n"
	.string "J'ai la tête en vrac!$"

Route115_Text_29B49D: @ 829B49D
	.string "J'ai appris le karaté à mon POKéMON.\p"
	.string "On dirait que ça lui profite plus qu'à\n"
	.string "moi. Je m'en réjouis.$"

Route115_Text_29B50B: @ 829B50B
	.string "Tu m'impressionnes! Je prendrai ma\n"
	.string "revanche après mon entraînement!$"

Route115_Text_29B547: @ 829B547
	.string "Après que tu m'as battu, on s'est\n"
	.string "entraînés dur pour s'améliorer…\p"
	.string "Viens, on veut prendre notre revanche!$"

Route115_Text_29B59D: @ 829B59D
	.string "Arrrrg!\n"
	.string "On a encore perdu!$"

Route115_Text_29B5B5: @ 829B5B5
	.string "Mon POKéMON va devenir plus fort!\n"
	.string "Je renforce mon entraînement!$"

Route115_Text_29B5EF: @ 829B5EF
	.string "Cette plage est le camp secret où je\n"
	.string "m'entraîne! Ne viens pas me déranger!$"

Route115_Text_29B62D: @ 829B62D
	.string "Je ne me suis pas assez entraînée!$"

Route115_Text_29B647: @ 829B647
	.string "Le sable est comme un coussin qui\n"
	.string "amortit les chocs et qui empêche de\l"
	.string "se faire mal.\p"
	.string "C'est l'endroit idéal pour s'entraîner.$"

Route115_Text_29B6AB: @ 829B6AB
	.string "Bien… Tu es libre de venir.\n"
	.string "En retour, j'aimerais t'affronter de\l"
	.string "nouveau.$"

Route115_Text_29B6FA: @ 829B6FA
	.string "OK, que le combat commence!$"

Route115_Text_29B71A: @ 829B71A
	.string "Je peux me battre, mais mes POKéMON…$"

Route115_Text_29B737: @ 829B737
	.string "Lorsque je perds, j'en tire quand même\n"
	.string "un certain plaisir.\p"
	.string "Ça doit être que j'aime mes POKéMON.$"

Route115_Text_29B78F: @ 829B78F
	.string "J'ai un POKéMON rare!\n"
	.string "Tu voudrais le voir?$"

Route115_Text_29B7C5: @ 829B7C5
	.string "Tu…\n"
	.string "Tu veux mon POKéMON, c'est ça?$"

Route115_Text_29B7EA: @ 829B7EA
	.string "J'ai ce POKéMON rare.\n"
	.string "Je ne le céderai pas.$"

Route115_Text_29B826: @ 829B826
	.string "Je vais me battre en courant!\n"
	.string "Essaie de me rattraper!$"

Route115_Text_29B85D: @ 829B85D
	.string "J'ai un point de côté…$"

Route115_Text_29B869: @ 829B869
	.string "J'ai fait l'erreur de vouloir me battre\n"
	.string "en courant!\p"
	.string "Je devrais faire une course pour me\n"
	.string "calmer!$"

Route115_Text_29B8C1: @ 829B8C1
	.string "Prends ça!\n"
	.string "Attaque ninja ultra POKéMON!$"

Route115_Text_29B8E8: @ 829B8E8
	.string "Ouaaah!\n"
	.string "Ma stratégie n'était pas la bonne!$"

Route115_Text_29B904: @ 829B904
	.string "Mais mes POKéMON étaient\n"
	.string "super géniaux, non?$"

Route115_Text_29B92D: @ 829B92D
	.string "Mes POKéMON mériteraient d'avoir\n"
	.string "une ceinture noire!$"

Route115_Text_29B958: @ 829B958
	.string "Quelle humiliation!$"

Route115_Text_29B971: @ 829B971
	.string "J'ai rarement vu quelqu'un d'aussi\n"
	.string "fort que moi…\p"
	.string "J'ai compris!\n"
	.string "Tu dois être un CHAMPION D'ARENE,\l"
	.string "n'est-ce pas?$"

Route115_Text_29B9CB: @ 829B9CB
	.string "Tu oses croiser mon regard?\n"
	.string "Pas d'échappatoire pour toi!$"

Route115_Text_29B9F6: @ 829B9F6
	.string "Gaaah!\n"
	.string "Pas mal!$"

Route115_Text_29BA04: @ 829BA04
	.string "Très bien!\p"
	.string "Je vais me TELEPORTER à la\n"
	.string "maison!$"

Route115_Text_29BA2C: @ 829BA2C
	.string "Tu déranges ma méditation…\n"
	.string "Je vais te le faire payer!$"

Route115_Text_29BA67: @ 829BA67
	.string "Tu as brisé ma concentration!$"

Route115_Text_29BA87: @ 829BA87
	.string "Je méditais avec mes POKéMON.\n"
	.string "Mais ce n'est pas l'endroit idéal…$"

Route116_Text_29BACD: @ 829BACD
	.string "S'il n'y a pas de tunnel de construit,\n"
	.string "alors je passerai par en haut.$"

Route116_Text_29BB0F: @ 829BB0F
	.string "Pfou… Pfou…\n"
	.string "Ça fatigue de perdre…$"

Route116_Text_29BB31: @ 829BB31
	.string "C'est pas grave s'il n'y a pas de tunnel.\n"
	.string "Un MONTAGNARD passe par les montagnes!$"

Route116_Text_29BB79: @ 829BB79
	.string "Mon POKéMON est le roi!\n"
	.string "Regarde un peu!$"

Route116_Text_29BB9A: @ 829BB9A
	.string "Aïe! Une coupure!\n"
	.string "Il faut que je mette un pansement!$"

Route116_Text_29BBC6: @ 829BBC6
	.string "Les pansements prouvent la résistance\n"
	.string "au combat! J'en ai un autre!$"

Route116_Text_29BBFD: @ 829BBFD
	.string "Mes POKéMON INSECTE sont résistants!\n"
	.string "Battons-nous!$"

Route116_Text_29BC25: @ 829BC25
	.string "J'ai perdu!\n"
	.string "Je croyais pouvoir te vaincre!$"

Route116_Text_29BC42: @ 829BC42
	.string "Les POKéMON INSECTE évoluent vite.\n"
	.string "Alors ils deviennent vite forts aussi.$"

Route116_Text_29BC7F: @ 829BC7F
	.string "Laisse-moi te montrer comme mon\n"
	.string "adorable POKéMON est fort!$"

Route116_Text_29BCB3: @ 829BCB3
	.string "Tu joues dans la catégorie supérieure…$"

Route116_Text_29BCCC: @ 829BCCC
	.string "Je trouve que l'idéal pour un POKéMON,\n"
	.string "c'est de mêler charme et puissance.$"

Route116_Text_29BD0C: @ 829BD0C
	.string "On apprend toutes sortes de choses à\n"
	.string "l'ECOLE DE DRESSEURS.\p"
	.string "Je veux mettre tout ça en pratique!$"

Route116_Text_29BD66: @ 829BD66
	.string "Je me suis un peu relâché à l'école…\n"
	.string "C'est pour ça que j'ai perdu.$"

Route116_Text_29BD92: @ 829BD92
	.string "Je vais devoir reprendre des cours à\n"
	.string "l'ECOLE DE DRESSEURS.\p"
	.string "Sinon, ROXANNE va pester.$"

Route116_Text_29BDEF: @ 829BDEF
	.string "J'ai appris à l'ECOLE DE DRESSEURS\n"
	.string "que les POKéNAVS peuvent enregistrer\l"
	.string "les DRESSEURS.\p"
	.string "Je sais pas vraiment comment ça marche,\n"
	.string "tu me laisses essayer?$"

Route116_Text_29BE71: @ 829BE71
	.string "J'ai appris à l'ECOLE DE DRESSEURS\n"
	.string "que les POKéNAVS peuvent enregistrer\l"
	.string "les DRESSEURS.\p"
	.string "Je sais pas vraiment comment ça marche,\n"
	.string "tu me laisses essayer?$"

Route116_Text_29BEF3: @ 829BEF3
	.string "J'ai étudié sérieusement à l'ECOLE\n"
	.string "DE DRESSEURS.\p"
	.string "Cette fois, je ne vais pas perdre.$"

Route116_Text_29BF4C: @ 829BF4C
	.string "Hum?\n"
	.string "J'ai étudié avec assiduité.$"

Route116_Text_29BF68: @ 829BF68
	.string "Je vais devoir reprendre des cours à\n"
	.string "l'ECOLE DE DRESSEURS.\p"
	.string "Sinon, ROXANNE va pester.$"

Route116_Text_29BFC5: @ 829BFC5
	.string "J'étudie à l'école et j'étudie aussi\n"
	.string "en rentrant chez moi!$"

Route116_Text_29BFFA: @ 829BFFA
	.string "Quel choc! J'ai perdu?$"

Route116_Text_29C010: @ 829C010
	.string "C'est pas comme ça que je vais devenir\n"
	.string "un DRESSEUR avec autant de charme\l"
	.string "que ROXANNE!$"

Route116_Text_29C052: @ 829C052
	.string "Oh, waouh! C'est un POKéNAV?\n"
	.string "J'en ai un aussi!\p"
	.string "Laisse-moi t'enregistrer!$"

Route116_Text_29C096: @ 829C096
	.string "Oh, waouh! C'est un POKéNAV?\n"
	.string "J'en ai un aussi!\p"
	.string "Laisse-moi t'enregistrer!$"

Route116_Text_29C0DA: @ 829C0DA
	.string "J'ai beaucoup appris depuis la dernière\n"
	.string "fois. Il faut que tu voies mes progrès!$"

Route116_Text_29C11F: @ 829C11F
	.string "Quel choc! J'ai encore perdu?$"

Route116_Text_29C13B: @ 829C13B
	.string "Tu as battu ROXANNE? Je ne vais pas\n"
	.string "pouvoir te battre alors. Pas encore.$"

Route116_Text_29C173: @ 829C173
	.string "Pour ta gouverne, personne n'a jamais\n"
	.string "pu me vaincre, personne!$"

Route116_Text_29C1B8: @ 829C1B8
	.string "Eh bien, quelle expérience troublante…$"

Route116_Text_29C1EA: @ 829C1EA
	.string "J'ai les moyens de m'offrir tout ce\n"
	.string "que je souhaite!\p"
	.string "Mais pour les POKéMON, ma fortune\n"
	.string "ne me sert à rien.$"

Route116_Text_29C266: @ 829C266
	.string "Si tu poses les yeux sur mes POKéMON,\n"
	.string "leur beauté te laissera le souffle\l"
	.string "coupé, j'en suis certain!$"

Route116_Text_29C2C2: @ 829C2C2
	.string "Oh, dis-moi que ça n'est pas vrai!$"

Route116_Text_29C2DD: @ 829C2DD
	.string "Oh, non, non, non!\n"
	.string "Tu as abîmé la fourrure de mes POKéMON!\p"
	.string "Et aussi mon brushing! Je n'ai plus\n"
	.string "qu'à appeler mon styliste!$"

Route116_Text_29C350: @ 829C350
	.string "T'as pris tes chaussures de marche?$"

Route116_Text_29C365: @ 829C365
	.string "Aïe aïe aïe!$"

Route116_Text_29C380: @ 829C380
	.string "Je devrais essayer d'autres types de\n"
	.string "POKéMON…\l"
	.string "C'est ce que je devrais faire…$"

Route116_Text_29C3C1: @ 829C3C1
	.string "C'est une voie sans issue.\n"
	.string "Je m'ennuie… On se bat?$"

Route116_Text_29C3F7: @ 829C3F7
	.string "C'était vraiment marrant…\n"
	.string "Même si j'ai perdu…$"

Route116_Text_29C418: @ 829C418
	.string "Tu voudrais pas rester ici pour me\n"
	.string "tenir compagnie?$"

Route117_Text_29C43F: @ 829C43F
	.string "Ecoute, tu pourrais te battre contre\n"
	.string "les POKéMON que j'élève?$"

Route117_Text_29C47A: @ 829C47A
	.string "Tu as très bien élevé les tiens…$"

Route117_Text_29C498: @ 829C498
	.string "Les POKéMON, ce n'est pas qu'une\n"
	.string "question de force.\p"
	.string "Parfaire la particularité d'une\n"
	.string "personnalité, c'est une autre façon\l"
	.string "d'apprécier les POKéMON.$"

Route117_Text_29C508: @ 829C508
	.string "Je vais m'entraîner deux fois plus.\n"
	.string "Tu viendras me voir?$"

Route117_Text_29C549: @ 829C549
	.string "Les POKéMON que j'élève ont l'air en\n"
	.string "forme, exactement comme avant.$"

Route117_Text_29C58B: @ 829C58B
	.string "Tu sais les élever comme il faut.\n"
	.string "Tu pourrais tenir une PENSION…$"

Route117_Text_29C5D0: @ 829C5D0
	.string "Tes POKéMON grandissent bien!\n"
	.string "Tu devrais les inscrire à des CONCOURS.$"

Route117_Text_29C612: @ 829C612
	.string "Tu permets que je vérifie si tes\n"
	.string "POKéMON se développent bien?$"

Route117_Text_29C659: @ 829C659
	.string "Oui, ils grandissent bien.$"

Route117_Text_29C679: @ 829C679
	.string "Essaie d'élever tes POKéMON en faisant\n"
	.string "attention à leurs traits de caractère.$"

Route117_Text_29C6BC: @ 829C6BC
	.string "Je suis contente d'avoir rencontré un\n"
	.string "DRESSEUR comme toi.\p"
	.string "J'espère qu'on se reverra!$"

Route117_Text_29C6FD: @ 829C6FD
	.string "Tu permets que je revérifie si tu as\n"
	.string "bien élevé tes POKéMON?$"

Route117_Text_29C73E: @ 829C73E
	.string "Ils se développent admirablement bien.$"

Route117_Text_29C75A: @ 829C75A
	.string "Les POKéMON aiment différentes sortes\n"
	.string "de {POKEBLOCK}S selon leur nature.$"

Route117_Text_29C7A5: @ 829C7A5
	.string "Je suis en plein milieu d'un triathlon,\n"
	.string "mais tant pis, battons-nous!$"

Route117_Text_29C7EB: @ 829C7EB
	.string "Je n'ai plus du tout de force!$"

Route117_Text_29C800: @ 829C800
	.string "J'aurais pu te balayer…\p"
	.string "J'aurais peut-être dû ralentir le\n"
	.string "rythme pour tenir sur la durée…$"

Route117_Text_29C846: @ 829C846
	.string "Les POKéMON aussi doivent être forts?\n"
	.string "Tu veux bien devenir mon entraîneur?$"

Route117_Text_29C880: @ 829C880
	.string "On n'est qu'à la moitié du triathlon et\n"
	.string "je suis claqué, mais je suis en tête.\p"
	.string "Affrontons-nous!$"

Route117_Text_29C8E3: @ 829C8E3
	.string "Je suis encore à bout de forces!$"

Route117_Text_29C8FE: @ 829C8FE
	.string "Je suis au top à la natation et en\n"
	.string "cyclisme, mais je ne suis pas aussi\l"
	.string "confiant pour les POKéMON.$"

Route117_Text_29C955: @ 829C955
	.string "Je fais du triathlon avec mon POKéMON,\n"
	.string "alors je suis confiante pour la vitesse.$"

Route117_Text_29C9A6: @ 829C9A6
	.string "Je crois qu'il me faut plus de\n"
	.string "pratique.$"

Route117_Text_29C9D0: @ 829C9D0
	.string "L'entraînement n'a de sens que s'il est\n"
	.string "pratiqué régulièrement.\p"
	.string "OK! Je me remets à l'entraînement!\n"
	.string "Dès demain!$"

Route117_Text_29CA32: @ 829CA32
	.string "Ton entraînement a l'air d'être\n"
	.string "vraiment efficace…\p"
	.string "On s'affrontera plus tard si tu\n"
	.string "veux bien!$"

Route117_Text_29CA7C: @ 829CA7C
	.string "Tu continues à t'entraîner?\n"
	.string "Moi, oui!\l"
	.string "Laisse-moi te le prouver!$"

Route117_Text_29CACC: @ 829CACC
	.string "Je crois qu'il me faut plus de\n"
	.string "pratique.$"

Route117_Text_29CAF6: @ 829CAF6
	.string "Demain, je me remets à l'entraînement.\n"
	.string "On se rebattra bien un jour ou l'autre!$"

Route117_Text_29CB32: @ 829CB32
	.string "Hier un SCOUT…\n"
	.string "et maintenant un ENTOMOMANIAC!\p"
	.string "Mais mon amour pour les POKéMON\n"
	.string "reste intact!$"

Route117_Text_29CB87: @ 829CB87
	.string "Mon incompétence, elle aussi,\n"
	.string "est toujours intacte…$"

Route117_Text_29CBAD: @ 829CBAD
	.string "Je n'ai fait que suivre mon cœur, et me\n"
	.string "voilà considéré comme un ENTOMOMANIAC.\p"
	.string "Enfin, étant un expert en POKéMON\n"
	.string "INSECTE, c'est normal qu'on me\l"
	.string "considère comme un ENTOMOMANIAC.$"

Route117_Text_29CC4A: @ 829CC4A
	.string "ANNA: Je suis avec ma charmante\n"
	.string "partenaire. Je dois être à la hauteur!$"

Route117_Text_29CC8E: @ 829CC8E
	.string "ANNA: Je suis avec ma charmante\n"
	.string "partenaire! Tu aurais pû me laisser\l"
	.string "gagner!$"

Route117_Text_29CCCB: @ 829CCCB
	.string "ANNA: Tes POKéMON se complètent\n"
	.string "bien.\p"
	.string "Je dirais que tu es juste derrière nous!$"

Route117_Text_29CD1D: @ 829CD1D
	.string "ANNA: On ne peut pas en rester là!\n"
	.string "Tu reviendras, hein?$"

Route117_Text_29CD61: @ 829CD61
	.string "ANNA: Si tu veux nous affronter,\n"
	.string "prends deux POKéMON avec toi.$"

Route117_Text_29CD9D: @ 829CD9D
	.string "EVA: On va s'accrocher avec ma\n"
	.string "partenaire de choc et on va t'écraser!$"

Route117_Text_29CDE9: @ 829CDE9
	.string "EVA: Oh, non!\n"
	.string "ANNA, je suis désolée de te\l"
	.string "décevoir…$"

Route117_Text_29CE17: @ 829CE17
	.string "MEG: I dragged ANNA down…\n"
	.string "If I didn't, she would have won!$"

Route117_Text_29CE52: @ 829CE52
	.string "EVA: Tu n'as qu'un seul POKéMON?\n"
	.string "Alors on ne va pas pouvoir s'affronter.\p"
	.string "On veut combattre en 2 contre 2.$"

Route117_Text_29CEB6: @ 829CEB6
	.string "ANNA: Je ne peux pas continuer à\n"
	.string "perdre devant ma partenaire, pas vrai?$"

Route117_Text_29CEF6: @ 829CEF6
	.string "ANNA: Je n'ai pas trouvé mon rythme.$"

Route117_Text_29CF1C: @ 829CF1C
	.string "ANNA: Tes POKéMON se complètent\n"
	.string "bien.\p"
	.string "Je dirais que tu es juste derrière nous!$"

Route117_Text_29CF6E: @ 829CF6E
	.string "ANNA: Si tu veux nous affronter,\n"
	.string "prends deux POKéMON avec toi.$"

Route117_Text_29CFAA: @ 829CFAA
	.string "EVA: On va s'accrocher avec ma\n"
	.string "partenaire et cette fois, on va gagner!$"

Route117_Text_29CFED: @ 829CFED
	.string "EVA: Trop balèze pour nous!$"

Route117_Text_29CFFE: @ 829CFFE
	.string "EVA: On s'est battues avec ma\n"
	.string "partenaire, mais on a perdu…\p"
	.string "C'est décourageant…$"

Route117_Text_29D053: @ 829D053
	.string "EVA: Tu n'as qu'un seul POKéMON?\n"
	.string "Alors on ne va pas pouvoir s'affronter.\p"
	.string "On veut combattre en 2 contre 2.$"

Route117_Text_29D0B7: @ 829D0B7
	.string "C'est sympa, hein? Se battre tout en\n"
	.string "regardant les jolies fleurs!$"

Route117_Text_29D0F1: @ 829D0F1
	.string "Oh, c'était très impressionnant!$"

Route117_Text_29D10E: @ 829D10E
	.string "Rien de mieux qu'un petit jogging en\n"
	.string "pleine nature.$"

Route117_Text_29D14B: @ 829D14B
	.string "Laisse-moi te montrer la force cachée\n"
	.string "des POKéMON PSY!$"

Route117_Text_29D189: @ 829D189
	.string "Etonnant!$"

Route117_Text_29D196: @ 829D196
	.string "Les POKéMON PSY sont complexes.\n"
	.string "Tu devrais essayer d'en attraper.$"

Route117_Text_29D1D1: @ 829D1D1
	.string "Se concentrer sur la victoire!\n"
	.string "C'est le secret d'un combat réussi!$"

Route117_Text_29D206: @ 829D206
	.string "Je ne me morfonds jamais en cas de\n"
	.string "défaite… Je retourne m'entraîner!$"

Route117_Text_29D24C: @ 829D24C
	.string "Si tu penses trop à la défaite, tu as\n"
	.string "plus de chances de perdre.$"

Route118_Text_29D290: @ 829D290
	.string "Le parfum des fleurs a un pouvoir\n"
	.string "magique. Il purifie le corps et l'esprit.$"

Route118_Text_29D2D8: @ 829D2D8
	.string "Oh là là!\n"
	.string "On dirait bien que j'ai perdu.$"

Route118_Text_29D2FA: @ 829D2FA
	.string "Les fleurs, les POKéMON…\n"
	.string "J'aime tout ce qui sent bon.\p"
	.string "Tout ce qui pue…\n"
	.string "C'est pas pour moi!$"

Route118_Text_29D343: @ 829D343
	.string "Sniff… Cette odeur…\n"
	.string "C'est un POKéNAV!\p"
	.string "Tu veux bien qu'on échange nos\n"
	.string "numéros?$"

Route118_Text_29D382: @ 829D382
	.string "Est-ce ce doux parfum qui t'a fait\n"
	.string "venir ici?$"

Route118_Text_29D3AA: @ 829D3AA
	.string "Le pouvoir du parfum…\n"
	.string "Ça n'a pas changé grand-chose.$"

Route118_Text_29D3D9: @ 829D3D9
	.string "Si tu sais bien utiliser un doux parfum,\n"
	.string "tu peux attirer les POKéMON avec.$"

Route118_Text_29D41D: @ 829D41D
	.string "Les POKéMON OISEAU qui volent\n"
	.string "avec grâce dans le ciel,\l"
	.string "ce sont les meilleurs!$"

Route118_Text_29D45B: @ 829D45B
	.string "Arrg… Je me suis fait écraser…$"

Route118_Text_29D46C: @ 829D46C
	.string "Tu es vraiment balèze! Je vais devoir\n"
	.string "perfectionner mon entraînement.$"

Route118_Text_29D4A6: @ 829D4A6
	.string "Prenez votre envol!\n"
	.string "Mes POKéMON OISEAU!$"

Route118_Text_29D4C4: @ 829D4C4
	.string "Ils ont effectivement pris leur envol…$"

Route118_Text_29D4DA: @ 829D4DA
	.string "S'ils étaient plus forts, ils pourraient\n"
	.string "voler plus librement…$"

Route118_Text_29D515: @ 829D515
	.string "Je suis PECHEUR, mais aussi DRESSEUR.\n"
	.string "J'élève les POKéMON que j'attrape.$"

Route118_Text_29D55C: @ 829D55C
	.string "Je croyais pourtant que je m'entraînais\n"
	.string "correctement…$"

Route118_Text_29D587: @ 829D587
	.string "Je ne pourrai pas gagner si j'entraîne\n"
	.string "mes POKéMON tout en pêchant…\p"
	.string "Ça voudrait dire que je ne fais les\n"
	.string "choses qu'à moitié?$"

Route118_Text_29D5DF: @ 829D5DF
	.string "Pour les PECHEURS, le matériel est\n"
	.string "la clé de tout.\p"
	.string "Mais l'essentiel pour les DRESSEURS,\n"
	.string "ce sont les POKéMON et le cœur!$"

Route118_Text_29D64C: @ 829D64C
	.string "Ai-je été touché en plein cœur?$"

Route118_Text_29D663: @ 829D663
	.string "Si tu y penses, la pêche c'est comme un\n"
	.string "combat entre un PECHEUR et un POKéMON.$"

Route118_Text_29D6AF: @ 829D6AF
	.string "Laisse ma mélodie bercer ton âme!$"

Route118_Text_29D6CD: @ 829D6CD
	.string "La, lalala…$"

Route118_Text_29D6D8: @ 829D6D8
	.string "Une guitare électrique, ça ne fait pas\n"
	.string "toujours un bruit terrible…\p"
	.string "On peut pincer les cordes de façon à en\n"
	.string "tirer cette émouvante mélodie…$"

Route118_Text_29D74A: @ 829D74A
	.string "Tu viendras écouter mes prochaines\n"
	.string "compositions?$"

Route118_Text_29D789: @ 829D789
	.string "La mélodie de mes POKéMON et moi…\n"
	.string "Laisse-nous la faire toucher ton âme.$"

Route118_Text_29D7CA: @ 829D7CA
	.string "La, lalala…$"

Route118_Text_29D7D5: @ 829D7D5
	.string "Quand je joue, mes émotions peuvent te\n"
	.string "toucher grâce à ma guitare électrique…$"

Route118_Text_29D81B: @ 829D81B
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, et 3!$"

Route118_Text_29D83C: @ 829D83C
	.string "POKéMON 1, 2, et 3?\n"
	.string "Est-ce que ça va?$"

Route118_Text_29D872: @ 829D872
	.string "C'est cool d'avoir toute une équipe\n"
	.string "de POKéMON pour se battre!\p"
	.string "Tu peux faire comme moi, j't'en\n"
	.string "voudrai pas!$"

Route119_Text_29D8C2: @ 829D8C2
	.string "On est le CLUB COPIE!\n"
	.string "On COPIE ce que tu fais!$"

Route119_Text_29D8F0: @ 829D8F0
	.string "Oups!\n"
	.string "On a perdu!$"

Route119_Text_29D902: @ 829D902
	.string "Qu'y a-t-il de drôle à copier les\n"
	.string "autres?\p"
	.string "Pffffff…\n"
	.string "Tu ne comprendras jamais…$"

Route119_Text_29D941: @ 829D941
	.string "Ah, on se rencontre enfin! Mes POKéMON\n"
	.string "INSECTE vont te tenir compagnie!$"

Route119_Text_29D97C: @ 829D97C
	.string "J'aurais préféré ne pas te rencontrer…$"

Route119_Text_29D993: @ 829D993
	.string "Je voudrais te copier encore un peu.\n"
	.string "Tu peux te dépêcher de bouger?$"

Route119_Text_29D9CD: @ 829D9CD
	.string "Si tu avances, on avance.\n"
	.string "Si tu tournes à droite, on tourne aussi.$"

Route119_Text_29DA14: @ 829DA14
	.string "Mais si tu gagnes, je perds…$"

Route119_Text_29DA2C: @ 829DA2C
	.string "Je ne peux pas copier ta victoire.\n"
	.string "C'est tout bonnement impossible…\l"
	.string "Ça me met en pétard…$"

Route119_Text_29DA7D: @ 829DA7D
	.string "Hé, t'as finalement réussi à m'attraper!\n"
	.string "Mais tu voulais peut-être m'éviter?$"

Route119_Text_29DABC: @ 829DABC
	.string "Ouuuuh, c'était un beau combat!$"

Route119_Text_29DADB: @ 829DADB
	.string "On est le CLUB COPIE!\n"
	.string "J'espère que tu aimes ce qu'on fait.$"

Route119_Text_29DB17: @ 829DB17
	.string "Tu ne sais pas qui je suis, hein?\p"
	.string "Mais je ne te connais pas non plus.\n"
	.string "Alors on va se battre!$"

Route119_Text_29DB66: @ 829DB66
	.string "T'es plutôt balèze!$"

Route119_Text_29DB7C: @ 829DB7C
	.string "On copiera chacun de tes mouvements\n"
	.string "jusqu'à ce que tu partes ailleurs.$"

Route119_Text_29DBC2: @ 829DBC2
	.string "Le CLUB COPIE a été fondé par des\n"
	.string "personnes aimant COPIER les autres.\p"
	.string "A la seconde même où on se rencontre,\n"
	.string "un combat débute!$"

Route119_Text_29DC20: @ 829DC20
	.string "J'abandonne!$"

Route119_Text_29DC2B: @ 829DC2B
	.string "Veux-tu rejoindre notre CLUB COPIE?$"

Route119_Text_29DC4C: @ 829DC4C
	.string "Qui sait toujours comment faire pour\n"
	.string "survivre?\p"
	.string "Nous, les POKéMON RANGERS!$"

Route119_Text_29DC9F: @ 829DC9F
	.string "Je ne connais pas suffisamment de\n"
	.string "choses sur les POKéMON…$"

Route119_Text_29DCC6: @ 829DCC6
	.string "Fuir la civilisation et éveiller\n"
	.string "l'instinct sauvage qui est en nous!\p"
	.string "C'est notre devise!$"

Route119_Text_29DD1C: @ 829DD1C
	.string "J'espère qu'on s'affrontera de nouveau\n"
	.string "et que tu ne te moqueras pas de mon\l"
	.string "manque de connaissances!$"

Route119_Text_29DD62: @ 829DD62
	.string "Je vais faire renaître mon instinct\n"
	.string "sauvage en restant avec les POKéMON.$"

Route119_Text_29DDA5: @ 829DDA5
	.string "Toujours autant de force!$"

Route119_Text_29DDBD: @ 829DDBD
	.string "Crois en tes POKéMON.\n"
	.string "Crois en toi.\p"
	.string "Le reste se fera tout seul.$"

Route119_Text_29DE0F: @ 829DE0F
	.string "Hé, regarde-toi.\p"
	.string "Pour quelqu'un qui part à l'aventure, tu\n"
	.string "voyages drôlement léger.$"

Route119_Text_29DE5D: @ 829DE5D
	.string "Les accidents se produisent quand on\n"
	.string "ne s'y attend pas!$"

Route119_Text_29DE88: @ 829DE88
	.string "Tu voyages léger, mais tu as tout ce\n"
	.string "qu'il te faut.\p"
	.string "Tu es mentalement et physiquement\n"
	.string "au top.$"

Route119_Text_29DEF7: @ 829DEF7
	.string "Est-ce que tu as un POKéNAV?\n"
	.string "C'est un outil indispensable pour\l"
	.string "un DRESSEUR.\p"
	.string "Oh, tu en as un!\n"
	.string "Enregistrons-nous alors!$"

Route119_Text_29DF6B: @ 829DF6B
	.string "Comment se passe ton voyage avec\n"
	.string "tes POKéMON?$"

Route119_Text_29DF92: @ 829DF92
	.string "Il me manque quelque chose…$"

Route119_Text_29DFAF: @ 829DFAF
	.string "En tant que DRESSEUR, tu as\n"
	.string "confiance en tes POKéMON et eux,\l"
	.string "réciproquement, ont confiance en toi.$"

Route119_Text_29E007: @ 829E007
	.string "Le ciel, si vaste, tient une grande\n"
	.string "promesse!\p"
	.string "Rien n'est aussi intense que de voler!$"

Route119_Text_29E063: @ 829E063
	.string "A terre et hors combat!$"

Route119_Text_29E071: @ 829E071
	.string "Mon POKéMON OISEAU m'a permis de\n"
	.string "réaliser mon rêve. Je peux voler!$"

Route119_Text_29E0A5: @ 829E0A5
	.string "Je vais te montrer mon vrai potentiel,\n"
	.string "ainsi que celui de mes POKéMON OISEAU.$"

Route119_Text_29E0E1: @ 829E0E1
	.string "Nous avons manqué de potentiel…$"

Route119_Text_29E0F6: @ 829E0F6
	.string "Tout petit déjà, j'admirais les\n"
	.string "POKéMON OISEAU…$"

Route119_Text_29E134: @ 829E134
	.string "Me cacher dans l'ombre et vivre dans\n"
	.string "l'obscurité… Tel est mon destin.\p"
	.string "J'émerge pour te défier!$"

Route119_Text_29E18D: @ 829E18D
	.string "J'admets la défaite!$"

Route119_Text_29E19D: @ 829E19D
	.string "Les perdants se retirent discrètement\n"
	.string "pour retourner dans l'ombre.\l"
	.string "Ça aussi, c'est le destin…$"

Route119_Text_29E1F5: @ 829E1F5
	.string "Quand on ne se méfie pas, on prend\n"
	.string "le risque de souffrir!$"

Route119_Text_29E22B: @ 829E22B
	.string "Ta force est surprenante!$"

Route119_Text_29E245: @ 829E245
	.string "Mon attaque surprise a échoué…$"

Route119_Text_29E26A: @ 829E26A
	.string "L'arbre cache la forêt!$"

Route119_Text_29E288: @ 829E288
	.string "Je m'incline devant ta supériorité.$"

Route119_Text_29E2A3: @ 829E2A3
	.string "L'arbre cache la forêt!\n"
	.string "Un POKéMON cache un autre POKéMON!\p"
	.string "Il n'y a pas de sens caché derrière ça.$"

Route119_Text_29E30D: @ 829E30D
	.string "Tu m'as parlé…\n"
	.string "Alors tu veux m'affronter!\p"
	.string "Pas de problème! Je vais tester le\n"
	.string "POKéMON que j'ai attrapé en SURFANT!$"

Route119_Text_29E372: @ 829E372
	.string "Je n'ai pas la moindre idée de ce qu'il\n"
	.string "faut pour gagner.$"

Route119_Text_29E3A2: @ 829E3A2
	.string "Monter sur mon POKéMON pour faire\n"
	.string "du SURF…\p"
	.string "Et ensuite, pêcher sur son dos…\p"
	.string "C'est un plaisir indescriptible!$"

Route119_Text_29E3FF: @ 829E3FF
	.string "Je vais exploser mon ampli!\n"
	.string "La victoire est à moi!\l"
	.string "Ça va vibrer, tu vas voir!$"

Route119_Text_29E44F: @ 829E44F
	.string "Tu m'as montré qui est le boss,\n"
	.string "je repars avec mes bosses!$"

Route119_Text_29E492: @ 829E492
	.string "J'ai débranché mon ampli.\n"
	.string "Laisse-moi seul avec ma défaite.$"

Route119_Text_29E4DF: @ 829E4DF
	.string "Hohoho!\n"
	.string "J'adore me battre contre de\l"
	.string "jeunes DRESSEURS!$"

Route119_Text_29E513: @ 829E513
	.string "T'es plutôt incroyable!$"

Route119_Text_29E532: @ 829E532
	.string "Hohoho!\n"
	.string "Je vais continuer de m'entraîner!$"

Route119_Text_29E56F: @ 829E56F
	.string "Où que je sois et quoi que je fasse,\n"
	.string "je garde toujours mon parasol.$"

Route119_Text_29E5B1: @ 829E5B1
	.string "Mais…\n"
	.string "C'est pas juste!$"

Route119_Text_29E5CB: @ 829E5CB
	.string "Tu me demandes si mon parasol\n"
	.string "n'est pas trop lourd?\p"
	.string "Ton SAC est rempli de choses bien\n"
	.string "plus lourdes que ce que je porte.$"

Route120_Text_29E62D: @ 829E62D
	.string "Connais-tu une capacité pouvant\n"
	.string "toucher un POKéMON en vol?$"

Route120_Text_29E665: @ 829E665
	.string "Tu es au-dessus de moi!$"

Route120_Text_29E67A: @ 829E67A
	.string "La capacité VOL est très pratique, tu\n"
	.string "ne trouves pas?\p"
	.string "Presque aucune capacité ne peut\n"
	.string "atteindre un POKéMON en vol.$"

Route120_Text_29E6E3: @ 829E6E3
	.string "Mon POKéMON est fort!\n"
	.string "Et les tiens?$"

Route120_Text_29E70A: @ 829E70A
	.string "Tes POKéMON étaient plus forts…$"

Route120_Text_29E726: @ 829E726
	.string "Si un POKéMON progresse avec\n"
	.string "régularité, on peut compter dessus.$"

Route120_Text_29E75D: @ 829E75D
	.string "Je suis sûr que tu vas progresser.\n"
	.string "Je voudrais t'enregistrer dans mon\l"
	.string "POKéNAV!$"

Route120_Text_29E7AA: @ 829E7AA
	.string "Si un POKéMON progresse avec\n"
	.string "régularité, on peut compter dessus.$"

Route120_Text_29E7E1: @ 829E7E1
	.string "Tes POKéMON sont vraiment très forts.$"

Route120_Text_29E804: @ 829E804
	.string "Mes POKéMON deviennent plus forts.\n"
	.string "Moi aussi je dois devenir plus fort!$"

Route120_Text_29E843: @ 829E843
	.string "Je vais vérifier si tes POKéMON sont\n"
	.string "prêts à prendre le grand air.$"

Route120_Text_29E884: @ 829E884
	.string "Avec des POKéMON aussi forts que ça,\n"
	.string "tu ne risques pas d'avoir besoin d'aide!$"

Route120_Text_29E8C5: @ 829E8C5
	.string "Voyager au gré de ses envies avec ses\n"
	.string "POKéMON…\p"
	.string "C'est le privilège d'être DRESSEUR.$"

Route120_Text_29E91C: @ 829E91C
	.string "Comment te sens-tu? Si tu n'es pas\n"
	.string "en pleine forme, ça peut être difficile\l"
	.string "dans les moments critiques.$"

Route120_Text_29E980: @ 829E980
	.string "Je suis en pleine forme, et pourtant…$"

Route120_Text_29E996: @ 829E996
	.string "J'ai l'habitude de faire de l'exercice.\n"
	.string "Je cours toujours avec mes POKéMON.$"

Route120_Text_29E9D7: @ 829E9D7
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu veux te battre?$"

Route120_Text_29E9FF: @ 829E9FF
	.string "Vaincu…$"

Route120_Text_29EA08: @ 829EA08
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Je vais essayer de faire mieux…$"

Route120_Text_29EA31: @ 829EA31
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu as un POKéNAV…?$"

Route120_Text_29EA61: @ 829EA61
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu veux encore te battre?$"

Route120_Text_29EA8F: @ 829EA8F
	.string "… … … … … …\n"
	.string "J'ai encore perdu…$"

Route120_Text_29EAA9: @ 829EAA9
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Je vais essayer de faire mieux…\l"
	.string "Pour mes précieux POKéMON INSECTE…$"

Route120_Text_29EAEF: @ 829EAEF
	.string "Les POKéMON ont de nombreuses\n"
	.string "capacités spéciales. Pour devenir un\l"
	.string "des meilleurs DRESSEURS, renseigne-toi.$"

Route120_Text_29EB53: @ 829EB53
	.string "T'es manifestement en pleine réflexion.$"

Route120_Text_29EB6E: @ 829EB6E
	.string "Les capacités spéciales des POKéMON\n"
	.string "changeront leur façon de se battre.$"

Route120_Text_29EBAF: @ 829EBAF
	.string "Qui pourrais-tu bien être?\p"
	.string "Peut-être es-tu à la recherche des\n"
	.string "ruines antiques qui, selon la légende,\l"
	.string "pourraient exister?$"

Route120_Text_29EC25: @ 829EC25
	.string "Quelle infâme mésaventure…$"

Route120_Text_29EC41: @ 829EC41
	.string "Ce rocher géant… J'aimerais croire qu'il\n"
	.string "renferme des ruines antiques. Mais il\l"
	.string "n'y a pas d'entrée.$"

Route120_Text_29ECA6: @ 829ECA6
	.string "Pourquoi j'ai ce parasol?\p"
	.string "Je te le dirai si tu réussis à me battre.$"

Route120_Text_29ECEF: @ 829ECEF
	.string "Un parasol ne permet pas d'éviter les\n"
	.string "attaques de POKéMON…$"

Route120_Text_29ED19: @ 829ED19
	.string "Je ne pense pas que la lumière intense\n"
	.string "soit bénéfique à mes POKéMON.\l"
	.string "Alors je les protège avec mon parasol.$"

Route120_Text_29ED71: @ 829ED71
	.string "Mon POKéMON, mon parasol et moi…\p"
	.string "Si l'un d'entre nous manque, la\n"
	.string "représentation de la beauté est ternie.$"

Route120_Text_29EDD3: @ 829EDD3
	.string "Tu as complètement terni ma beauté…$"

Route120_Text_29EDF7: @ 829EDF7
	.string "Un parasol, ça ne t'irait pas du tout.\n"
	.string "Ça ne ferait que t'encombrer…$"

Route120_Text_29EE50: @ 829EE50
	.string "Je vais adopter les mouvements des\n"
	.string "POKéMON et créer des techniques ninja.$"

Route120_Text_29EE97: @ 829EE97
	.string "La création de nouvelles techniques\n"
	.string "ninja n'est qu'un rêve…$"

Route120_Text_29EED4: @ 829EED4
	.string "J'aurais peut-être dû suivre les\n"
	.string "enseignements d'un maître ninja.$"

Route120_Text_29EF08: @ 829EF08
	.string "Nous, les ninjas, on se dissimule\n"
	.string "derrière nos capes de camouflage.\p"
	.string "Je parie que tu ne savais pas où\n"
	.string "j'étais!$"

Route120_Text_29EF63: @ 829EF63
	.string "J'ai perdu!\n"
	.string "Je vais devoir dissimuler ma honte!$"

Route120_Text_29EF89: @ 829EF89
	.string "Nos capes de camouflage sont toutes\n"
	.string "faites à la main.$"

Route120_Text_29EFB1: @ 829EFB1
	.string "Si tu ne fais pas attention, tu pourrais\n"
	.string "te faire mal!$"

Route120_Text_29EFE1: @ 829EFE1
	.string "Ouch!\n"
	.string "C'est moi qui me suis fait mal!$"

Route120_Text_29F002: @ 829F002
	.string "Je me demande… Dois-je faire évoluer\n"
	.string "mes POKéMON?\p"
	.string "Je les trouve mignons comme ils sont.$"

Route120_Text_29F04F: @ 829F04F
	.string "Ton équipe de POKéMON…\n"
	.string "Est-ce que tu as d'autres types?$"

Route120_Text_29F080: @ 829F080
	.string "J'ai bien compris ta façon de te battre!$"

Route120_Text_29F0A1: @ 829F0A1
	.string "Rien de mieux que de se battre avec\n"
	.string "ses POKéMON préférés!$"

Route121_Text_29F0EC: @ 829F0EC
	.string "Tu veux jouer avec mon adorable\n"
	.string "POKéMON?$"

Route121_Text_29F11F: @ 829F11F
	.string "Ce n'est pas ce que je voulais dire!$"

Route121_Text_29F138: @ 829F138
	.string "Je vais à un CONCOURS à NENUCRIQUE.\p"
	.string "Mon POKéMON ne devrait avoir aucun\n"
	.string "problème à se distinguer en MASTER.$"

Route121_Text_29F199: @ 829F199
	.string "Avec les POKéMON, j'ai voyagé aux\n"
	.string "quatre coins du monde.\p"
	.string "Tu dois te dire que je suis confiant\n"
	.string "en ce qui concerne mes compétences.$"

Route121_Text_29F20D: @ 829F20D
	.string "Ah, bien joué!$"

Route121_Text_29F21E: @ 829F21E
	.string "J'aimerais bien refaire le tour du globe!$"

Route121_Text_29F25B: @ 829F25B
	.string "Les prouesses de tes POKéMON sont\n"
	.string "remarquables. Permets-moi de\l"
	.string "t'enregistrer dans mon POKéNAV.$"

Route121_Text_29F2A6: @ 829F2A6
	.string "Avec les POKéMON, j'ai voyagé aux\n"
	.string "quatre coins du monde.\p"
	.string "Tu dois te dire que je suis confiant\n"
	.string "en ce qui concerne mes compétences.$"

Route121_Text_29F31A: @ 829F31A
	.string "Ah, bien joué!$"

Route121_Text_29F32B: @ 829F32B
	.string "Tes POKéMON et toi…\p"
	.string "La prouesse que vous avez accomplie\n"
	.string "va être reconnue par-delà les mers.$"

Route121_Text_29F381: @ 829F381
	.string "Dans ce monde, il existe des pouvoirs\n"
	.string "qui dépassent notre entendement…$"

Route121_Text_29F3B9: @ 829F3B9
	.string "J'ai perdu…$"

Route121_Text_29F3C6: @ 829F3C6
	.string "MONT MEMORIA…\n"
	.string "Là, un mystérieux pouvoir est\l"
	.string "en action…$"

Route121_Text_29F3FB: @ 829F3FB
	.string "VIVI: Ensemble, on ne connaît pas la\n"
	.string "peur! Tu vas voir comme on est fortes!$"

Route121_Text_29F43F: @ 829F43F
	.string "VIVI: Je vais tout balayer devant\n"
	.string "ma petite protégée…$"

Route121_Text_29F476: @ 829F476
	.string "VIVI: Quand quelqu'un a confiance\n"
	.string "en moi, je me dois de faire preuve d'un\l"
	.string "sang-froid irréprochable…$"

Route121_Text_29F4C9: @ 829F4C9
	.string "VIVI: Si tu n'as qu'un seul POKéMON,\n"
	.string "on ne peut pas s'affronter.\p"
	.string "Ce serait de la folie!$"

Route121_Text_29F521: @ 829F521
	.string "BEA: Ensemble, on ne connaît pas la\n"
	.string "peur. Tu vas voir comme on est fortes!$"

Route121_Text_29F564: @ 829F564
	.string "BEA: Pardonne-moi, VIVI!$"

Route121_Text_29F582: @ 829F582
	.string "BEA: Il va falloir qu'on s'entraîne\n"
	.string "encore avec VIVI, mon mentor.$"

Route121_Text_29F5CE: @ 829F5CE
	.string "BEA: Il te faut au moins deux\n"
	.string "POKéMON pour pouvoir nous affronter!$"

Route121_Text_29F612: @ 829F612
	.string "Stop! Regarde mes POKéMON!\n"
	.string "De vrais trésors!$"

Route121_Text_29F641: @ 829F641
	.string "Oh, comment oses-tu!\n"
	.string "Ne prends pas ça au sérieux!$"

Route121_Text_29F66F: @ 829F66F
	.string "Je vais peut-être aller attraper\n"
	.string "d'autres POKéMON au PARC SAFARI.$"

Route121_Text_29F69F: @ 829F69F
	.string "Je ne me suis pas donnée à fond cette\n"
	.string "fois! Mais ça ne sera pas la même\l"
	.string "chose la prochaine fois!$"

Route121_Text_29F6E4: @ 829F6E4
	.string "Mes précieux POKéMON ont grandi!\n"
	.string "Regarde!$"

Route121_Text_29F710: @ 829F710
	.string "Oh, comment oses-tu!\n"
	.string "Tu ne vas quand même pas t'énerver!$"

Route121_Text_29F740: @ 829F740
	.string "Je vais peut-être aller attraper\n"
	.string "d'autres POKéMON au PARC SAFARI.$"

Route121_Text_29F770: @ 829F770
	.string "J'ai pour habitude de battre cinq\n"
	.string "DRESSEURS par jour…\p"
	.string "Et devine quoi! Tu es le numéro cinq!$"

Route121_Text_29F7C1: @ 829F7C1
	.string "Non!\n"
	.string "Tu es ignoble!$"

Route121_Text_29F7D4: @ 829F7D4
	.string "Je ne pensais pas perdre aussi\n"
	.string "facilement…\p"
	.string "Mais je gagnerai la prochaine fois!$"

Route121_Text_29F80D: @ 829F80D
	.string "Tu m'as humiliée!\n"
	.string "Je ne t'oublierai pas…\l"
	.string "Fais-moi voir ton POKéNAV!$"

Route121_Text_29F855: @ 829F855
	.string "J'ai pour nouvelle habitude de battre\n"
	.string "dix DRESSEURS par jour…\p"
	.string "Et devine quoi! Tu es le numéro dix!$"

Route121_Text_29F8A8: @ 829F8A8
	.string "Attends! Ça va pas!\n"
	.string "Je demande une revanche!$"

Route121_Text_29F8D0: @ 829F8D0
	.string "Tu es le premier adversaire que je\n"
	.string "ne peux pas battre… Sniff…\p"
	.string "Je ne peux pas croire que ça m'arrive…$"

Route121_Text_29F91A: @ 829F91A
	.string "Tu vois pas que j'ai les mains pleines?\p"
	.string "Et malgré ça, tu insistes pour qu'on\n"
	.string "se batte!$"

Route121_Text_29F97B: @ 829F97B
	.string "Evidemment que j'ai perdu!\n"
	.string "J'ai les deux mains prises!$"

Route121_Text_29F9AE: @ 829F9AE
	.string "J'ai acheté trop d'articles au CENTRE\n"
	.string "COMMERCIAL de NENUCRIQUE.\p"
	.string "Il est juste un peu plus loin.\n"
	.string "Si seulement j'avais un SAC comme\l"
	.string "le tien!$"

Route121_Text_29FA1E: @ 829FA1E
	.string "Pour moi, rien de mieux que de découvrir\n"
	.string "les POKéMON des autres!$"

Route121_Text_29FA64: @ 829FA64
	.string "Super génial!$"

Route121_Text_29FA73: @ 829FA73
	.string "Ils sont super tes POKéMON!\n"
	.string "Comment est-ce que tu les dresses?$"

Route121_Text_29FAA7: @ 829FAA7
	.string "Je veux que tout le monde voie les\n"
	.string "POKéMON que j'ai dressés!$"

Route121_Text_29FAD8: @ 829FAD8
	.string "Waouh!\n"
	.string "Spectaculaire!$"

Route121_Text_29FAEA: @ 829FAEA
	.string "Je dresse chaque POKéMON avec le\n"
	.string "même soin et la même attention.\l"
	.string "Je ne favorise pas ceux que je préfère!$"

Route121_Text_29FB35: @ 829FB35
	.string "Mes POKéMON n'ont jamais connu la\n"
	.string "défaite! Encore une victoire et je les\l"
	.string "inscris à un CONCOURS!$"

Route121_Text_29FB8C: @ 829FB8C
	.string "Hein? Qu'est-ce qui s'est passé?$"

Route121_Text_29FBA8: @ 829FBA8
	.string "Je devrais peut-être les entraîner un\n"
	.string "peu plus avant de les inscrire à\l"
	.string "un CONCOURS…$"

Route123_Text_29FBEB: @ 829FBEB
	.string "Tu veux connaître ta force?\n"
	.string "Je vais te faire passer le test!$"

Route123_Text_29FC23: @ 829FC23
	.string "Tu as réussi haut la main!$"

Route123_Text_29FC42: @ 829FC42
	.string "Pour l'emporter même sur moi…\n"
	.string "Il faut que ta force soit grandiose!$"

Route123_Text_29FC6F: @ 829FC6F
	.string "Tu sembles avoir une belle collection\n"
	.string "de BADGES D'ARENES.\p"
	.string "Laisse-moi voir si tu es réellement\n"
	.string "digne de tous ces BADGES.$"

Route123_Text_29FCD6: @ 829FCD6
	.string "Bon, très bien, tu en es digne!$"

Route123_Text_29FCF4: @ 829FCF4
	.string "Tu as prouvé la véritable valeur\n"
	.string "de tes BADGES dans ce combat!$"

Route123_Text_29FD1D: @ 829FD1D
	.string "On dit que les bons moments sont\n"
	.string "riches en agréables parfums.$"

Route123_Text_29FD53: @ 829FD53
	.string "Oh…\n"
	.string "Je sens l'âpre odeur de la souffrance…$"

Route123_Text_29FD7B: @ 829FD7B
	.string "Le jardin du MAITRE DES BAIES dégage\n"
	.string "de multiples parfums édifiants.$"

Route123_Text_29FDBA: @ 829FDBA
	.string "Etre médium est une question de\n"
	.string "volonté.\p"
	.string "Je me suis promis de ne jamais perdre.\n"
	.string "C'est ce qui fait ma force!$"

Route123_Text_29FE1E: @ 829FE1E
	.string "Je suis triste…$"

Route123_Text_29FE2A: @ 829FE2A
	.string "Etre médium requiert de la volonté.\n"
	.string "Je ne pensais pas perdre contre toi…$"

Route123_Text_29FE70: @ 829FE70
	.string "Je vois… Je vois…\n"
	.string "Je vois que nous allons nous battre\l"
	.string "de nouveau!\p"
	.string "Mais je ne peux pas voir si je vaincrai…\n"
	.string "Montre-moi ton POKéNAV.$"

Route123_Text_29FED4: @ 829FED4
	.string "Je me suis convaincu que je n'allais\n"
	.string "plus perdre. Ça me donne de la force!$"

Route123_Text_29FF1B: @ 829FF1B
	.string "Je suis triste…$"

Route123_Text_29FF27: @ 829FF27
	.string "Je devrais m'entraîner au MONT MEMORIA.\n"
	.string "Sinon, je ne vais jamais te battre…$"

Route123_Text_29FF61: @ 829FF61
	.string "Ne te réjouis pas trop si tes POKéMON\n"
	.string "développent des pouvoirs psychiques.\p"
	.string "Il faut que tu les perfectionnes si tu\n"
	.string "veux vraiment pouvoir t'en servir.$"

Route123_Text_29FFD8: @ 829FFD8
	.string "Ecrasée!$"

Route123_Text_29FFE5: @ 829FFE5
	.string "On a tous des pouvoirs psychiques.\n"
	.string "On a juste oublié comment les utiliser.$"

Route123_Text_2A0027: @ 82A0027
	.string "J'aimerais te rencontrer de nouveau.\n"
	.string "Tu es d'accord?$"

Route123_Text_2A005E: @ 82A005E
	.string "As-tu éveillé les pouvoirs psychiques\n"
	.string "qui sommeillent en toi?$"

Route123_Text_2A008D: @ 82A008D
	.string "Renversant!$"

Route123_Text_2A0099: @ 82A0099
	.string "Le pouvoir que tu as sur tes POKéMON…\n"
	.string "Ça pourrait être un pouvoir psychique…$"

Route123_Text_2A00D6: @ 82A00D6
	.string "MIU: Salut, DRESSEUR! J'espère que\n"
	.string "tes POKéMON ne pleurent pas quand\l"
	.string "ils perdent.$"

Route123_Text_2A0119: @ 82A0119
	.string "MIU: Ouin, on a perdu.$"

Route123_Text_2A012E: @ 82A012E
	.string "MIU: DRESSEUR, si tes POKéMON\n"
	.string "sont forts, c'est grâce à votre amitié.$"

Route123_Text_2A016D: @ 82A016D
	.string "MIU: C'est pas marrant de se\n"
	.string "battre si t'as pas deux POKéMON.$"

Route123_Text_2A01A7: @ 82A01A7
	.string "YUKI: OK! On va battre les POKéMON\n"
	.string "de ce DRESSEUR!$"

Route123_Text_2A01D8: @ 82A01D8
	.string "YUKI: Ouin, on a perdu.$"

Route123_Text_2A01EE: @ 82A01EE
	.string "YUKI: Pourquoi es-tu si robuste?\n"
	.string "On n'avait jamais perdu avant.$"

Route123_Text_2A0224: @ 82A0224
	.string "YUKI: C'est pas marrant de se\n"
	.string "battre si t'as pas deux POKéMON.$"

Route123_Text_2A025F: @ 82A025F
	.string "MONT MEMORIA…\n"
	.string "Ici reposent les âmes des POKéMON…\p"
	.string "Ton POKéMON veut-il se reposer?$"

Route123_Text_2A02A6: @ 82A02A6
	.string "Débordant de vitalité…$"

Route123_Text_2A02C1: @ 82A02C1
	.string "MONT MEMORIA…\n"
	.string "Ici reposent les âmes des POKéMON…\p"
	.string "Un pouvoir apaisant les esprits doit\n"
	.string "se dégager de cet endroit…$"

Route123_Text_2A0323: @ 82A0323
	.string "Je vais m'occuper de toi tout en\n"
	.string "jouant mon solo de guitare!$"

Route123_Text_2A035C: @ 82A035C
	.string "Hé, pas si vite!\n"
	.string "J'ai même pas fini l'intro!$"

Route123_Text_2A0389: @ 82A0389
	.string "T'as le rock dans la peau. J'aimerais\n"
	.string "écrire un morceau sur toi.$"

Route123_Text_2A03C1: @ 82A03C1
	.string "La prochaine fois, écoute au moins\n"
	.string "jusqu'au bout, OK?$"

Route123_Text_2A03FB: @ 82A03FB
	.string "Je sens que cette fois sera la bonne!\n"
	.string "Je vais gagner avant même la fin de\l"
	.string "ma chanson!$"

Route123_Text_2A045A: @ 82A045A
	.string "Attends un peu!\n"
	.string "Tu veux vraiment pas entendre\l"
	.string "le refrain?$"

Route123_Text_2A0487: @ 82A0487
	.string "Ma musique était censée te captiver\n"
	.string "au point de te faire perdre.$"

Route123_Text_2A04C0: @ 82A04C0
	.string "C'est mon formidable POKéMON INSECTE!\n"
	.string "C'est mon frangin qui me l'a donné!$"

Route123_Text_2A04FE: @ 82A04FE
	.string "Waah!\n"
	.string "Quelle méchanceté!$"

Route123_Text_2A0512: @ 82A0512
	.string "Ne dis pas à mon frère que j'ai perdu.\n"
	.string "Ce sera notre secret!$"

Route123_Text_2A054E: @ 82A054E
	.string "Ça me donnera confiance en moi de\n"
	.string "battre quelqu'un comme toi!$"

Route123_Text_2A0592: @ 82A0592
	.string "Où est passée ma confiance?$"

Route123_Text_2A05AC: @ 82A05AC
	.string "On dit qu'il ne faut pas juger les gens\n"
	.string "sur leur apparence.\p"
	.string "Mais la plupart du temps, ça marche!$"

Route123_Text_2A060A: @ 82A060A
	.string "Salut jeune DRESSEUR!\n"
	.string "T'as un peu de temps à perdre?$"

Route123_Text_2A0631: @ 82A0631
	.string "Un DRESSEUR plein de promesses!\n"
	.string "Voilà pour toi!$"

Route123_Text_2A0672: @ 82A0672
	.string "Comment? L'argent de la victoire ne\n"
	.string "te suffit pas?$"

Route123_Text_2A06AF: @ 82A06AF
	.string "Je dois t'avouer que les POKéMON OISEAU\n"
	.string "sont mon obsession!\p"
	.string "Les oiseaux sont vraiment cool!\n"
	.string "Ce sont simplement les meilleurs!$"

Route123_Text_2A0704: @ 82A0704
	.string "Même dans la défaite, les POKéMON\n"
	.string "OISEAU arrivent à rester cool!$"

Route123_Text_2A072B: @ 82A072B
	.string "Je collectionne les plumes que les\n"
	.string "POKéMON OISEAU perdent\l"
	.string "pendant leurs combats.\p"
	.string "J'ai l'intention d'en faire un chapeau\n"
	.string "une fois que j'en aurai suffisamment.$"

Route123_Text_2A079B: @ 82A079B
	.string "Quand il n'y a pas de DRESSEUR à\n"
	.string "affronter, je laisse mes POKéMON se\p"
	.string "battre entre eux et je profite du\n"
	.string "spectacle.$"

Route123_Text_2A07F0: @ 82A07F0
	.string "Plutôt pas mal tes POKéMON…$"

Route123_Text_2A080D: @ 82A080D
	.string "Héhé, je vais copier tes techniques de\n"
	.string "combat, je suis sûr que ça me rendra\l"
	.string "encore plus fort.$"

Route123_Text_2A0854: @ 82A0854
	.string "J'ai tendu un piège, et un DRESSEUR est\n"
	.string "tombé dedans!$"

Route123_Text_2A088A: @ 82A088A
	.string "Si je ne gagne pas, c'est tout de suite\n"
	.string "moins drôle de jouer au ninja!$"

Route123_Text_2A08CA: @ 82A08CA
	.string "La prochaine fois, je tendrai un piège\n"
	.string "à quelqu'un de moins fort!$"

Route123_Text_2A0902: @ 82A0902
	.string "Je viens d'acheter ce parasol.\n"
	.string "Avec ça, je suis deux fois plus belle!$"

Route123_Text_2A0943: @ 82A0943
	.string "Tu es au moins cinq fois plus\n"
	.string "redoutable que moi!$"

Route123_Text_2A096E: @ 82A096E
	.string "Bien utiliser les accessoires est\n"
	.string "le secret pour bien s'habiller!$"

Route124_Text_2A09B1: @ 82A09B1
	.string "Hé, tu ne retrouves pas ta route?\p"
	.string "Si tu réussis à battre mes POKéMON, je\n"
	.string "te servirai de guide.$"

Route124_Text_2A0A02: @ 82A0A02
	.string "Ce combat m'a fait perdre le nord!$"

Route124_Text_2A0A20: @ 82A0A20
	.string "De nombreuses personnes perdent\n"
	.string "leurs repères en mer.\p"
	.string "Si c'est ton cas, tu n'as qu'à te repérer\n"
	.string "sur la CARTE du POKéNAV.$"

Route124_Text_2A0A84: @ 82A0A84
	.string "Hum! Plutôt que de nager, tu avances\n"
	.string "sur le dos d'un POKéMON…\p"
	.string "Je t'envie!$"

Route124_Text_2A0ACC: @ 82A0ACC
	.string "Oh!\n"
	.string "Je ne peux pas…$"

Route124_Text_2A0AD9: @ 82A0AD9
	.string "Je suis en train d'attraper froid… Je\n"
	.string "suis resté trop longtemps dans l'eau…\p"
	.string "J'aimerais être sur un POKéMON aussi…$"

Route124_Text_2A0B37: @ 82A0B37
	.string "Si tu restes là à flotter en mer, les\n"
	.string "POKéMON vont venir jouer avec toi.$"

Route124_Text_2A0B7C: @ 82A0B7C
	.string "Oh, non!\n"
	.string "J'ai lancé le défi et j'ai perdu…$"

Route124_Text_2A0B9A: @ 82A0B9A
	.string "En mer, j'ai remarqué que des POKéMON\n"
	.string "attaquent et d'autres regardent.\p"
	.string "Je suppose que chaque POKéMON\n"
	.string "a sa propre personnalité.$"

Route124_Text_2A0C14: @ 82A0C14
	.string "C'est peut-être un caprice, mais\n"
	.string "j'aimerais beaucoup que tu\l"
	.string "m'enregistres sur ton POKéNAV!$"

Route124_Text_2A0C60: @ 82A0C60
	.string "Si tu ne fais que flotter en mer, les\n"
	.string "DRESSEURS vont te défier!$"

Route124_Text_2A0CA0: @ 82A0CA0
	.string "C'est curieux…\n"
	.string "J'ai encore perdu…$"

Route124_Text_2A0CBE: @ 82A0CBE
	.string "Ça n'a rien à voir, mais je vais aller\n"
	.string "visiter la MAISON DES PIEGES.$"

Route124_Text_2A0D0A: @ 82A0D0A
	.string "Je commence à en avoir marre de nager…\n"
	.string "Qu'est-ce que tu dirais d'un combat?$"

Route124_Text_2A0D3D: @ 82A0D3D
	.string "Je ne t'imaginais pas aussi robuste!$"

Route124_Text_2A0D66: @ 82A0D66
	.string "Ce sont tous tes efforts qui ont\n"
	.string "dû te donner autant de force.$"

Route124_Text_2A0DA0: @ 82A0DA0
	.string "Pfffff… J'ai plongé dans les abîmes de\n"
	.string "la mer pour me mettre bien à l'abri.\p"
	.string "J'excelle dans le sondage des\n"
	.string "profondeurs!$"

Route124_Text_2A0DFF: @ 82A0DFF
	.string "Glou, glou, glou…\n"
	.string "Je coule…$"

Route124_Text_2A0E1E: @ 82A0E1E
	.string "Je tiens de source sûre qu'il y a par\n"
	.string "ici un endroit où l'on peut faire de la\l"
	.string "PLONGEE.\p"
	.string "Je ne résiste pas à l'envie de retourner\n"
	.string "dans les profondeurs…$"

Route124_Text_2A0E87: @ 82A0E87
	.string "RITA: Soupir…\p"
	.string "Me voilà en mer, mais avec qui je suis?\n"
	.string "Mon petit frère!\p"
	.string "Battons-nous, que je ne continue pas\n"
	.string "à m'appesantir là-dessus!$"

Route124_Text_2A0EFE: @ 82A0EFE
	.string "RITA: SAM! C'est de ta faute si on\n"
	.string "a perdu! Ça se paiera!$"

Route124_Text_2A0F3A: @ 82A0F3A
	.string "RITA: Soupir…\p"
	.string "Si seulement j'étais avec un charmant\n"
	.string "petit ami et pas avec mon petit frère…$"

Route124_Text_2A0F8C: @ 82A0F8C
	.string "RITA: Tu comptes nous affronter?\n"
	.string "Seulement si tu as deux POKéMON.$"

Route124_Text_2A0FD1: @ 82A0FD1
	.string "SAM: Ma sœur est forte aux POKéMON.\p"
	.string "Viens pas te plaindre si tu perds!$"

Route124_Text_2A1012: @ 82A1012
	.string "SAM: Ouin…\n"
	.string "Ma grande sœur va m'incendier…$"

Route124_Text_2A103E: @ 82A103E
	.string "SAM: Ma grande sœur est vraiment\n"
	.string "flippante quand elle s'énerve.\p"
	.string "C'est pour ça qu'elle n'a pas de petit\n"
	.string "ami.$"

Route124_Text_2A109F: @ 82A109F
	.string "SAM: Tu te battras encore avec nous?\n"
	.string "Mais vas-y mollo la prochaine fois, OK?$"

Route124_Text_2A10E5: @ 82A10E5
	.string "SAM: Tu veux nous affronter?\n"
	.string "Alors ramène d'autres POKéMON.$"

Route124_Text_2A111E: @ 82A111E
	.string "RITA: J'ai vraiment pas de chance…\p"
	.string "Me voilà en mer, mais avec qui je suis?\n"
	.string "Mon petit frère!\p"
	.string "Salut, ça faisait longtemps. Qu'on se\n"
	.string "batte! Ça me changera les idées!$"

Route124_Text_2A11B2: @ 82A11B2
	.string "RITA: SAM!\n"
	.string "C'est de ta faute si on a perdu!\p"
	.string "On va faire une séance d'entraînement!$"

Route124_Text_2A1203: @ 82A1203
	.string "RITA: J'ai vraiment pas de chance…\p"
	.string "Avec un petit ami, on battrait tout le\n"
	.string "monde avec nos tendres combinaisons…$"

Route124_Text_2A1255: @ 82A1255
	.string "RITA: Tu comptes nous affronter? \n"
	.string "Seulement si tu as deux POKéMON.$"

Route124_Text_2A129A: @ 82A129A
	.string "SAM: Il faut qu'on gagne!\n"
	.string "Je vais tout donner!$"

Route124_Text_2A12DD: @ 82A12DD
	.string "SAM: Ouin…\n"
	.string "Ma grande sœur va encore m'incendier.$"

Route124_Text_2A130F: @ 82A130F
	.string "SAM: Ma grande sœur est vraiment\n"
	.string "flippante quand elle s'énerve.\p"
	.string "Elle va me faire travailler très dur\n"
	.string "avec les POKéMON…$"

Route124_Text_2A1384: @ 82A1384
	.string "SAM: Tu veux nous affronter?\n"
	.string "Alors ramène d'autres POKéMON.$"

Route124_Text_2A13BD: @ 82A13BD
	.string "Je me demande bien ce que je suis\n"
	.string "venu faire ici.\p"
	.string "C'est pathétique, y'a pas d'autre mot.$"

Route124_Text_2A142C: @ 82A142C
	.string "Je me suis retrouvé noyé sous\n"
	.string "les coups.$"

Route124_Text_2A144F: @ 82A144F
	.string "Je devrais aller parler un peu avec les\n"
	.string "NAGEUSES du coin.$"

Route124_Text_2A148E: @ 82A148E
	.string "Je ne peux pas perdre contre un\n"
	.string "DRESSEUR qui utilise SURF pour\l"
	.string "se déplacer!$"

Route124_Text_2A14BC: @ 82A14BC
	.string "C'est de la sueur que j'ai dans les\n"
	.string "yeux, pas des larmes, je t'assure!$"

Route124_Text_2A14ED: @ 82A14ED
	.string "On trouve de très jolies choses au\n"
	.string "fond de l'eau par ici!$"

Route125_Text_2A1527: @ 82A1527
	.string "Je savais que tu arrivais, alors je me\n"
	.string "suis attardé pour te rencontrer!$"

Route125_Text_2A155A: @ 82A155A
	.string "Je me rends!$"

Route125_Text_2A1567: @ 82A1567
	.string "Le son se propage plus vite dans l'eau\n"
	.string "que dans l'air.$"

Route125_Text_2A159F: @ 82A159F
	.string "Hé, toi là-bas!\n"
	.string "Viens voir mon adorable POKéMON!$"

Route125_Text_2A15C7: @ 82A15C7
	.string "J'ai carrément pataugé…$"

Route125_Text_2A15D5: @ 82A15D5
	.string "Le charme d'HYPOTREMPE m'a attiré\n"
	.string "et j'ai commencé à nager aussi.$"

Route125_Text_2A1615: @ 82A1615
	.string "J'en ai marre de nager.\n"
	.string "Ça te dirait un combat contre moi?$"

Route125_Text_2A164D: @ 82A164D
	.string "T'es vraiment trop!$"

Route125_Text_2A165E: @ 82A165E
	.string "Fffou…\n"
	.string "C'est par où ALGATIA?$"

Route125_Text_2A1686: @ 82A1686
	.string "Comment! Tu voudrais te battre contre\n"
	.string "le POKéMON EAU que j'ai élevé?$"

Route125_Text_2A16C5: @ 82A16C5
	.string "Que…$"

Route125_Text_2A16CE: @ 82A16CE
	.string "Cette force… Tu ne me déçois pas!\n"
	.string "Au contraire, j'en ai le souffle coupé!$"

Route125_Text_2A16FC: @ 82A16FC
	.string "Je suis un MARIN robuste et passionné.\n"
	.string "J'ai bravé les mers du monde entier!$"

Route125_Text_2A173A: @ 82A173A
	.string "Arrrrg!\n"
	.string "Je n'ai pas réussi à gagner!$"

Route125_Text_2A1755: @ 82A1755
	.string "Dans la GROTTE TREFONDS, la mer\n"
	.string "monte et descend.\p"
	.string "Il y a environ six heures entre la marée\n"
	.string "haute et la marée basse. Tu l'savais?$"

Route125_Text_2A17CF: @ 82A17CF
	.string "Enregistre-moi dans ton POKéNAV\n"
	.string "et je te dirai un truc dingue!$"

Route125_Text_2A180E: @ 82A180E
	.string "Il est grand temps que je prenne ma\n"
	.string "revanche sur toi! Place au combat!$"

Route125_Text_2A1851: @ 82A1851
	.string "Je n'ai pas réussi à gagner!\n"
	.string "Absolument pas!$"

Route125_Text_2A187A: @ 82A187A
	.string "La GROTTE TREFONDS…\p"
	.string "Il existe des endroits accessibles\n"
	.string "ou non en fonction de la marée.\l"
	.string "Tout dépend si elle est haute ou basse.\p"
	.string "N'oublie pas qu'il y a environ six heures\n"
	.string "entre la marée haute et la marée basse!$"

Route125_Text_2A192B: @ 82A192B
	.string "KIM: Un drôle de vieux monsieur vit dans\n"
	.string "la GROTTE TREFONDS. On me l'a dit.\p"
	.string "Toi aussi tu veux aller le voir?$"

Route125_Text_2A1989: @ 82A1989
	.string "KIM: Je croyais qu'on allait gagner.$"

Route125_Text_2A19A6: @ 82A19A6
	.string "KIM: Un drôle de vieux monsieur vit dans\n"
	.string "la GROTTE TREFONDS, n'est-ce pas?\p"
	.string "Allons le voir, IRIS!$"

Route125_Text_2A19F8: @ 82A19F8
	.string "KIM: Non, non et non! Il te faut\n"
	.string "deux POKéMON sinon, c'est pas la peine!$"

Route125_Text_2A1A35: @ 82A1A35
	.string "IRIS: KIM, tu peux me dire ce\n"
	.string "qu'on cherche là?$"

Route125_Text_2A1A71: @ 82A1A71
	.string "IRIS: Oh, on ne peut plus trop avancer.$"

Route125_Text_2A1A92: @ 82A1A92
	.string "IRIS: KIM, on va vraiment aller dans\n"
	.string "la GROTTE TREFONDS?\p"
	.string "On va être toutes mouillées.$"

Route125_Text_2A1AD9: @ 82A1AD9
	.string "IRIS: Oh, on ne pourrait jamais\n"
	.string "combattre à 2 contre 1.$"

Route125_Text_2A1B1A: @ 82A1B1A
	.string "Tu te demandes ce qu'un ORNITHOLOGUE\n"
	.string "comme moi fait au milieu de l'océan?$"

Route125_Text_2A1B4E: @ 82A1B4E
	.string "OK, je vais te dire ce que je fais ici.$"

Route125_Text_2A1B70: @ 82A1B70
	.string "J'ai mis un message dans une bouteille\n"
	.string "et je suis venu le déposer.\p"
	.string "J'espère qu'une jolie NAGEUSE\n"
	.string "tombera dessus.$"

Route125_Text_2A1BCE: @ 82A1BCE
	.string "Hé! C'est toi qui jettes des ordures\n"
	.string "à la mer?$"

Route125_Text_2A1BFD: @ 82A1BFD
	.string "Oh, apparemment ça n'était pas toi?$"

Route125_Text_2A1C2A: @ 82A1C2A
	.string "J'ai trouvé une affreuse bouteille en\n"
	.string "train de flotter dans l'eau.\p"
	.string "Ça me met hors de moi de voir\n"
	.string "les gens polluer la mer.$"

Route126_Text_2A1C95: @ 82A1C95
	.string "La natation fait travailler tout le\n"
	.string "corps. Ça va te donner la pêche!$"

Route126_Text_2A1CC8: @ 82A1CC8
	.string "Je l'admets! Tu as gagné!$"

Route126_Text_2A1CDD: @ 82A1CDD
	.string "Mate un peu ce physique! C'est grâce\n"
	.string "à la natation que je fais chaque jour.$"

Route126_Text_2A1D2A: @ 82A1D2A
	.string "Cette très haute montagne de roche\n"
	.string "blanche, c'est ATALANOPOLIS.$"

Route126_Text_2A1D63: @ 82A1D63
	.string "Tu m'as réglé mon compte?$"

Route126_Text_2A1D72: @ 82A1D72
	.string "Je n'arrive pas à trouver l'entrée\n"
	.string "d'ATALANOPOLIS. Où peut-elle être?$"

Route126_Text_2A1DAE: @ 82A1DAE
	.string "Lalalalalala!\n"
	.string "Je suis une sirène!$"

Route126_Text_2A1DC8: @ 82A1DC8
	.string "Je m'efface devant toi, comme une bulle\n"
	.string "qui éclate! Bul, bul, bul…$"

Route126_Text_2A1E03: @ 82A1E03
	.string "Tu m'as battue… Je veux disparaître\n"
	.string "dans une vague de désespoir…$"

Route126_Text_2A1E3E: @ 82A1E3E
	.string "Salut, p'tit môme!\n"
	.string "Tu te bats contre moi?$"

Route126_Text_2A1E63: @ 82A1E63
	.string "Oh, noooon!$"

Route126_Text_2A1E70: @ 82A1E70
	.string "J'adore m'ébattre comme ça dans la mer\n"
	.string "avec les POKéMON!$"

Route126_Text_2A1EA5: @ 82A1EA5
	.string "Admire un peu ce corps d'athlète!\n"
	.string "Je suis encore plus costaud qu'un\l"
	.string "KARATEKA!$"

Route126_Text_2A1EE3: @ 82A1EE3
	.string "Oups!\n"
	.string "Pas mal, pas mal du tout!$"

Route126_Text_2A1F10: @ 82A1F10
	.string "Perdre contre toi ne fait que me\n"
	.string "motiver davantage.\p"
	.string "Je vais m'entraîner avec mes POKéMON\n"
	.string "encore plus durement!$"

Route126_Text_2A1F5A: @ 82A1F5A
	.string "Ouaip, vraiment pas mal!\n"
	.string "J'aimerais vraiment te connaître un\l"
	.string "peu mieux!$"

Route126_Text_2A1F98: @ 82A1F98
	.string "Mate un peu ce physique! Je suis\n"
	.string "encore plus musclé qu'un NAGEUR!$"

Route126_Text_2A1FD8: @ 82A1FD8
	.string "Oups! Vraiment trop fort!$"

Route126_Text_2A200C: @ 82A200C
	.string "Tu arrives vraiment à me motiver.\n"
	.string "Je vais m'entraîner encore plus!\p"
	.string "Reviens me voir dès que possible!$"

Route126_Text_2A2063: @ 82A2063
	.string "L'année dernière, je n'étais même pas\n"
	.string "capable de nager la brasse.\p"
	.string "Mais maintenant je suis un bon NAGEUR,\n"
	.string "je vais te montrer!$"

Route126_Text_2A20C6: @ 82A20C6
	.string "Je ferais mieux d'apprendre le crawl.$"

Route126_Text_2A20F7: @ 82A20F7
	.string "Rien de mieux que l'entraînement pour\n"
	.string "se perfectionner.\p"
	.string "Tu es jeune, n'hésite pas à essayer\n"
	.string "plein de choses!$"

Route126_Text_2A216A: @ 82A216A
	.string "Tu ne trouves pas ça affreux d'avaler\n"
	.string "de l'eau salée par le nez?$"

Route126_Text_2A21A3: @ 82A21A3
	.string "Gloub gloub.\n"
	.string "J'ai bu la tasse!$"

Route126_Text_2A21B8: @ 82A21B8
	.string "J'ai avalé de l'eau!\n"
	.string "C'est salé et amer!$"

Route126_Text_2A21EF: @ 82A21EF
	.string "Je vais y mettre tout mon cœur!$"

Route126_Text_2A2216: @ 82A2216
	.string "Tu as montré plus de volonté.$"

Route126_Text_2A222A: @ 82A222A
	.string "Je suis épuisée…\n"
	.string "Je vais faire la planche pour changer.$"

Route127_Text_2A225F: @ 82A225F
	.string "Je le lis sur ton visage. Tu veux\n"
	.string "me défier.$"

Route127_Text_2A2294: @ 82A2294
	.string "Ooooooooooooh…$"

Route127_Text_2A22A1: @ 82A22A1
	.string "Un combat bien disputé me ravigote\n"
	.string "et m'apaise.$"

Route127_Text_2A22DD: @ 82A22DD
	.string "As-tu un rival contre qui tu détestes\n"
	.string "perdre?$"

Route127_Text_2A2315: @ 82A2315
	.string "Arrrrg!\n"
	.string "J'ai horreur de perdre!$"

Route127_Text_2A232C: @ 82A232C
	.string "Si tu as un rival, ne ressens-tu pas le\n"
	.string "devoir de toujours faire mieux?$"

Route127_Text_2A2381: @ 82A2381
	.string "Grâce à la pêche, j'ai atteint un état de\n"
	.string "complète sérénité…\p"
	.string "Permets-moi de t'en donner la preuve…$"

Route127_Text_2A23E1: @ 82A23E1
	.string "Même si j'ai perdu, je reste serein…$"

Route127_Text_2A240C: @ 82A240C
	.string "Ce n'est pas grave si je n'attrape rien.\n"
	.string "La ligne reste dans l'eau…$"

Route127_Text_2A2450: @ 82A2450
	.string "Ne me dis pas qu'un POKéMON en train\n"
	.string "de SURFER s'est accroché à ma ligne!$"

Route127_Text_2A2483: @ 82A2483
	.string "Je n'arrive pas à tenir le rythme!$"

Route127_Text_2A2494: @ 82A2494
	.string "Tes POKéMON ont l'air plutôt forts.\n"
	.string "Si je voulais les attraper, j'aurais\l"
	.string "du fil à retordre!$"

Route127_Text_2A24C6: @ 82A24C6
	.string "Hé! C'est parti pour un match entre toi,\n"
	.string "fan de POKéMON et moi, mordu de pêche!$"

Route127_Text_2A250B: @ 82A250B
	.string "Non! Ma ligne est emmêlée!\n"
	.string "La partie est terminée!$"

Route127_Text_2A2538: @ 82A2538
	.string "Ma ligne exécute une danse!\n"
	.string "Le méli-mélo! Hahaha, elle est emmêlée…$"

Route127_Text_2A257A: @ 82A257A
	.string "Les POKéMON OISEAU ont une bonne\n"
	.string "vue. Ils repèrent leurs proies de haut.$"

Route127_Text_2A25C1: @ 82A25C1
	.string "Pfooou… J'abandonne!$"

Route127_Text_2A25D2: @ 82A25D2
	.string "Par ici, il y a beaucoup d'endroits où\n"
	.string "tu peux plonger.\p"
	.string "Ils sont facilement repérables du ciel\n"
	.string "en raison de leur couleur plus foncée.$"

Route127_Text_2A264D: @ 82A264D
	.string "Marcher pieds nus, c'est ce que je\n"
	.string "conseille pour s'endurcir l'esprit!$"

Route127_Text_2A2685: @ 82A2685
	.string "Woutch! Je me suis pris une\n"
	.string "écharde dans le pied!$"

Route127_Text_2A26AC: @ 82A26AC
	.string "C'est sympa de marcher pieds nus.\n"
	.string "Mais tes CHAUSSURES ont l'air\l"
	.string "vraiment pas mal!$"

Route127_Text_2A26EE: @ 82A26EE
	.string "Voilà ce que je fais à ceux qui me\n"
	.string "battent! J'espère qu'on se reverra!$"

Route127_Text_2A2734: @ 82A2734
	.string "Je marche pieds nus tous les jours.\n"
	.string "Mes pieds sont durs comme la pierre!$"

Route127_Text_2A276B: @ 82A276B
	.string "Ouch! Encore une écharde!$"

Route127_Text_2A278E: @ 82A278E
	.string "Tu n'veux pas essayer de marcher\n"
	.string "pieds nus?\p"
	.string "Comme ça je pourrai t'emprunter tes\n"
	.string "CHAUSSURES…$"

Route127_Text_2A27D0: @ 82A27D0
	.string "Affrontons-nous dans un combat\n"
	.string "calme et méthodique.$"

Route127_Text_2A27FC: @ 82A27FC
	.string "Tu ne m'as pas donné le temps de me\n"
	.string "battre stratégiquement.$"

Route127_Text_2A2832: @ 82A2832
	.string "Quand je suis entourée par le ciel et\n"
	.string "la mer, c'est comme si le temps\l"
	.string "s'arrêtait.$"

Route128_Text_2A287F: @ 82A287F
	.string "Il y a encore un bon bout de chemin\n"
	.string "avant ETERNARA…$"

Route128_Text_2A28AB: @ 82A28AB
	.string "J'ai aussi du chemin à parcourir\n"
	.string "avant ma première victoire…$"

Route128_Text_2A28D7: @ 82A28D7
	.string "Toute ma vie j'ai connu la défaite,\n"
	.string "mais je n'abandonnerai jamais!$"

Route128_Text_2A2916: @ 82A2916
	.string "Je sais que je n'ai pas le niveau pour\n"
	.string "l'instant. Mais ça changera.\p"
	.string "Enregistre-moi dans ton POKéNAV.$"

Route128_Text_2A2975: @ 82A2975
	.string "Je ne suis pas trop fatigué. Je vais\n"
	.string "continuer à nager jusqu'à ETERNARA.$"

Route128_Text_2A29B8: @ 82A29B8
	.string "Je n'ai pas encore goûté à la victoire…$"

Route128_Text_2A29DC: @ 82A29DC
	.string "Je vais arriver à ETERNARA,\n"
	.string "où je vais finalement gagner…$"

Route128_Text_2A2A1F: @ 82A2A1F
	.string "Un triathlon est une course épuisante\n"
	.string "composée de trois épreuves.\p"
	.string "Il faut nager, faire du vélo et puis\n"
	.string "courir un semi-marathon.$"

Route128_Text_2A2A94: @ 82A2A94
	.string "Un combat de POKéMON, c'est épuisant\n"
	.string "aussi…$"

Route128_Text_2A2AB7: @ 82A2AB7
	.string "Après, je dois rouler en VELO, mais…\n"
	.string "Je suis sur le point de jeter l'éponge…$"

Route128_Text_2A2AF9: @ 82A2AF9
	.string "Je suis sûre que je pourrais mieux\n"
	.string "faire. On se fait une revanche un de\l"
	.string "ces jours?$"

Route128_Text_2A2B41: @ 82A2B41
	.string "C'est long un triathlon. Mais je suppose\n"
	.string "que devenir le MAITRE POKéMON\l"
	.string "est également long et épuisant.$"

Route128_Text_2A2BAB: @ 82A2BAB
	.string "Un combat de POKéMON, c'est vraiment\n"
	.string "dur et ça ne pardonne pas…$"

Route128_Text_2A2BDD: @ 82A2BDD
	.string "Tu devrais bien réfléchir aux défis qui\n"
	.string "t'attendent sur la ROUTE VICTOIRE.$"

Route128_Text_2A2C1C: @ 82A2C1C
	.string "Nous avons travaillé si dur pour relever\n"
	.string "le défi de la LIGUE POKéMON…\p"
	.string "Nous ne pouvons pas perdre maintenant!$"

Route128_Text_2A2C79: @ 82A2C79
	.string "Oh!\n"
	.string "Comment cela a-t-il pu se produire?!$"

Route128_Text_2A2C95: @ 82A2C95
	.string "Après ce que j'ai fait pour en arriver là,\n"
	.string "je n'vais pas m'arrêter sur une défaite.$"

Route128_Text_2A2CD9: @ 82A2CD9
	.string "Il n'y a pas plus fort DRESSEUR que moi!$"

Route128_Text_2A2CFE: @ 82A2CFE
	.string "C'est impossible!$"

Route128_Text_2A2D0D: @ 82A2D0D
	.string "Il n'y a probablement pas plus fort\n"
	.string "DRESSEUR que toi!$"

Route128_Text_2A2D3D: @ 82A2D3D
	.string "Je veux aller à ETERNARA, alors j'ai\n"
	.string "attrapé un POKéMON connaissant\l"
	.string "CASCADE pour monter les chutes d'eau.$"

Route128_Text_2A2DA9: @ 82A2DA9
	.string "J'ai chuté!$"

Route128_Text_2A2DBA: @ 82A2DBA
	.string "Ah, ah, très drôle!\p"
	.string "Mon POKéMON connaît CASCADE, mais je\n"
	.string "n'ai pas le BADGE d'ATALANOPOLIS!$"

Route128_Text_2A2E0F: @ 82A2E0F
	.string "Tu as l'air plutôt coriace. Je me\n"
	.string "demande si je peux gagner…$"

Route128_Text_2A2E44: @ 82A2E44
	.string "Ouch!\n"
	.string "Ça ne devait pas être possible.$"

Route128_Text_2A2E6C: @ 82A2E6C
	.string "De nombreux DRESSEURS plutôt doués\n"
	.string "se réunissent souvent près d'ETERNARA.\p"
	.string "Tu crois que je suis assez fort\n"
	.string "pour eux?$"

Route128_Text_2A2EC8: @ 82A2EC8
	.string "Le soleil semble briller plus fort par\n"
	.string "là-bas.$"

Route128_Text_2A2EFA: @ 82A2EFA
	.string "J'ai perdu parce que j'avais le soleil\n"
	.string "dans les yeux.$"

Route128_Text_2A2F2F: @ 82A2F2F
	.string "Il va falloir que je rentre. Je dois me\n"
	.string "remettre de la protection solaire.$"

Route129_Text_2A2F66: @ 82A2F66
	.string "C'est mon premier triathlon.\n"
	.string "Je suis tout tendu et nerveux!$"

Route129_Text_2A2F9D: @ 82A2F9D
	.string "Arrrrg!\n"
	.string "J'ai raté la victoire!$"

Route129_Text_2A2FB9: @ 82A2FB9
	.string "Si je suis tendu, je ne vais pas pouvoir\n"
	.string "donner le maximum.$"

Route129_Text_2A2FF2: @ 82A2FF2
	.string "Je suis en plein milieu d'un triathlon,\n"
	.string "mais oui, battons-nous!$"

Route129_Text_2A3034: @ 82A3034
	.string "J'étais pourtant sûre de gagner!$"

Route129_Text_2A3048: @ 82A3048
	.string "Tu sais ce qu'il y a de plus formidable\n"
	.string "dans le triathlon?\p"
	.string "C'est de pouvoir tester les limites de\n"
	.string "ta propre force et de ton endurance\l"
	.string "face à Mère Nature!$"

Route129_Text_2A30CD: @ 82A30CD
	.string "Hé!\n"
	.string "Qu'on s'y mette!$"

Route129_Text_2A30F1: @ 82A30F1
	.string "Battu… On m'a battu!\n"
	.string "Ça y est, c'est fait!$"

Route129_Text_2A3114: @ 82A3114
	.string "Un perdant n'a rien à attendre. Il est\n"
	.string "temps pour moi de battre en retraite.$"

Route129_Text_2A314E: @ 82A314E
	.string "Y a pas urgence?\n"
	.string "On n'a qu'à s'y mettre tranquillement.$"

Route129_Text_2A317D: @ 82A317D
	.string "Oh, ça alors!\n"
	.string "Je voulais me détendre un peu plus…$"

Route129_Text_2A31A6: @ 82A31A6
	.string "N'as-tu pas horreur de faire des\n"
	.string "erreurs quand tu te dépêches?\p"
	.string "C'est pour cela que j'essaie de prendre\n"
	.string "les choses calmement.$"

Route129_Text_2A3204: @ 82A3204
	.string "Surfer n'est pas aussi facile qu'on\n"
	.string "pourrait le penser, n'est-ce pas?$"

Route129_Text_2A3239: @ 82A3239
	.string "Gagner, c'est pas facile non plus!$"

Route129_Text_2A3252: @ 82A3252
	.string "Tu dois sûrement t'intéresser à\n"
	.string "la LIGUE POKéMON!\l"
	.string "Continue comme ça!$"

Route130_Text_2A328A: @ 82A328A
	.string "Quelle surprise! Je ne pensais pas\n"
	.string "tomber sur un DRESSEUR en mer.\p"
	.string "Je crois qu'on devrait s'affronter!$"

Route130_Text_2A32E6: @ 82A32E6
	.string "Quelle force pour un si jeune âge…$"

Route130_Text_2A3300: @ 82A3300
	.string "Tu as le regard de quelqu'un qui a connu\n"
	.string "de rudes épreuves et qui a su relever\l"
	.string "les défis. Ça te correspond bien!$"

Route130_Text_2A3363: @ 82A3363
	.string "Dans les eaux bleues et profondes de\n"
	.string "la mer, mon cœur désemparé trouve\l"
	.string "réconfort auprès des vagues.$"

Route130_Text_2A33AC: @ 82A33AC
	.string "Comme la mer, vaste et bleue, le\n"
	.string "monde des POKéMON couvre des\l"
	.string "profondeurs incroyables.$"

Route130_Text_2A33F5: @ 82A33F5
	.string "Le rêve de tous les enfants du\n"
	.string "monde, c'est de devenir un jour\l"
	.string "MAITRE POKéMON.$"

Route130_Text_2A343A: @ 82A343A
	.string "Flotter au milieu de l'eau comme ça…\n"
	.string "Ça détend vraiment…$"

Route130_Text_2A346D: @ 82A346D
	.string "Je devais être un peu trop détendu!$"

Route130_Text_2A3494: @ 82A3494
	.string "Se battre et nager comme ça…\n"
	.string "Je suis vraiment un homme heureux…$"

Route131_Text_2A34C8: @ 82A34C8
	.string "La mer regorge de POKéMON.\n"
	.string "Tu sais, c'est pas facile de nager.$"

Route131_Text_2A350D: @ 82A350D
	.string "Les POKéMON élevés par des DRESSEURS\n"
	.string "sont sacrément forts…$"

Route131_Text_2A353D: @ 82A353D
	.string "Pfou… Pfou… Je suis lessivé…\p"
	.string "L'aller est facile. C'est le retour qui\n"
	.string "est plus difficile.\p"
	.string "Va-t-il me rester assez d'énergie pour\n"
	.string "faire le trajet retour?$"

Route131_Text_2A35C6: @ 82A35C6
	.string "La mer… La mer… La mer…\n"
	.string "La mer à perte de vue!\p"
	.string "Ça me rend dingue!$"

Route131_Text_2A3626: @ 82A3626
	.string "Booouh!$"

Route131_Text_2A362D: @ 82A362D
	.string "Je suis las de la mer et pourtant,\n"
	.string "je ne peux m'empêcher de nager.\p"
	.string "Je suis un nageur-né!\n"
	.string "Voilà ce que je suis.$"

Route131_Text_2A367B: @ 82A367B
	.string "Salut, mon chou. Attends!\n"
	.string "On devrait s'affronter, toi et moi!$"

Route131_Text_2A36AB: @ 82A36AB
	.string "Même si tu n'en as pas l'air, tu as\n"
	.string "une grande force!$"

Route131_Text_2A36D6: @ 82A36D6
	.string "As-tu vu un type par ici qui se\n"
	.string "plaignait d'être lassé de la mer?\p"
	.string "Tu parles!\n"
	.string "Il est éperdument amoureux de la mer!$"

Route131_Text_2A3751: @ 82A3751
	.string "Pourquoi les hommes aiment-ils\n"
	.string "tant les maillots de bain?\p"
	.string "Ils me matent tous!$"

Route131_Text_2A378A: @ 82A378A
	.string "J'ai perdu pied!$"

Route131_Text_2A379F: @ 82A379F
	.string "C'est peut-être pas mon maillot de bain\n"
	.string "que matent les hommes, mais ma beauté!$"

Route131_Text_2A37E9: @ 82A37E9
	.string "LANA: Avec mon frère, on va faire équipe\n"
	.string "pour t'avoir!$"

Route131_Text_2A381F: @ 82A381F
	.string "LANA: On n'a pas réussi à gagner,\n"
	.string "même en faisant équipe…$"

Route131_Text_2A3855: @ 82A3855
	.string "LANA: A PACIFIVILLE, les habitants\n"
	.string "sont liés à la mer et aux POKéMON comme\l"
	.string "au premier jour.$"

Route131_Text_2A38B7: @ 82A38B7
	.string "LANA: Si tu n'as pas deux POKéMON,\n"
	.string "on n'aura pas le plaisir de s'affronter.$"

Route131_Text_2A38F8: @ 82A38F8
	.string "IAN: Avec ma sœurette, on fait de\n"
	.string "notre mieux!$"

Route131_Text_2A3925: @ 82A3925
	.string "IAN: Avec ma sœurette, on a fait\n"
	.string "tout ce qu'on pouvait, mais on a perdu…$"

Route131_Text_2A3960: @ 82A3960
	.string "IAN: Tu sais que PACIFIVILLE\n"
	.string "est une ville flottante?\p"
	.string "Alors là où il y a la mer, se trouve une\n"
	.string "partie de PACIFIVILLE!$"

Route131_Text_2A39CD: @ 82A39CD
	.string "IAN: Si tu as deux POKéMON, on\n"
	.string "te prend à 2 contre 2!$"

Route131_Text_2A39FE: @ 82A39FE
	.string "Si tu arrives à me battre, je te donnerai\n"
	.string "des infos intéressantes!$"

Route131_Text_2A3A38: @ 82A3A38
	.string "Oh?\n"
	.string "J'ai vraiment perdu?$"

Route131_Text_2A3A48: @ 82A3A48
	.string "Il y a un endroit étrange pas très loin\n"
	.string "d'ici. On peut y voir une tour immense.\p"
	.string "Mais pourquoi n'irais-tu pas y jeter\n"
	.string "un coup d'œil?$"

Route131_Text_2A3AA0: @ 82A3AA0
	.string "Il n'y a pas plus calme que les gens\n"
	.string "de PACIFIVILLE.\p"
	.string "Ils ne se mettent jamais en colère, un\n"
	.string "peu comme moi, quoi!$"

Route131_Text_2A3AFC: @ 82A3AFC
	.string "Oups!$"

Route131_Text_2A3B02: @ 82A3B02
	.string "Gr… Eh, non!\n"
	.string "Je ne suis pas en colère, je t'assure!$"

Route132_Text_2A3B4C: @ 82A3B4C
	.string "Quand j'étais petit, je prenais toujours\n"
	.string "froid mais depuis que je nage, je suis\l"
	.string "en bonne santé.$"

Route132_Text_2A3BAC: @ 82A3BAC
	.string "J'aimerais tant être plus puissant…$"

Route132_Text_2A3BC0: @ 82A3BC0
	.string "Les DRESSEURS arpentent champs et\n"
	.string "montagnes. Ça les garde en forme aussi.$"

Route132_Text_2A3C04: @ 82A3C04
	.string "Je ne nage pas là où le courant est\n"
	.string "trop fort.$"

Route132_Text_2A3C39: @ 82A3C39
	.string "Oh, non, je t'en supplie!$"

Route132_Text_2A3C49: @ 82A3C49
	.string "Si je me fais balayer, je vais perdre\n"
	.string "tout repère…$"

Route132_Text_2A3C7F: @ 82A3C7F
	.string "Défaite, victoire… Si tu n'essaies pas,\n"
	.string "tu ne sauras jamais…$"

Route132_Text_2A3CAD: @ 82A3CAD
	.string "Waah!\n"
	.string "Je sombre dans la défaite!$"

Route132_Text_2A3CC5: @ 82A3CC5
	.string "Je ne me bats jamais si je sais que c'est\n"
	.string "gagné d'avance. J'aime me battre en\l"
	.string "prenant le risque de perdre!$"

Route132_Text_2A3D26: @ 82A3D26
	.string "Je médite sur les POKéMON 24 heures\n"
	.string "sur 24. Comment pourrais-tu me battre?$"

Route132_Text_2A3D6C: @ 82A3D6C
	.string "J'ai perdu.\n"
	.string "J'admets la défaite.$"

Route132_Text_2A3D8B: @ 82A3D8B
	.string "Arrrg…\n"
	.string "Tu es fana de POKéMON, n'est-ce pas?\p"
	.string "Tu dois observer les POKéMON 24 heures\n"
	.string "sur 24, pas vrai?$"

Route132_Text_2A3DF0: @ 82A3DF0
	.string "Je suis toujours avec mon mari, mais\n"
	.string "je peux gagner même sans lui!$"

Route132_Text_2A3E2C: @ 82A3E2C
	.string "Oh, je ne devais pas être assez forte!$"

Route132_Text_2A3E4E: @ 82A3E4E
	.string "Le jeune homme plus loin est le portrait\n"
	.string "craché de mon mari quand il était\l"
	.string "plus jeune.\p"
	.string "Il me fait rougir!$"

Route132_Text_2A3EAC: @ 82A3EAC
	.string "Quelqu'un n'arrête pas de me regarder!\n"
	.string "Ce ne serait pas toi par hasard?$"

Route132_Text_2A3EDD: @ 82A3EDD
	.string "Wow!\n"
	.string "OK, j'ai compris!$"

Route132_Text_2A3F03: @ 82A3F03
	.string "J'ai la désagréable impression que\n"
	.string "quelqu'un n'arrête pas de me regarder!\p"
	.string "Je n'arrive pas à me concentrer!$"

Route132_Text_2A3F4F: @ 82A3F4F
	.string "Où est-ce que ma femme est encore\n"
	.string "passée?\p"
	.string "Je passe mon temps à la chercher\n"
	.string "partout!$"

Route132_Text_2A3FA8: @ 82A3FA8
	.string "Ah, j'aurais dû attendre l'aide de ma\n"
	.string "femme pour t'affronter.$"

Route132_Text_2A3FE5: @ 82A3FE5
	.string "Ma femme doit être en train de me\n"
	.string "chercher. Je vais aller à sa rencontre.$"

Route132_Text_2A4026: @ 82A4026
	.string "J'adore m'entraîner toute seule ici.\n"
	.string "Je ne supporte pas que tous ces gens\l"
	.string "soient là!$"

Route132_Text_2A406E: @ 82A406E
	.string "OK, j'arrête de me plaindre de voir trop\n"
	.string "de monde ici!$"

Route132_Text_2A40A4: @ 82A40A4
	.string "Je suppose que je dois pouvoir faire\n"
	.string "équipe avec ce vieil homme pour\l"
	.string "affronter l'autre équipe.$"

Route133_Text_2A40F0: @ 82A40F0
	.string "Le courant m'a mené ici. Toi aussi?\n"
	.string "C'est un coup du destin. Battons-nous!$"

Route133_Text_2A413F: @ 82A413F
	.string "Quelle force!\n"
	.string "Trop pour moi!$"

Route133_Text_2A4154: @ 82A4154
	.string "C'est bien ma chance… Un DRESSEUR\n"
	.string "aussi fort que toi qui atterrit ici…\l"
	.string "Je dois être maudit…$"

Route133_Text_2A41A8: @ 82A41A8
	.string "J'ai mené une existence de chagrin et\n"
	.string "de misère… J'ai fait naufrage et voilà\l"
	.string "où je me suis retrouvée…$"

Route133_Text_2A4200: @ 82A4200
	.string "Encore une autre défaite…$"

Route133_Text_2A420E: @ 82A420E
	.string "Une vie à la dérive…\n"
	.string "Je n'en veux plus!$"

Route133_Text_2A4236: @ 82A4236
	.string "Bienvenue!\n"
	.string "Je t'attendais!$"

Route133_Text_2A4258: @ 82A4258
	.string "Non! Je t'en prie!$"

Route133_Text_2A4264: @ 82A4264
	.string "Un DRESSEUR aussi fort et pourtant\n"
	.string "si jeune… C'est agaçant!$"

Route133_Text_2A4290: @ 82A4290
	.string "Comme les autres, je veux gagner. Mais\n"
	.string "je ne veux pas que mes POKéMON soient\l"
	.string "comme ceux des autres.$"

Route133_Text_2A42E0: @ 82A42E0
	.string "Zut!\n"
	.string "Je ne suis pas encore assez énergique!$"

Route133_Text_2A4304: @ 82A4304
	.string "C'est plus sympa de faire les choses à\n"
	.string "ma guise que de faire comme les autres.\l"
	.string "C'est évident!$"

Route133_Text_2A436A: @ 82A436A
	.string "J'ai fait tout le chemin jusqu'ici avec\n"
	.string "mon POKéMON OISEAU.$"

Route133_Text_2A439C: @ 82A439C
	.string "Tu…\n"
	.string "Tu gardes un tel sang-froid!$"

Route133_Text_2A43B9: @ 82A43B9
	.string "J'aimerais retourner à CIMETRONELLE,\n"
	.string "mais j'ai aussi appris à aimer ce lieu.$"

Route133_Text_2A4401: @ 82A4401
	.string "J'ai dû me battre des centaines de fois,\n"
	.string "mais j'ai arrêté de compter!$"

Route133_Text_2A443A: @ 82A443A
	.string "J'ai aussi perdu des centaines de fois,\n"
	.string "mais ça fait toujours aussi mal!$"

Route133_Text_2A4477: @ 82A4477
	.string "Continue comme ça, et un jour tu seras\n"
	.string "comme mon mari et moi!$"

Route133_Text_2A44BA: @ 82A44BA
	.string "Les jeunes n'en font qu'à leur tête. Ils\n"
	.string "n'ont vraiment rien dans le crâne.$"

Route133_Text_2A4505: @ 82A4505
	.string "Les jeunes n'ont vraiment aucun\n"
	.string "respect pour leurs aînés!$"

Route133_Text_2A4527: @ 82A4527
	.string "Ne laisse pas les autres diriger ta vie.\n"
	.string "Et essaie de toujours suivre ton but!$"

Route134_Text_2A4571: @ 82A4571
	.string "Même les POKéMON qui savent nager sont\n"
	.string "emportés par le courant.$"

Route134_Text_2A45BB: @ 82A45BB
	.string "Ouuuuuille!$"

Route134_Text_2A45C5: @ 82A45C5
	.string "Je crois que les POKéMON aiment bien\n"
	.string "les forts courants des environs.$"

Route134_Text_2A4609: @ 82A4609
	.string "Mes LOVDISC veulent un match sympa.\n"
	.string "Tu te joins à nous?$"

Route134_Text_2A4643: @ 82A4643
	.string "Oups!$"

Route134_Text_2A464B: @ 82A464B
	.string "Il y a un collectionneur qui recherche\n"
	.string "les ECAILLES de LOVDISC.$"

Route134_Text_2A4682: @ 82A4682
	.string "Dacodac! Assez flemmardé!\n"
	.string "Il est temps de combattre!$"

Route134_Text_2A46BE: @ 82A46BE
	.string "Encore carrément naze…$"

Route134_Text_2A46D2: @ 82A46D2
	.string "Mes POKéMON OISEAU sont vite fatigués\n"
	.string "après un long vol…$"

Route134_Text_2A4709: @ 82A4709
	.string "Tu es DRESSEUR de POKéMON.\n"
	.string "Les mots sont inutiles. Agissons!$"

Route134_Text_2A4745: @ 82A4745
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_2A475D: @ 82A475D
	.string "C'est moi qui te défie et c'est moi\n"
	.string "qui perds. J'ai vraiment honte…$"

Route134_Text_2A479E: @ 82A479E
	.string "Le mauvais temps sur cette zone nous\n"
	.string "permet d'être plus forts que jamais.$"

Route134_Text_2A47E1: @ 82A47E1
	.string "J'admets la défaite!$"

Route134_Text_2A47FD: @ 82A47FD
	.string "On va retourner au SITE METEORE\n"
	.string "pour s'entraîner davantage.\p"
	.string "Si ça te dit, tu n'as qu'à venir aussi.\n"
	.string "Je vais t'endurcir!$"

Route134_Text_2A4875: @ 82A4875
	.string "Notre… notre bateau!\n"
	.string "La marée l'a emmené!$"

Route134_Text_2A489B: @ 82A489B
	.string "Arrête, arrête, j'abandonne!$"

Route134_Text_2A48BD: @ 82A48BD
	.string "Si on ne peut pas SURFER, comment\n"
	.string "faire pour rentrer chez nous?\p"
	.string "En fait, je sais qu'un POKéMON K.O.\n"
	.string "peut utiliser SURF, mais ça me\l"
	.string "donne mauvaise conscience…$"

Route134_Text_2A4937: @ 82A4937
	.string "Est-ce que tes POKéMON peuvent éviter\n"
	.string "nos attaques rapides comme l'éclair?$"

Route134_Text_2A496B: @ 82A496B
	.string "Je ne savais pas qu'une telle technique\n"
	.string "existait! Tu m'as complètement battue!$"

Route134_Text_2A49B1: @ 82A49B1
	.string "Je n'ai pas perdu mon goût pour la\n"
	.string "vitesse. J'essaierai encore et encore!$"

Route134_Text_2A49E9: @ 82A49E9
	.string "Mes POKéMON ne pourront pas être\n"
	.string "battus si facilement!$"

Route134_Text_2A4A10: @ 82A4A10
	.string "Tu plaisantes?\n"
	.string "Comment t'as fait pour gagner?$"

Route134_Text_2A4A34: @ 82A4A34
	.string "Haha!\n"
	.string "Tu as gagné, très bien!\p"
	.string "Je vais affronter tous les DRESSEURS\n"
	.string "que je croiserai sur le chemin du retour\l"
	.string "pour retrouver mon vrai niveau!$"

Route134_Text_2A4A8F: @ 82A4A8F
	.string "Dis, t'aurais pas vu un autre MARIN\n"
	.string "dans l'coin?$"

Route134_Text_2A4AC1: @ 82A4AC1
	.string "Wow! C'était vraiment quelque chose!$"

Route134_Text_2A4AD8: @ 82A4AD8
	.string "Notre bateau a pris la mer.\p"
	.string "Mon compagnon est quelqu'un de timide,\n"
	.string "alors je suis un peu inquiet pour lui.$"
