gTrickHouse_Mechadoll_Oddish:: @ 27ECBC
	.string "MYSTHERBE$"

gTrickHouse_Mechadoll_Poochyena:: @ 27ECC3
	.string "MEDHYENA$"

gTrickHouse_Mechadoll_Taillow:: @ 27ECCD
	.string "NIRONDELLE$"

gTrickHouse_Mechadoll_Azurill:: @ 27ECD5
	.string "AZURILL$"

gTrickHouse_Mechadoll_Lotad:: @ 27ECDD
	.string "NENUPIOT$"

gTrickHouse_Mechadoll_Wingull:: @ 27ECE3
	.string "GOELISE$"

gTrickHouse_Mechadoll_Dustox:: @ 27ECEB
	.string "PAPINOX$"

gTrickHouse_Mechadoll_Zubat:: @ 27ECF2
	.string "NOSFERAPTI$"

gTrickHouse_Mechadoll_Nincada:: @ 27ECF8
	.string "NINGALE$"

gTrickHouse_Mechadoll_Ralts:: @ 27ED00
	.string "TARSAL$"

gTrickHouse_Mechadoll_Zigzagoon:: @ 27ED06
	.string "ZIGZATON$"

gTrickHouse_Mechadoll_Slakoth:: @ 27ED10
	.string "PARECOOL$"

gTrickHouse_Mechadoll_Poochyena2:: @ 27ED18
	.string "MEDHYENA$"

gTrickHouse_Mechadoll_Shroomish:: @ 27ED22
	.string "BALIGNON$"

gTrickHouse_Mechadoll_Zigzagoon2:: @ 27ED2C
	.string "ZIGZATON$"

gTrickHouse_Mechadoll_Poochyena3:: @ 27ED36
	.string "MEDHYENA$"

gTrickHouse_Mechadoll_Zubat2:: @ 27ED40
	.string "NOSFERAPTI$"

gTrickHouse_Mechadoll_Carvanha:: @ 27ED46
	.string "CARVANHA$"

gTrickHouse_Mechadoll_BurnHeal:: @ 27ED4F
	.string "ANTI-BRULE$"

gTrickHouse_Mechadoll_HarborMail:: @ 27ED59
	.string "LETTRES PORT$"

gTrickHouse_Mechadoll_SamePrice:: @ 27ED65
	.string "Même prix$"

gTrickHouse_Mechadoll_60Yen:: @ 27ED70
	.string "60¥$"

gTrickHouse_Mechadoll_55Yen:: @ 27ED74
	.string "55¥$"

gTrickHouse_Mechadoll_Nothing:: @ 27ED78
	.string "Rien$"

gTrickHouse_Mechadoll_CostMore:: @ 27ED80
	.string "Oui$"

gTrickHouse_Mechadoll_CostLess:: @ 27ED95
	.string "Non$"

gTrickHouse_Mechadoll_SamePrice2:: @ 27EDAA
	.string "Même prix$"

gTrickHouse_Mechadoll_Male:: @ 27EDB5
	.string "Plus d'hommes$"

gTrickHouse_Mechadoll_Female:: @ 27EDBA
	.string "Plus de femmes$"

gTrickHouse_Mechadoll_Neither:: @ 27EDC1
	.string "Aucun des deux$"

gTrickHouse_Mechadoll_ElderlyMen:: @ 27EDC9
	.string "Plus de vieux messieurs$"

gTrickHouse_Mechadoll_ElderlyLadies:: @ 27EDD5
	.string "Plus de vieilles dames$"

gTrickHouse_Mechadoll_SameNumber:: @ 27EDE4
	.string "Le même nombre$"

gTrickHouse_Mechadoll_None:: @ 27EDF0
	.string "Aucune$"

gTrickHouse_Mechadoll_One:: @ 27EDF5
	.string "1$"

gTrickHouse_Mechadoll_Two:: @ 27EDF7
	.string "2$"

gTrickHouse_Mechadoll_Two2:: @ 27EDF9
	.string "2$"

gTrickHouse_Mechadoll_Three:: @ 27EDFB
	.string "3$"

gTrickHouse_Mechadoll_Four:: @ 27EDFD
	.string "4$"

gTrickHouse_Mechadoll_Six:: @ 27EDFF
	.string "6$"

gTrickHouse_Mechadoll_Seven:: @ 27EE01
	.string "7$"

gTrickHouse_Mechadoll_Eight:: @ 27EE03
	.string "8$"

gTrickHouse_Mechadoll_Six2:: @ 27EE05
	.string "6$"

gTrickHouse_Mechadoll_Seven2:: @ 27EE07
	.string "7$"

gTrickHouse_Mechadoll_Eight2:: @ 27EE09
	.string "8$"
