FortreeCity_House3_MapScripts:: @ 8217AE7
	.byte 0

FortreeCity_House3_EventScript_217AE8:: @ 8217AE8
	msgbox FortreeCity_House3_Text_217AFA, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_217AF1:: @ 8217AF1
	msgbox FortreeCity_House3_Text_217C22, MSGBOX_NPC
	end

FortreeCity_House3_Text_217AFA: @ 8217AFA
	.string "En parlant de POKéDEX, ça me\n"
	.string "rappelle quelque chose.\p"
	.string "J'ai rencontré ce DRESSEUR, PIERRE,\n"
	.string "quand je cherchais des pierres rares.\p"
	.string "Si t'avais vu comme ses POKéMON\n"
	.string "étaient surprenants!\p"
	.string "Non seulement ils étaient rares, mais\n"
	.string "ils étaient également soumis à un rude\l"
	.string "entraînement.\p"
	.string "Ce DRESSEUR est peut-être encore plus\n"
	.string "fort que le CHAMPION de cette ville…$"

FortreeCity_House3_Text_217C22: @ 8217C22
	.string "Quelle est cette chose que tu as là?\p"
	.string "… … … … … …\p"
	.string "Oh, ça s'appelle un POKéDEX?\n"
	.string "C'est très impressionnant!$"

