VictoryRoad_B1F_MapScripts:: @ 82364E4
	.byte 0

VictoryRoad_B1F_EventScript_2364E5:: @ 82364E5
	trainerbattle_single TRAINER_SAMUEL, VictoryRoad_B1F_Text_236558, VictoryRoad_B1F_Text_2365AD
	msgbox VictoryRoad_B1F_Text_2365C4, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_2364FC:: @ 82364FC
	trainerbattle_single TRAINER_SHANNON, VictoryRoad_B1F_Text_2365FD, VictoryRoad_B1F_Text_23664D
	msgbox VictoryRoad_B1F_Text_236678, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_236513:: @ 8236513
	trainerbattle_single TRAINER_MICHELLE, VictoryRoad_B1F_Text_2366C2, VictoryRoad_B1F_Text_23670B
	msgbox VictoryRoad_B1F_Text_23671B, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_23652A:: @ 823652A
	trainerbattle_single TRAINER_MITCHELL, VictoryRoad_B1F_Text_236757, VictoryRoad_B1F_Text_236780
	msgbox VictoryRoad_B1F_Text_2367A7, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_236541:: @ 8236541
	trainerbattle_single TRAINER_HALLE, VictoryRoad_B1F_Text_2367FD, VictoryRoad_B1F_Text_23683B
	msgbox VictoryRoad_B1F_Text_23684C, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_Text_236558: @ 8236558
	.string "Penser que je me rapproche de\n"
	.string "la LIGUE POKéMON…\p"
	.string "J'ai le trac…$"

VictoryRoad_B1F_Text_2365AD: @ 82365AD
	.string "Je n'ai rien pu faire…$"

VictoryRoad_B1F_Text_2365C4: @ 82365C4
	.string "La LIGUE POKéMON s'éloigne à nouveau…\n"
	.string "Quelle déception…$"

VictoryRoad_B1F_Text_2365FD: @ 82365FD
	.string "Pour réussir à parcourir le chemin qui\n"
	.string "te mènera à la LIGUE POKéMON, il te\l"
	.string "faudra avoir la confiance de tes\l"
	.string "POKéMON.$"

VictoryRoad_B1F_Text_23664D: @ 823664D
	.string "Votre relation est basée sur une\n"
	.string "solide confiance.$"

VictoryRoad_B1F_Text_236678: @ 8236678
	.string "Comme les POKéMON et les DRESSEURS\n"
	.string "sont toujours ensemble, leur confiance\l"
	.string "mutuelle grandit.$"

VictoryRoad_B1F_Text_2366C2: @ 82366C2
	.string "Ce n'est pas encore là. Ce n'est qu'une\n"
	.string "étape sur la route de la LIGUE POKéMON.$"

VictoryRoad_B1F_Text_23670B: @ 823670B
	.string "C'est en ce sens qu'il faut aller!$"

VictoryRoad_B1F_Text_23671B: @ 823671B
	.string "Tu vas te débrouiller, c'est sûr!\n"
	.string "Tes POKéMON ont tous envie d'y aller!$"

VictoryRoad_B1F_Text_236757: @ 8236757
	.string "Mes POKéMON me font penser\n"
	.string "aux étoiles!$"

VictoryRoad_B1F_Text_236780: @ 8236780
	.string "Je n'avais encore jamais rencontré\n"
	.string "quelqu'un comme toi!$"

VictoryRoad_B1F_Text_2367A7: @ 82367A7
	.string "Même quand tu ne te bats pas, j'arrive\n"
	.string "à sentir une grande force émanant\l"
	.string "de tes POKéMON et toi…$"

VictoryRoad_B1F_Text_2367FD: @ 82367FD
	.string "OK, pas besoin de t'énerver!\n"
	.string "Relax, ça va bien se passer!$"

VictoryRoad_B1F_Text_23683B: @ 823683B
	.string "Ouah!\n"
	.string "Formidable!$"

VictoryRoad_B1F_Text_23684C: @ 823684C
	.string "C'est bien la ROUTE VICTOIRE.\p"
	.string "Mais ce n'est pas si différent de la\n"
	.string "route que tu as déjà empruntée.\p"
	.string "Essaie de profiter du reste du\n"
	.string "chemin à parcourir!$"

