MagmaHideout_3F_1R_MapScripts:: @ 823A1B2
	.byte 0

MagmaHideout_3F_1R_EventScript_23A1B3:: @ 823A1B3
	trainerbattle_single TRAINER_GRUNT_46, MagmaHideout_3F_1R_Text_23A1E1, MagmaHideout_3F_1R_Text_23A229
	msgbox MagmaHideout_3F_1R_Text_23A246, MSGBOX_AUTOCLOSE
	end

MagmaHideout_3F_1R_EventScript_23A1CA:: @ 823A1CA
	trainerbattle_single TRAINER_GRUNT_53, MagmaHideout_3F_1R_Text_23A293, MagmaHideout_3F_1R_Text_23A353
	msgbox MagmaHideout_3F_1R_Text_23A37C, MSGBOX_AUTOCLOSE
	end

MagmaHideout_3F_1R_Text_23A1E1: @ 823A1E1
	.string "Qu'est-ce que j'ai fait de mal pour\n"
	.string "être obligé de monter la garde ici?\p"
	.string "Mon oreille gauche est presque\n"
	.string "en train de brûler!$"

MagmaHideout_3F_1R_Text_23A229: @ 823A229
	.string "Je dois avoir des bouffées de chaleur…$"

MagmaHideout_3F_1R_Text_23A246: @ 823A246
	.string "Tu trouves pas ça bizarre qu'on porte\n"
	.string "des bonnets dans cette fournaise?$"

MagmaHideout_3F_1R_Text_23A293: @ 823A293
	.string "Nous avons rejoint la TEAM pour aider\n"
	.string "notre leader à concrétiser sa vision.\p"
	.string "Je me moque que tu appartiennes\n"
	.string "ou non à la TEAM AQUA.\p"
	.string "Je ne laisserai personne interférer\n"
	.string "dans nos plans!$"

MagmaHideout_3F_1R_Text_23A353: @ 823A353
	.string "Oh non…\n"
	.string "Je n'ai rien pu faire.$"

MagmaHideout_3F_1R_Text_23A37C: @ 823A37C
	.string "Ecoute-moi bien.\n"
	.string "Ne te trompe pas d'ennemi.\p"
	.string "N'écoute pas la TEAM AQUA.\n"
	.string "Ne crois pas leurs mensonges!$"

