SootopolisCity_House7_MapScripts:: @ 82270CB
	.byte 0

SootopolisCity_House7_EventScript_2270CC:: @ 82270CC
	msgbox SootopolisCity_House7_Text_2270DE, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_2270D5:: @ 82270D5
	msgbox SootopolisCity_House7_Text_227190, MSGBOX_NPC
	end

SootopolisCity_House7_Text_2270DE: @ 82270DE
	.string "Un volcan immergé est entré en éruption\n"
	.string "et remonté des profondeurs marines.\p"
	.string "Son cratère a émergé de la mer et\n"
	.string "s'est rempli d'eau de pluie.\p"
	.string "C'est ainsi que la ville d'ATALANOPOLIS\n"
	.string "a été créée.$"

SootopolisCity_House7_Text_227190: @ 8227190
	.string "La grotte qui relie ATALANOPOLIS au\n"
	.string "monde extérieur…\p"
	.string "C'est comme si elle avait été créée\n"
	.string "pour empêcher quelque chose de sortir.\p"
	.string "Ou s'agit-il juste de mon imagination?$"

